import {
  BadRequestException,
  Injectable,
  Logger,
  Optional,
} from '@nestjs/common';
import { db } from '@ananya/database';
import { categories, components, manufacturers } from '@ananya/database/schema';
import { and, asc, desc, eq, gte, inArray } from '@ananya/database/query';
import { MlService, extractManufacturerPartNumber } from './ml.service';
import {
  ComponentReviewQueueService,
  type PersistComponentFindingInput,
} from './component-review-queue.service';
import {
  DEFAULT_COMPONENT_AUDIT_LIMIT,
  MAX_COMPONENT_AUDIT_LIMIT,
  COMPONENT_REVIEW_ISSUE_TYPES,
  type ComponentReviewAuditScope,
  type ComponentReviewIssueCategory,
  type ConfidenceLevel,
} from './component-review-queue.dtos';
import { DataPacksService } from '../data-packs/data-packs.service';
import type { ComponentSuggestionResponseDto, EvidenceItemDto } from './dtos';

/**
 * Component Intelligence Review Analyzer (Pass 2).
 *
 * Analyzes PERSISTED components and produces evidence-backed review findings
 * for `ComponentReviewQueueService.persistFindings()`.
 *
 * Core principle: the queue is not a firehose for every ML output. A finding is
 * only generated when there is a *meaningful discrepancy* a human should judge:
 *
 *  - the stored value is missing and analysis can supply one, or
 *  - the stored value disagrees with a high-confidence, evidence-backed
 *    conclusion, or
 *  - two persisted records appear to describe the same part.
 *
 * Rules intentionally NOT implemented here:
 *  - "no suggestion available" cases (nothing to review),
 *  - new-category candidates (creating taxonomies from a review queue is out of
 *    scope; category-attribute intelligence owns taxonomy curation),
 *  - attribute-level data quality (missing/conflicting component attribute
 *    values) which belongs to the following pass.
 *
 * Safety: the analyzer NEVER mutates component data. It only persists findings.
 */

/** Bumped when rule semantics change so fingerprints are re-evaluated. */
export const COMPONENT_REVIEW_INTELLIGENCE_VERSION = 'component-review-v1';

/** Minimum confidence for ML-derived (manufacturer/category) findings. */
export const REVIEW_MIN_CONFIDENCE = 0.85;

/** Shortest normalized part number considered a real identifier. */
export const MIN_MPN_LENGTH = 4;

/**
 * Values that are recorded in the MPN column but are not identifiers.
 * Comparing placeholders would flag every placeholder-bearing component as a
 * duplicate of every other.
 */
export const PLACEHOLDER_MPNS: readonly string[] = [
  'NA',
  'NONE',
  'NULL',
  'TBD',
  'TBA',
  'UNKNOWN',
  'TOBEDETERMINED',
  'MISSING',
  'GENERIC',
  'VARIOUS',
  'SEEABOVE',
  'NOTAPPLICABLE',
];

/**
 * Packaging / reel suffixes that do not change the engineering part.
 * Mirrors `strip_packaging_suffix()` in
 * `apps/ml/app/services/duplicate_detector.py` so the review queue reaches the
 * same conclusion as the creation-time duplicate detector.
 */
export const PACKAGING_SUFFIXES: readonly string[] = [
  'TR',
  'REEL',
  'TAPE',
  '7R',
  '07',
  '13',
  'CTU',
  'TU',
];

/** Producer tags recorded on findings generated by this analyzer. */
export const COMPONENT_ANALYZER_SOURCES: readonly string[] = [
  'analyzer:identity',
  'analyzer:manufacturer',
  'analyzer:category',
  'analyzer:duplicate',
];

export const DEFAULT_COMPONENT_AUDIT_RECENT_DAYS = 30;

/**
 * Upper bound on duplicate findings produced by a single audit. Duplicate
 * detection reconciles the whole catalog, so a pathologically duplicated
 * catalog could otherwise generate an unbounded write. Ordering is
 * deterministic, so re-running an audit continues from a stable point.
 */
export const MAX_DUPLICATE_FINDINGS_PER_AUDIT = 500;

/**
 * Caps the duplicate findings written by a single audit.
 *
 * Input order is deterministic, so a capped audit always produces the same
 * subset and re-running it continues from a stable point instead of thrashing.
 */
export function capDuplicateFindings(
  findings: PersistComponentFindingInput[],
  max: number = MAX_DUPLICATE_FINDINGS_PER_AUDIT,
): { findings: PersistComponentFindingInput[]; truncated: boolean } {
  if (findings.length <= max) return { findings, truncated: false };
  return { findings: findings.slice(0, max), truncated: true };
}

export interface AnalyzableComponent {
  id: string;
  sku: string;
  name: string;
  description: string | null;
  manufacturerPartNumber: string | null;
  manufacturerId: string | null;
  categoryId: string | null;
  unit: string;
  isActive: boolean;
  createdAt: Date;
  updatedAt: Date;
}

export interface ComponentCategoryRef {
  id: string;
  code: string;
  name: string;
  parentId: string | null;
}

export interface ComponentManufacturerRef {
  id: string;
  code: string;
  name: string;
}

export interface CatalogMpnEntry {
  id: string;
  sku: string;
  name: string;
  manufacturerPartNumber: string;
  manufacturerId: string | null;
  categoryId: string | null;
  isActive: boolean;
  createdAt: Date;
  updatedAt: Date;
}

export interface EvaluateComponentFindingsInput {
  component: AnalyzableComponent;
  suggestion: ComponentSuggestionResponseDto | null;
  categoryById: Map<string, ComponentCategoryRef>;
  manufacturerById: Map<string, ComponentManufacturerRef>;
  mpnIndex: Map<string, CatalogMpnEntry[]>;
  packagePatterns: string[];
  intelligenceVersion: string;
}

export interface DetectDuplicateFindingsInput {
  catalog: CatalogMpnEntry[];
  scopeComponentIds: Set<string>;
  includeInactive: boolean;
  intelligenceVersion: string;
}

export interface RunComponentAuditInput {
  scope?: ComponentReviewAuditScope;
  componentIds?: string[];
  sinceDays?: number;
  limit?: number;
  includeInactive?: boolean;
}

export interface ComponentAuditResult {
  scope: ComponentReviewAuditScope;
  analyzedCount: number;
  /** Requested component ids that do not exist (SELECTED scope only). */
  notFoundCount: number;
  /** Components whose analysis failed; they are excluded from reconciliation. */
  failedCount: number;
  mlActiveCount: number;
  persistedCount: number;
  staledCount: number;
  duplicateFindingsCount: number;
  /** True when duplicate findings hit `MAX_DUPLICATE_FINDINGS_PER_AUDIT`. */
  duplicateFindingsTruncated: boolean;
  findingsByCategory: Record<string, number>;
  pendingTotal: number;
  /**
   * True when the batch reached its limit: additional components may not have
   * been analyzed. Re-running the audit is idempotent.
   */
  batchLimitReached: boolean;
  durationMs: number;
  intelligenceVersion: string;
  /** Canonical issue-type taxonomy exposed so clients never hardcode it. */
  issueTypes: Record<ComponentReviewIssueCategory, readonly string[]>;
}

/**
 * Canonical normalization for part numbers: keep alphanumerics, uppercase.
 * Mirrors the normalization used by the creation-time duplicate detector and
 * the ML microservice.
 */
export function normalizeMpn(value?: string | null): string | null {
  if (!value) return null;
  const normalized = value.replace(/[^A-Za-z0-9]/g, '').toUpperCase();
  return normalized.length > 0 ? normalized : null;
}

export function normalizeName(value?: string | null): string {
  return (value ?? '')
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]/g, '');
}

export function isPlaceholderMpn(normalizedMpn: string): boolean {
  return PLACEHOLDER_MPNS.includes(normalizedMpn);
}

/**
 * True when two normalized part numbers identify the same engineering part and
 * must therefore never be reported as an MPN conflict:
 *
 *  - identical values,
 *  - values differing only by a packaging/reel suffix (`...0710KL` vs
 *    `...0710KLTR`),
 *  - one being a separator-split fragment of the other. Free text such as
 *    `RC0805FR 0710KL` is tokenized into `RC0805FR` and `0710KL`, so a fragment
 *    is extraction noise rather than a different identifier.
 */
export function areEquivalentMpns(first: string, second: string): boolean {
  if (first === second) return true;
  if (stripPackagingSuffix(first) === stripPackagingSuffix(second)) return true;
  return first.includes(second) || second.includes(first);
}

/**
 * Candidate identifier tokens inside free text. Matches the token shape used by
 * the creation-time extractor: an alphanumeric run of at least five characters
 * with no whitespace.
 */
const MPN_TOKEN_PATTERN = /\b[A-Z0-9][A-Z0-9._/-]{4,}\b/gi;

/**
 * Finds the first token in free text that plausibly is a manufacturer part
 * number, skipping words, footprint codes, engineering measurements,
 * placeholders, and internal values.
 *
 * `extractManufacturerPartNumber()` is reused per candidate so trailing
 * manufacturer/product suffixes (`-YAGEO-SMD`) are stripped identically to the
 * creation-time flow. Unlike that helper it keeps scanning instead of giving up
 * on the first regex match, which is required when the text is a component name
 * such as "Chip Resistor RC0805FR-0727RL".
 */
export function extractCandidateMpnFromText(
  text: string,
  manufacturers: Array<{ name: string; code: string }> = [],
  packagePatterns: readonly string[] = [],
): string | undefined {
  const tokens = text.match(MPN_TOKEN_PATTERN) ?? [];

  for (const token of tokens) {
    const candidate = extractManufacturerPartNumber(token, manufacturers);
    if (!candidate) continue;

    const normalized = normalizeMpn(candidate);
    if (!normalized || normalized.length < MIN_MPN_LENGTH) continue;
    if (!/[A-Z]/.test(normalized) || !/\d/.test(normalized)) continue;
    if (isPlaceholderMpn(normalized)) continue;
    if (isPackageCode(normalized, packagePatterns)) continue;
    // Descriptions are full of ratings ("27Ω ±1% 125mW 0805"); those are
    // specifications, never manufacturer part numbers.
    if (isEngineeringMeasurement(normalized, packagePatterns)) continue;

    return candidate;
  }

  return undefined;
}

/**
 * Removes a trailing packaging/reel code when what remains is still a
 * substantial identifier (mirrors the Python guard `len(norm) > len(suffix)+4`).
 */
export function stripPackagingSuffix(normalizedMpn: string): string {
  for (const suffix of PACKAGING_SUFFIXES) {
    if (
      normalizedMpn.endsWith(suffix) &&
      normalizedMpn.length > suffix.length + 4
    ) {
      return normalizedMpn.slice(0, normalizedMpn.length - suffix.length);
    }
  }
  return normalizedMpn;
}

/**
 * True when the token is actually a footprint/package code rather than a
 * manufacturer part number (e.g. `0805`, `SOT23`). Package codes legitimately
 * appear in component names, so they must not be suggested as MPNs.
 */
export function isPackageCode(
  normalizedToken: string,
  packagePatterns: readonly string[],
): boolean {
  if (/^(0[2468]0[1235]|1[0-9]{3}|2[0-9]{3})$/.test(normalizedToken)) {
    return true;
  }
  return packagePatterns.some((pattern) => {
    const normalized = normalizeMpn(pattern);
    return Boolean(normalized) && normalized === normalizedToken;
  });
}

/**
 * Units and unit-like qualifiers that mark a token as an engineering
 * measurement rather than an identifier.
 *
 * Matched against the UPPERCASED token suffix, so case never matters: `125mW`
 * and `125MW` are the same measurement. Deliberately excludes ambiguous
 * single-letter abbreviations that appear inside legitimate part numbers as
 * ordinary characters (for example `R` in `RC0805FR`, or `C` in
 * `C0805C104K5RACTU`), and excludes `C` for temperature because `°C` separates
 * on the degree sign and never forms a single token.
 */
export const MEASUREMENT_UNITS: readonly string[] = [
  // Power
  'W',
  'MW',
  'KW',
  // Voltage
  'V',
  'MV',
  'KV',
  'VAC',
  'VDC',
  // Current
  'A',
  'MA',
  'UA',
  // Charge / capacity
  'AH',
  'MAH',
  // Resistance (`Ω` and `kΩ` separate on the symbol and never form a token)
  'OHM',
  'KOHM',
  'MOHM',
  // Frequency
  'HZ',
  'KHZ',
  'MHZ',
  'GHZ',
  // Capacitance
  'F',
  'UF',
  'NF',
  'PF',
  'MF',
  // Inductance
  'H',
  'UH',
  'MH',
  'NH',
  // Temperature (`DEG` / `DEGC` cover "25degC"; `°C` is split by the symbol)
  'DEG',
  'DEGC',
  // Ratio and percentage notations
  'DB',
  'PCT',
];

/**
 * Amount + unit shape: a leading numeric amount immediately followed by an
 * alphabetical unit run, plus whatever trails it.
 */
const MEASUREMENT_PATTERN = /^(\d+(?:\.\d+)?)([A-Z]+)(.*)$/;

/**
 * True when the candidate is an engineering measurement rather than a part
 * number (for example `125MW`, `100MA`, `10KHZ`, `27OHM`, `1000V`).
 *
 * A measurement requires the numeric amount to be at the very START of the
 * token, followed immediately by a known unit. That constraint is what keeps
 * legitimate identifiers safe: the `N4148`/`N2222` in `1N4148`/`2N2222` is not
 * a unit, and identifiers that merely contain unit-like letters after a letter
 * prefix (`RC0805FR-0727RL`, `LM358DR`, `SSM3K35AMFV`, `C0805C104K5RACTU`)
 * never reach the unit check because they do not begin with a number.
 *
 * A trailing remainder is only tolerated when it is itself a footprint code, so
 * compound descriptor tokens such as `125MW0805` are still rejected.
 */
export function isEngineeringMeasurement(
  normalizedToken: string,
  packagePatterns: readonly string[] = [],
): boolean {
  const match = normalizedToken.match(MEASUREMENT_PATTERN);
  if (!match) return false;

  const unit = match[2];
  const remainder = match[3];
  if (!unit || !MEASUREMENT_UNITS.includes(unit)) return false;

  if (!remainder) return true;
  return isPackageCode(remainder, packagePatterns);
}

export function buildMpnIndex(
  catalog: CatalogMpnEntry[],
): Map<string, CatalogMpnEntry[]> {
  const index = new Map<string, CatalogMpnEntry[]>();
  for (const entry of catalog) {
    const normalized = normalizeMpn(entry.manufacturerPartNumber);
    if (!normalized) continue;
    const bucket = index.get(normalized);
    if (bucket) {
      bucket.push(entry);
    } else {
      index.set(normalized, [entry]);
    }
  }
  return index;
}

/** Stable ordering: oldest record first, ties broken by id. */
export function compareCatalogOrder(
  a: CatalogMpnEntry,
  b: CatalogMpnEntry,
): number {
  const delta = a.createdAt.getTime() - b.createdAt.getTime();
  return delta !== 0 ? delta : a.id.localeCompare(b.id);
}

/**
 * True when the two categories are the same node or one is an ancestor of the
 * other. Re-categorising `Resistors` to `Electronic Components` is a hierarchy
 * refinement, not a conflict worth reviewing.
 */
export function areCategoriesRelated(
  firstId: string,
  secondId: string,
  categoryById: Map<string, ComponentCategoryRef>,
): boolean {
  if (firstId === secondId) return true;
  return (
    collectAncestorIds(firstId, categoryById).has(secondId) ||
    collectAncestorIds(secondId, categoryById).has(firstId)
  );
}

function collectAncestorIds(
  categoryId: string,
  categoryById: Map<string, ComponentCategoryRef>,
): Set<string> {
  const ids = new Set<string>();
  let current: string | null = categoryId;
  while (current && !ids.has(current)) {
    ids.add(current);
    current = categoryById.get(current)?.parentId ?? null;
  }
  return ids;
}

function isHighConfidence(
  level: ConfidenceLevel | undefined | null,
  confidence: number | undefined | null,
): boolean {
  return (
    level === 'HIGH' &&
    typeof confidence === 'number' &&
    confidence >= REVIEW_MIN_CONFIDENCE
  );
}

function toEvidence(
  items: EvidenceItemDto[] | undefined | null,
  limit = 5,
): Array<Record<string, unknown>> {
  return (items ?? []).slice(0, limit).map((item) => ({
    type: item.type,
    description: item.description,
    weight: item.weight,
    ...(item.source ? { source: item.source } : {}),
  }));
}

function truncate(value: string, maxLength: number): string {
  return value.length <= maxLength
    ? value
    : `${value.slice(0, maxLength - 1)}…`;
}

/**
 * Evaluates identity and classification rules for a single persisted
 * component. Pure and deterministic so rules can be unit tested without a
 * database or the ML service.
 */
export function evaluateComponentFindings(
  input: EvaluateComponentFindingsInput,
): PersistComponentFindingInput[] {
  return [
    ...buildMpnFindings(input),
    ...buildManufacturerFindings(input),
    ...buildCategoryFindings(input),
  ];
}

interface ExtractedMpnContext {
  extracted: string;
  normalized: string;
  sourceText: string;
  existingOwners: CatalogMpnEntry[];
}

/**
 * Locates an independent manufacturer part number in the component's own name
 * and description text.
 *
 * The persisted MPN column is deliberately excluded: comparing a column with
 * itself cannot produce evidence. Text extraction also ignores the internal SKU
 * and footprint codes so neither is mistaken for a manufacturer identifier.
 */
function resolveExtractedMpn(
  input: EvaluateComponentFindingsInput,
): ExtractedMpnContext | null {
  const { component, manufacturerById, mpnIndex, packagePatterns } = input;

  const sourceText = [component.name, component.description]
    .filter((part): part is string => Boolean(part && part.trim()))
    .join(' ')
    .trim();
  if (!sourceText) return null;

  const manufacturerTerms = Array.from(manufacturerById.values()).map(
    (manufacturer) => ({ name: manufacturer.name, code: manufacturer.code }),
  );
  const extracted = extractCandidateMpnFromText(
    sourceText,
    manufacturerTerms,
    packagePatterns,
  );
  if (!extracted) return null;

  const normalized = normalizeMpn(extracted);
  if (!normalized) return null;

  // An internal SKU repeated as an MPN carries no manufacturer identity.
  if (normalized === normalizeMpn(component.sku)) return null;

  return {
    extracted,
    normalized,
    sourceText,
    existingOwners: (mpnIndex.get(normalized) ?? []).filter(
      (entry) => entry.id !== component.id,
    ),
  };
}

/**
 * MPN identity rules.
 *
 * - `MPN_MISSING`: no MPN persisted, but one is identifiable from the text.
 * - `MPN_CONFLICT`: an MPN is persisted and the text identifies a *different*
 *   part number. Formatting and packaging variants are treated as equivalent
 *   and never flagged, because they describe the same engineering part.
 */
function buildMpnFindings(
  input: EvaluateComponentFindingsInput,
): PersistComponentFindingInput[] {
  const { component, intelligenceVersion } = input;
  const persisted = component.manufacturerPartNumber?.trim() || null;
  const resolved = resolveExtractedMpn(input);
  if (!resolved) return [];

  const { extracted, normalized, sourceText, existingOwners } = resolved;

  const evidence: Array<Record<string, unknown>> = [
    {
      type: 'mpn_pattern',
      description: `Manufacturer part number "${extracted}" identified in the component name or description`,
      weight: 0.9,
      source: 'analyzer:mpn_extraction',
    },
  ];
  if (existingOwners.length > 0) {
    const [firstOwner] = existingOwners;
    evidence.push({
      type: 'existing_data',
      description:
        existingOwners.length === 1
          ? `Extracted part number already belongs to component ${firstOwner?.sku}`
          : `Extracted part number already belongs to ${existingOwners.length} other components (e.g. ${firstOwner?.sku})`,
      weight: 0.75,
      source: 'database:components.manufacturer_part_number',
    });
  }

  const collidesWithExistingComponent = existingOwners.length > 0;
  const analyzedText = truncate(sourceText, 300);

  if (!persisted) {
    return [
      {
        componentId: component.id,
        issueType: 'MPN_MISSING',
        issueCategory: 'IDENTITY',
        field: 'manufacturerPartNumber',
        title: 'Manufacturer part number missing',
        description: `No manufacturer part number is recorded, but "${extracted}" was identified in the component name or description.`,
        currentValue: { manufacturerPartNumber: null },
        suggestedValue: {
          manufacturerPartNumber: extracted,
          normalizedMpn: normalized,
          collidesWithExistingComponent,
        },
        confidence: 0.9,
        confidenceLevel: 'HIGH',
        evidence,
        source: 'analyzer:identity',
        intelligenceVersion,
        componentUpdatedAt: component.updatedAt,
        metadata: { rule: 'MPN_MISSING', analyzedText },
      },
    ];
  }

  const persistedNormalized = normalizeMpn(persisted);
  if (!persistedNormalized) return [];

  if (areEquivalentMpns(persistedNormalized, normalized)) return [];

  return [
    {
      componentId: component.id,
      issueType: 'MPN_CONFLICT',
      issueCategory: 'IDENTITY',
      field: 'manufacturerPartNumber',
      title: 'Manufacturer part number may be incorrect',
      description: `Recorded manufacturer part number is "${persisted}", but "${extracted}" was identified in the component name or description.`,
      currentValue: { manufacturerPartNumber: persisted },
      suggestedValue: {
        manufacturerPartNumber: extracted,
        normalizedMpn: normalized,
        collidesWithExistingComponent,
      },
      confidence: 0.9,
      confidenceLevel: 'HIGH',
      evidence: [
        ...evidence,
        {
          type: 'anomaly',
          description: `Recorded value "${persisted}" and identified value "${extracted}" differ after normalization`,
          weight: 0.9,
          source: 'analyzer:mpn_conflict',
        },
      ],
      source: 'analyzer:identity',
      intelligenceVersion,
      componentUpdatedAt: component.updatedAt,
      metadata: {
        rule: 'MPN_CONFLICT',
        analyzedText,
        persistedNormalizedMpn: persistedNormalized,
      },
    },
  ];
}

function buildManufacturerFindings(
  input: EvaluateComponentFindingsInput,
): PersistComponentFindingInput[] {
  const { component, suggestion, manufacturerById, intelligenceVersion } =
    input;
  const manufacturer = suggestion?.manufacturer;
  if (!manufacturer) return [];
  if (manufacturer.resolution === 'UNKNOWN') return [];
  if (
    !isHighConfidence(manufacturer.confidenceLevel, manufacturer.confidence)
  ) {
    return [];
  }

  const suggestedName = manufacturer.manufacturerName?.trim();
  if (!suggestedName) return [];

  const suggestedValue: Record<string, unknown> = {
    manufacturerId: manufacturer.manufacturerId ?? null,
    manufacturerName: suggestedName,
    manufacturerCode: manufacturer.manufacturerCode ?? null,
    resolution: manufacturer.resolution,
    matchType: manufacturer.matchType,
  };

  if (!component.manufacturerId) {
    return [
      {
        componentId: component.id,
        issueType: 'MANUFACTURER_UNRESOLVED',
        issueCategory: 'IDENTITY',
        field: 'manufacturer',
        title: 'Manufacturer not assigned',
        description: `No manufacturer is recorded for this component. Analysis resolved "${suggestedName}" (${manufacturer.matchType}).`,
        currentValue: { manufacturerId: null, manufacturerName: null },
        suggestedValue,
        confidence: manufacturer.confidence,
        confidenceLevel: manufacturer.confidenceLevel ?? 'HIGH',
        evidence: toEvidence(manufacturer.evidence),
        source: 'analyzer:manufacturer',
        intelligenceVersion,
        componentUpdatedAt: component.updatedAt,
        metadata: { rule: 'MANUFACTURER_UNRESOLVED' },
      },
    ];
  }

  const stored = manufacturerById.get(component.manufacturerId);
  // Dangling reference: repairing master data references is not this rule's job.
  if (!stored) return [];

  if (manufacturer.manufacturerId === stored.id) return [];

  const matchesStoredName =
    normalizeName(suggestedName) === normalizeName(stored.name) ||
    normalizeName(suggestedName) === normalizeName(stored.code) ||
    normalizeName(manufacturer.manufacturerCode) ===
      normalizeName(stored.name) ||
    normalizeName(manufacturer.manufacturerCode) === normalizeName(stored.code);
  if (matchesStoredName) return [];

  return [
    {
      componentId: component.id,
      issueType: 'MANUFACTURER_CONFLICT',
      issueCategory: 'IDENTITY',
      field: 'manufacturer',
      title: 'Manufacturer may be incorrect',
      description: `Recorded manufacturer is "${stored.name}", but analysis resolved "${suggestedName}" (${manufacturer.matchType}).`,
      currentValue: {
        manufacturerId: stored.id,
        manufacturerName: stored.name,
        manufacturerCode: stored.code,
      },
      suggestedValue,
      confidence: manufacturer.confidence,
      confidenceLevel: manufacturer.confidenceLevel ?? 'HIGH',
      evidence: toEvidence(manufacturer.evidence),
      source: 'analyzer:manufacturer',
      intelligenceVersion,
      componentUpdatedAt: component.updatedAt,
      metadata: { rule: 'MANUFACTURER_CONFLICT' },
    },
  ];
}

function buildCategoryFindings(
  input: EvaluateComponentFindingsInput,
): PersistComponentFindingInput[] {
  const { component, suggestion, categoryById, intelligenceVersion } = input;
  const category = suggestion?.category;
  if (!category) return [];
  if (!isHighConfidence(category.confidenceLevel, category.confidence)) {
    return [];
  }
  // Only existing categories are actionable. New-category candidates belong to
  // the creation assistant, not to a review queue.
  if (category.resolution !== 'EXISTING') return [];

  const suggestedId = category.categoryId ?? null;
  if (!suggestedId) return [];
  const suggested = categoryById.get(suggestedId);
  if (!suggested) return [];

  const categoryPath =
    category.categoryPath && category.categoryPath.length > 0
      ? category.categoryPath.join(' › ')
      : suggested.name;

  const suggestedValue: Record<string, unknown> = {
    categoryId: suggested.id,
    categoryName: suggested.name,
    categoryCode: suggested.code,
    categoryPath,
    resolution: category.resolution,
  };

  if (!component.categoryId) {
    return [
      {
        componentId: component.id,
        issueType: 'CATEGORY_UNRESOLVED',
        issueCategory: 'CLASSIFICATION',
        field: 'category',
        title: 'Category not assigned',
        description: `No category is recorded for this component. Analysis resolved "${categoryPath}".`,
        currentValue: { categoryId: null, categoryName: null },
        suggestedValue,
        confidence: category.confidence,
        confidenceLevel: category.confidenceLevel ?? 'HIGH',
        evidence: toEvidence(category.evidence),
        source: 'analyzer:category',
        intelligenceVersion,
        componentUpdatedAt: component.updatedAt,
        metadata: { rule: 'CATEGORY_UNRESOLVED' },
      },
    ];
  }

  const stored = categoryById.get(component.categoryId);
  if (!stored) return [];
  if (areCategoriesRelated(stored.id, suggested.id, categoryById)) return [];

  return [
    {
      componentId: component.id,
      issueType: 'CATEGORY_CONFLICT',
      issueCategory: 'CLASSIFICATION',
      field: 'category',
      title: 'Category may be incorrect',
      description: `Recorded category is "${stored.name}", but analysis resolved "${categoryPath}".`,
      currentValue: {
        categoryId: stored.id,
        categoryName: stored.name,
        categoryCode: stored.code,
      },
      suggestedValue,
      confidence: category.confidence,
      confidenceLevel: category.confidenceLevel ?? 'HIGH',
      evidence: toEvidence(category.evidence),
      source: 'analyzer:category',
      intelligenceVersion,
      componentUpdatedAt: component.updatedAt,
      metadata: { rule: 'CATEGORY_CONFLICT' },
    },
  ];
}

/**
 * Detects duplicate parts by comparing normalized manufacturer part numbers.
 *
 * This is deliberately deterministic and database-backed. It replaces the
 * creation-time ML duplicate detector for *persisted records*, which only
 * inspected a bounded 100-component window of free text and never compared
 * `components.manufacturer_part_number` values against each other.
 *
 * Search scope (authoritative fields, NOT a candidate window):
 *  - Exact duplicates are found by grouping the ENTIRE authoritative catalog of
 *    persisted, non-null `manufacturer_part_number` values. No row limit is
 *    applied, so a duplicate cannot be missed because of an arbitrary window.
 *  - `POTENTIAL_DUPLICATE` here means "same part number modulo a packaging/reel
 *    suffix" and is computed from the same complete grouping, so it is equally
 *    complete.
 *  - Expensive semantic similarity (embedding/lexical scoring over all pairs) is
 *    NOT implemented in this pass. When it is added it must stay bounded by
 *    candidate retrieval; nothing in this function currently depends on a
 *    bounded window.
 *
 * The only bound on this path is the per-audit write cap
 * ({@link MAX_DUPLICATE_FINDINGS_PER_AUDIT}) applied by the caller, which
 * truncates output deterministically and reports truncation rather than
 * silently dropping detections.
 *
 * Two tiers:
 *  - `EXACT_DUPLICATE`: identical after normalization.
 *  - `POTENTIAL_DUPLICATE`: identical after removing a packaging/reel suffix.
 *
 * Findings use a star topology: the oldest record of a group is treated as the
 * canonical record and every other member gets a single finding referencing it,
 * so a group of N produces N-1 reviewable items instead of N²/2 pairs.
 */
export function detectDuplicateFindings(
  input: DetectDuplicateFindingsInput,
): PersistComponentFindingInput[] {
  const { catalog, scopeComponentIds, includeInactive, intelligenceVersion } =
    input;

  const groups = new Map<string, CatalogMpnEntry[]>();
  for (const entry of catalog) {
    const normalized = normalizeMpn(entry.manufacturerPartNumber);
    if (
      !normalized ||
      normalized.length < MIN_MPN_LENGTH ||
      isPlaceholderMpn(normalized)
    ) {
      continue;
    }
    const base = stripPackagingSuffix(normalized);
    if (base.length < MIN_MPN_LENGTH) continue;
    const bucket = groups.get(base);
    if (bucket) {
      bucket.push(entry);
    } else {
      groups.set(base, [entry]);
    }
  }

  const findings: PersistComponentFindingInput[] = [];

  const duplicateCandidates: Array<{
    base: string;
    finding: PersistComponentFindingInput;
  }> = [];

  for (const [base, members] of groups) {
    if (members.length < 2) continue;

    const sorted = [...members].sort(compareCatalogOrder);
    const canonical = sorted[0];
    if (!canonical) continue;

    for (const member of sorted.slice(1)) {
      if (!includeInactive && !member.isActive) continue;

      // Report the pair when either side was requested for analysis, so
      // analyzing one half of a duplicate still surfaces it.
      const inScope =
        scopeComponentIds.has(member.id) || scopeComponentIds.has(canonical.id);
      if (!inScope) continue;

      const memberNormalized = normalizeMpn(member.manufacturerPartNumber);
      const canonicalNormalized = normalizeMpn(
        canonical.manufacturerPartNumber,
      );
      if (!memberNormalized || !canonicalNormalized) continue;

      const exact = memberNormalized === canonicalNormalized;

      duplicateCandidates.push({
        base,
        finding: buildDuplicateFinding({
          member,
          canonical,
          base,
          exact,
          intelligenceVersion,
        }),
      });
    }
  }

  // Deterministic order keeps capped audits stable across runs.
  duplicateCandidates.sort(
    (left, right) =>
      left.base.localeCompare(right.base) ||
      left.finding.componentId.localeCompare(right.finding.componentId),
  );

  findings.push(...duplicateCandidates.map((candidate) => candidate.finding));

  return findings;
}

function buildDuplicateFinding(input: {
  member: CatalogMpnEntry;
  canonical: CatalogMpnEntry;
  base: string;
  exact: boolean;
  intelligenceVersion: string;
}): PersistComponentFindingInput {
  const { member, canonical, base, exact, intelligenceVersion } = input;

  const evidence: Array<Record<string, unknown>> = [
    {
      type: 'mpn_pattern',
      description: exact
        ? `Normalized part number "${base}" is identical to component ${canonical.sku} ("${canonical.manufacturerPartNumber}")`
        : `Normalized part number "${base}" matches component ${canonical.sku} ("${canonical.manufacturerPartNumber}") after removing the packaging suffix`,
      weight: exact ? 1 : 0.9,
      source: 'database:components.manufacturer_part_number',
    },
  ];

  if (
    member.manufacturerId &&
    canonical.manufacturerId &&
    member.manufacturerId !== canonical.manufacturerId
  ) {
    evidence.push({
      type: 'anomaly',
      description:
        'The two records reference different manufacturers; verify which record is authoritative',
      weight: 0.8,
      source: 'analyzer:duplicate_conflict',
    });
  }
  if (
    member.categoryId &&
    canonical.categoryId &&
    member.categoryId !== canonical.categoryId
  ) {
    evidence.push({
      type: 'anomaly',
      description:
        'The two records are classified under different categories; verify the correct classification',
      weight: 0.75,
      source: 'analyzer:duplicate_conflict',
    });
  }

  const matchType = exact ? 'EXACT_MPN' : 'PACKAGING_VARIANT';
  const issueType = exact ? 'EXACT_DUPLICATE' : 'POTENTIAL_DUPLICATE';

  return {
    componentId: member.id,
    relatedComponentId: canonical.id,
    issueType,
    issueCategory: 'DUPLICATE',
    field: 'duplicate',
    title: exact
      ? `Duplicate manufacturer part number "${member.manufacturerPartNumber}"`
      : `Manufacturer part number variant of "${canonical.manufacturerPartNumber}"`,
    description: exact
      ? `Manufacturer part number is identical to component ${canonical.sku} ("${canonical.name}") after normalization.`
      : `Manufacturer part number "${member.manufacturerPartNumber}" matches component ${canonical.sku} ("${canonical.manufacturerPartNumber}") once the packaging suffix is removed.`,
    currentValue: {
      sku: member.sku,
      manufacturerPartNumber: member.manufacturerPartNumber,
      manufacturerId: member.manufacturerId,
      categoryId: member.categoryId,
    },
    suggestedValue: {
      duplicateOfComponentId: canonical.id,
      duplicateOfSku: canonical.sku,
      duplicateOfManufacturerPartNumber: canonical.manufacturerPartNumber,
      matchType,
      normalizedMpn: base,
    },
    confidence: exact ? 1 : 0.9,
    confidenceLevel: 'HIGH',
    evidence,
    source: 'analyzer:duplicate',
    intelligenceVersion,
    componentUpdatedAt: member.updatedAt,
    metadata: {
      rule: issueType,
      matchType,
      canonicalComponentId: canonical.id,
    },
  };
}

@Injectable()
export class ComponentReviewAnalyzer {
  private readonly logger = new Logger(ComponentReviewAnalyzer.name);

  constructor(
    private readonly mlService: MlService,
    private readonly reviewQueue: ComponentReviewQueueService,
    @Optional() private readonly dataPacksService?: DataPacksService,
  ) {}

  /**
   * Runs component analysis over the requested scope, persists findings, and
   * reconciles findings that are no longer detected.
   *
   * Bounded by `limit` because each analyzed component performs a full
   * intelligence lookup; full-catalog sweeps are executed as repeated bounded
   * audits rather than one unbounded request.
   */
  async runAudit(
    input: RunComponentAuditInput = {},
  ): Promise<ComponentAuditResult> {
    const startedAt = Date.now();
    const scope = input.scope ?? 'SELECTED';
    const limit = Math.min(
      Math.max(1, input.limit ?? DEFAULT_COMPONENT_AUDIT_LIMIT),
      MAX_COMPONENT_AUDIT_LIMIT,
    );
    const includeInactive = input.includeInactive ?? false;

    if (scope === 'SELECTED' && (input.componentIds ?? []).length === 0) {
      throw new BadRequestException(
        'Provide at least one component id, or use the ALL / RECENTLY_UPDATED scope.',
      );
    }

    const requestedIds = Array.from(
      new Set((input.componentIds ?? []).filter((id) => Boolean(id))),
    );
    const targets = await this.loadTargets({
      scope,
      componentIds: input.componentIds,
      sinceDays: input.sinceDays,
      limit,
      includeInactive,
    });

    const [
      { categoryById, manufacturerById },
      { catalog, mpnIndex },
      packagePatterns,
    ] = await Promise.all([
      this.loadReferenceData(),
      this.loadCatalogMpnData(),
      this.loadPackagePatterns(),
    ]);

    const scopeComponentIds = new Set(targets.map((target) => target.id));

    const duplicateCandidates = detectDuplicateFindings({
      catalog,
      scopeComponentIds,
      includeInactive,
      intelligenceVersion: COMPONENT_REVIEW_INTELLIGENCE_VERSION,
    });
    const {
      findings: duplicateFindings,
      truncated: duplicateFindingsTruncated,
    } = capDuplicateFindings(duplicateCandidates);
    if (duplicateFindingsTruncated) {
      this.logger.warn(
        `Duplicate analysis produced ${duplicateCandidates.length} findings; capping this audit at ${MAX_DUPLICATE_FINDINGS_PER_AUDIT}. Re-run the audit to continue.`,
      );
    }

    const findings: PersistComponentFindingInput[] = [...duplicateFindings];
    const duplicateFindingsCount = duplicateFindings.length;

    let failedCount = 0;
    let mlActiveCount = 0;
    const incompleteComponentIds = new Set<string>();

    for (const component of targets) {
      const manufacturerPartNumber =
        component.manufacturerPartNumber?.trim() || undefined;
      const description = [component.name, component.description]
        .filter((part): part is string => Boolean(part && part.trim()))
        .join(' ')
        .trim();

      let suggestion: ComponentSuggestionResponseDto | null = null;
      try {
        suggestion = await this.mlService.suggest({
          query:
            manufacturerPartNumber || component.name.trim() || component.sku,
          partNumber: manufacturerPartNumber,
          description: description || undefined,
        });
        if (suggestion.isMlActive) mlActiveCount += 1;
      } catch (error) {
        // A failed lookup must not silently invalidate previously generated
        // ML-derived findings for this component.
        failedCount += 1;
        incompleteComponentIds.add(component.id);
        this.logger.warn(
          `Component analysis failed for ${component.sku}: ${String(error)}`,
        );
      }

      findings.push(
        ...evaluateComponentFindings({
          component,
          suggestion,
          categoryById,
          manufacturerById,
          mpnIndex,
          packagePatterns,
          intelligenceVersion: COMPONENT_REVIEW_INTELLIGENCE_VERSION,
        }),
      );
    }

    const persisted =
      findings.length > 0
        ? await this.reviewQueue.persistFindings(findings)
        : { persistedCount: 0, findings: [] };

    const activeFingerprints = new Set(
      persisted.findings.map((finding) => finding.fingerprint),
    );
    const reconcilableComponentIds = targets
      .filter((target) => !incompleteComponentIds.has(target.id))
      .map((target) => target.id);

    const { staledCount } =
      reconcilableComponentIds.length > 0
        ? await this.reviewQueue.reconcileFindings({
            componentIds: reconcilableComponentIds,
            activeFingerprints,
            sources: [...COMPONENT_ANALYZER_SOURCES],
          })
        : { staledCount: 0 };

    const findingsByCategory: Record<string, number> = {};
    for (const finding of persisted.findings) {
      findingsByCategory[finding.issueCategory] =
        (findingsByCategory[finding.issueCategory] ?? 0) + 1;
    }

    const queue = await this.reviewQueue.listFindings({
      status: 'PENDING',
      page: 1,
      pageSize: 1,
    });

    const notFoundCount =
      scope === 'SELECTED' && requestedIds.length > 0
        ? await this.countMissingComponents(requestedIds, targets)
        : 0;

    const result: ComponentAuditResult = {
      scope,
      analyzedCount: targets.length,
      notFoundCount,
      failedCount,
      mlActiveCount,
      persistedCount: persisted.persistedCount,
      staledCount,
      duplicateFindingsCount,
      duplicateFindingsTruncated,
      findingsByCategory,
      pendingTotal: queue.summary.pending,
      batchLimitReached: targets.length === limit,
      durationMs: Math.round(Date.now() - startedAt),
      intelligenceVersion: COMPONENT_REVIEW_INTELLIGENCE_VERSION,
      issueTypes: COMPONENT_REVIEW_ISSUE_TYPES,
    };

    this.logger.log(
      `Component audit (${scope}) analyzed ${result.analyzedCount} component(s): ${result.persistedCount} finding(s) persisted, ${result.staledCount} marked stale.`,
    );

    return result;
  }

  /**
   * Counts requested ids that do not exist. Ids that exist but were cut by the
   * batch limit are not reported as missing.
   */
  private async countMissingComponents(
    requestedIds: string[],
    targets: AnalyzableComponent[],
  ): Promise<number> {
    const analyzedIds = new Set(targets.map((target) => target.id));
    const unresolvedIds = requestedIds.filter((id) => !analyzedIds.has(id));
    if (unresolvedIds.length === 0) return 0;

    const existing = await db
      .select({ id: components.id })
      .from(components)
      .where(inArray(components.id, unresolvedIds));

    return unresolvedIds.length - existing.length;
  }

  private async loadTargets(input: {
    scope: ComponentReviewAuditScope;
    componentIds?: string[];
    sinceDays?: number;
    limit: number;
    includeInactive: boolean;
  }): Promise<AnalyzableComponent[]> {
    const selection = componentColumns();

    if (input.scope === 'SELECTED') {
      const ids = Array.from(
        new Set((input.componentIds ?? []).filter((id) => Boolean(id))),
      );
      if (ids.length === 0) return [];
      // Explicitly selected components are analyzed even when inactive.
      return db
        .select(selection)
        .from(components)
        .where(inArray(components.id, ids))
        .orderBy(asc(components.sku))
        .limit(input.limit);
    }

    if (input.scope === 'RECENTLY_UPDATED') {
      const sinceDays = Math.max(
        1,
        input.sinceDays ?? DEFAULT_COMPONENT_AUDIT_RECENT_DAYS,
      );
      const since = new Date(Date.now() - sinceDays * 24 * 60 * 60 * 1000);
      const where = input.includeInactive
        ? gte(components.updatedAt, since)
        : and(gte(components.updatedAt, since), eq(components.isActive, true));
      return db
        .select(selection)
        .from(components)
        .where(where)
        .orderBy(desc(components.updatedAt))
        .limit(input.limit);
    }

    return db
      .select(selection)
      .from(components)
      .where(input.includeInactive ? undefined : eq(components.isActive, true))
      .orderBy(asc(components.sku))
      .limit(input.limit);
  }

  private async loadReferenceData(): Promise<{
    categoryById: Map<string, ComponentCategoryRef>;
    manufacturerById: Map<string, ComponentManufacturerRef>;
  }> {
    const [categoryRows, manufacturerRows] = await Promise.all([
      db
        .select({
          id: categories.id,
          code: categories.code,
          name: categories.name,
          parentId: categories.parentId,
        })
        .from(categories),
      db
        .select({
          id: manufacturers.id,
          code: manufacturers.code,
          name: manufacturers.name,
        })
        .from(manufacturers),
    ]);

    return {
      categoryById: new Map(categoryRows.map((row) => [row.id, row])),
      manufacturerById: new Map(manufacturerRows.map((row) => [row.id, row])),
    };
  }

  private async loadCatalogMpnData(): Promise<{
    catalog: CatalogMpnEntry[];
    mpnIndex: Map<string, CatalogMpnEntry[]>;
  }> {
    // Full-catalog read of authoritative MPN fields only (no unbounded payload
    // columns). Required for exact duplicate detection to be complete; there is
    // no candidate window here by design.
    const rows = await db
      .select({
        id: components.id,
        sku: components.sku,
        name: components.name,
        manufacturerPartNumber: components.manufacturerPartNumber,
        manufacturerId: components.manufacturerId,
        categoryId: components.categoryId,
        isActive: components.isActive,
        createdAt: components.createdAt,
        updatedAt: components.updatedAt,
      })
      .from(components);

    const catalog: CatalogMpnEntry[] = rows.flatMap((row) => {
      const manufacturerPartNumber = row.manufacturerPartNumber?.trim();
      if (!manufacturerPartNumber) return [];
      return [{ ...row, manufacturerPartNumber }];
    });

    return { catalog, mpnIndex: buildMpnIndex(catalog) };
  }

  private async loadPackagePatterns(): Promise<string[]> {
    if (!this.dataPacksService) return [];
    try {
      const hints = await this.dataPacksService.getActiveIntelligenceHints();
      return Array.from(
        new Set(hints.flatMap((hint) => hint.packagePatterns ?? [])),
      );
    } catch {
      return [];
    }
  }
}

function componentColumns() {
  return {
    id: components.id,
    sku: components.sku,
    name: components.name,
    description: components.description,
    manufacturerPartNumber: components.manufacturerPartNumber,
    manufacturerId: components.manufacturerId,
    categoryId: components.categoryId,
    unit: components.unit,
    isActive: components.isActive,
    createdAt: components.createdAt,
    updatedAt: components.updatedAt,
  };
}
