import {
  BadRequestException,
  Injectable,
  Logger,
  Optional,
} from '@nestjs/common';
import { db } from '@ananya/database';
import {
  categories,
  componentIntelligenceFindings,
  components,
  manufacturers,
} from '@ananya/database/schema';
import {
  and,
  asc,
  desc,
  eq,
  gte,
  inArray,
  notInArray,
  or,
  sql,
} from '@ananya/database/query';
import { MlService } from './ml.service';
import {
  ComponentReviewQueueService,
  type PersistComponentFindingInput,
} from './component-review-queue.service';
import {
  DEFAULT_COMPONENT_AUDIT_LIMIT,
  MAX_COMPONENT_AUDIT_LIMIT,
  COMPONENT_REVIEW_ISSUE_TYPES,
  type ComponentReviewAuditScope,
  type ComponentReviewIssueCategory,
  type ConfidenceLevel,
} from './component-review-queue.dtos';
import {
  MAX_DUPLICATE_FINDINGS_PER_AUDIT,
  MAX_NAME_CANDIDATE_ROWS,
  PACKAGING_SUFFIX_PATTERN,
  areCategoriesRelated,
  areEquivalentMpns,
  buildGenericNameTerms,
  buildManufacturerIdentityIndex,
  buildMpnIndex,
  buildSemanticCandidatePairs,
  capDuplicateFindings,
  collectNameIdentityCandidateIds,
  extractCandidateMpnFromText,
  normalizeMpn,
  normalizeName,
  normalizedMpnSql,
  normalizedNameSql,
  runDuplicateDetection,
  stripPackagingSuffix,
  type CatalogMpnEntry,
  type ComponentCategoryRef,
  type ComponentManufacturerRef,
  type ManufacturerHintTerm,
  type SemanticDetectionStats,
  type SqlCondition,
} from './component-duplicate-intelligence';
import {
  MAX_SEMANTIC_BLOCKING_KEYS,
  MAX_SEMANTIC_CANDIDATE_ROWS,
  semanticBlockingTokens,
  type SemanticTokenVocabulary,
} from './component-semantic-similarity';
import { loadIdentityAttributeValues } from './component-attribute-values.loader';
import {
  ATTRIBUTE_SUGGESTION_SOURCE,
  buildAttributeSuggestionFindings,
  MAX_ATTRIBUTE_FINDINGS_PER_COMPONENT,
} from './component-attribute-suggestion-findings';
import { DataPacksService } from '../data-packs/data-packs.service';
import type { ComponentSuggestionResponseDto, EvidenceItemDto } from './dtos';

/**
 * The deterministic duplicate/normalization contract lives in
 * `component-duplicate-intelligence.ts` (Pass 5A). It is re-exported here so
 * every existing consumer - the apply service, the review specs - keeps its
 * current import path.
 */
export * from './component-duplicate-intelligence';

/**
 * Component Intelligence Review Analyzer (Pass 2).
 *
 * Analyzes PERSISTED components and produces evidence-backed review findings
 * for `ComponentReviewQueueService.persistFindings()`.
 *
 * Core principle: the queue is not a firehose for every ML output. A finding is
 * only generated when there is a *meaningful discrepancy* a human should judge:
 *
 *  - the stored value is missing and analysis can supply one, or
 *  - the stored value disagrees with a high-confidence, evidence-backed
 *    conclusion, or
 *  - two persisted records appear to describe the same part.
 *
 * Rules intentionally NOT implemented here:
 *  - "no suggestion available" cases (nothing to review),
 *  - new-category candidates (creating taxonomies from a review queue is out of
 *    scope; category-attribute intelligence owns taxonomy curation),
 *  - attribute-level data quality (missing/conflicting component attribute
 *    values) which belongs to the following pass.
 *
 * Safety: the analyzer NEVER mutates component data. It only persists findings.
 */

/** Bumped when rule semantics change so fingerprints are re-evaluated. */
export const COMPONENT_REVIEW_INTELLIGENCE_VERSION = 'component-review-v3';

/** Minimum confidence for ML-derived (manufacturer/category) findings. */
export const REVIEW_MIN_CONFIDENCE = 0.85;

/** Producer tags recorded on findings generated by this analyzer. */
export const COMPONENT_ANALYZER_SOURCES: readonly string[] = [
  'analyzer:identity',
  'analyzer:manufacturer',
  'analyzer:category',
  'analyzer:duplicate',
  ATTRIBUTE_SUGGESTION_SOURCE,
];

export const DEFAULT_COMPONENT_AUDIT_RECENT_DAYS = 30;

/**
 * Lookback used when the audit requests the `RECENTLY_UPDATED` scope.
 */
export interface AnalyzableComponent {
  id: string;
  sku: string;
  name: string;
  description: string | null;
  manufacturerPartNumber: string | null;
  manufacturerId: string | null;
  categoryId: string | null;
  unit: string;
  isActive: boolean;
  createdAt: Date;
  updatedAt: Date;
}

export interface EvaluateComponentFindingsInput {
  component: AnalyzableComponent;
  suggestion: ComponentSuggestionResponseDto | null;
  categoryById: Map<string, ComponentCategoryRef>;
  manufacturerById: Map<string, ComponentManufacturerRef>;
  mpnIndex: Map<string, CatalogMpnEntry[]>;
  packagePatterns: string[];
  intelligenceVersion: string;
}

/**
 * Lookback window used by the `RECENTLY_UPDATED` audit scope.
 */
export interface RunComponentAuditInput {
  scope?: ComponentReviewAuditScope;
  componentIds?: string[];
  sinceDays?: number;
  limit?: number;
  includeInactive?: boolean;
}

/** Blocking instrumentation for the Pass 5B semantic retrieval step. */
export interface SemanticBlockingAuditStats {
  blockingTokensUsed: number;
  nonSelectiveTokens: string[];
  rowsRetrieved: number;
  rowsTruncated: boolean;
  cappedComponents: number;
  pairs: number;
}

export interface ComponentAuditResult {
  scope: ComponentReviewAuditScope;
  analyzedCount: number;
  /** Requested component ids that do not exist (SELECTED scope only). */
  notFoundCount: number;
  /** Components whose analysis failed; they are excluded from reconciliation. */
  failedCount: number;
  mlActiveCount: number;
  persistedCount: number;
  staledCount: number;
  duplicateFindingsCount: number;
  /** True when duplicate findings hit `MAX_DUPLICATE_FINDINGS_PER_AUDIT`. */
  duplicateFindingsTruncated: boolean;
  /** Pass 5B semantic layer instrumentation (never used for scoring). */
  semanticFindingsCount: number;
  semanticCandidatesConsidered: number;
  semanticCandidatesRejected: number;
  semanticCandidatesAccepted: number;
  semanticCandidatesTruncated: boolean;
  semanticRejectionReasons: Record<string, number>;
  semanticBlocking: {
    tokensUsed: number;
    nonSelectiveTokens: string[];
    rowsRetrieved: number;
    rowsTruncated: boolean;
    cappedComponents: number;
    pairs: number;
  };
  findingsByCategory: Record<string, number>;
  /** Attribute-value findings this producer created (values + relevance-only). */
  attributeFindingsCount: number;
  /** True when a component's attribute findings hit the per-component cap. */
  attributeFindingsTruncated: boolean;
  pendingTotal: number;
  /**
   * True when the batch reached its limit: additional components may not have
   * been analyzed. Re-running the audit is idempotent.
   */
  batchLimitReached: boolean;
  durationMs: number;
  intelligenceVersion: string;
  /** Canonical issue-type taxonomy exposed so clients never hardcode it. */
  issueTypes: Record<ComponentReviewIssueCategory, readonly string[]>;
}

function isHighConfidence(
  level: ConfidenceLevel | undefined | null,
  confidence: number | undefined | null,
): boolean {
  return (
    level === 'HIGH' &&
    typeof confidence === 'number' &&
    confidence >= REVIEW_MIN_CONFIDENCE
  );
}

function toEvidence(
  items: EvidenceItemDto[] | undefined | null,
  limit = 5,
): Array<Record<string, unknown>> {
  return (items ?? []).slice(0, limit).map((item) => ({
    type: item.type,
    description: item.description,
    weight: item.weight,
    ...(item.source ? { source: item.source } : {}),
  }));
}

function truncate(value: string, maxLength: number): string {
  return value.length <= maxLength
    ? value
    : `${value.slice(0, maxLength - 1)}…`;
}

/**
 * Evaluates identity and classification rules for a single persisted
 * component. Pure and deterministic so rules can be unit tested without a
 * database or the ML service.
 */
export function evaluateComponentFindings(
  input: EvaluateComponentFindingsInput,
): PersistComponentFindingInput[] {
  return [
    ...buildMpnFindings(input),
    ...buildManufacturerFindings(input),
    ...buildCategoryFindings(input),
  ];
}

interface ExtractedMpnContext {
  extracted: string;
  normalized: string;
  sourceText: string;
  existingOwners: CatalogMpnEntry[];
}

/**
 * Locates an independent manufacturer part number in the component's own name
 * and description text.
 *
 * The persisted MPN column is deliberately excluded: comparing a column with
 * itself cannot produce evidence. Text extraction also ignores the internal SKU
 * and footprint codes so neither is mistaken for a manufacturer identifier.
 */
function resolveExtractedMpn(
  input: EvaluateComponentFindingsInput,
): ExtractedMpnContext | null {
  const { component, mpnIndex } = input;
  const identity = extractComponentMpnIdentity(
    component,
    input.manufacturerById,
    input.packagePatterns,
  );
  if (!identity) return null;

  return {
    ...identity,
    existingOwners: (mpnIndex.get(identity.normalized) ?? []).filter(
      (entry) => entry.id !== component.id,
    ),
  };
}

/**
 * Independent MPN identity found in a component's own name/description text.
 * Pure, so the audit can collect the MPNs a batch needs before querying for
 * their owners (instead of reading the whole catalog).
 */
export interface ComponentMpnIdentity {
  extracted: string;
  normalized: string;
  sourceText: string;
}

export function extractComponentMpnIdentity(
  component: {
    sku: string;
    name: string;
    description: string | null;
  },
  manufacturerById: Map<string, ComponentManufacturerRef>,
  packagePatterns: readonly string[],
): ComponentMpnIdentity | null {
  const sourceText = [component.name, component.description]
    .filter((part): part is string => Boolean(part && part.trim()))
    .join(' ')
    .trim();
  if (!sourceText) return null;

  const manufacturerTerms = Array.from(manufacturerById.values()).map(
    (manufacturer) => ({ name: manufacturer.name, code: manufacturer.code }),
  );
  const extracted = extractCandidateMpnFromText(
    sourceText,
    manufacturerTerms,
    packagePatterns,
  );
  if (!extracted) return null;

  const normalized = normalizeMpn(extracted);
  if (!normalized) return null;

  // An internal SKU repeated as an MPN carries no manufacturer identity.
  if (normalized === normalizeMpn(component.sku)) return null;

  return { extracted, normalized, sourceText };
}

/**
 * MPN identity rules.
 *
 * - `MPN_MISSING`: no MPN persisted, but one is identifiable from the text.
 * - `MPN_CONFLICT`: an MPN is persisted and the text identifies a *different*
 *   part number. Formatting and packaging variants are treated as equivalent
 *   and never flagged, because they describe the same engineering part.
 */
function buildMpnFindings(
  input: EvaluateComponentFindingsInput,
): PersistComponentFindingInput[] {
  const { component, intelligenceVersion } = input;
  const persisted = component.manufacturerPartNumber?.trim() || null;
  const resolved = resolveExtractedMpn(input);
  if (!resolved) return [];

  const { extracted, normalized, sourceText, existingOwners } = resolved;

  const evidence: Array<Record<string, unknown>> = [
    {
      type: 'mpn_pattern',
      description: `Manufacturer part number "${extracted}" identified in the component name or description`,
      weight: 0.9,
      source: 'analyzer:mpn_extraction',
    },
  ];
  if (existingOwners.length > 0) {
    const [firstOwner] = existingOwners;
    evidence.push({
      type: 'existing_data',
      description:
        existingOwners.length === 1
          ? `Extracted part number already belongs to component ${firstOwner?.sku}`
          : `Extracted part number already belongs to ${existingOwners.length} other components (e.g. ${firstOwner?.sku})`,
      weight: 0.75,
      source: 'database:components.manufacturer_part_number',
    });
  }

  const collidesWithExistingComponent = existingOwners.length > 0;
  const analyzedText = truncate(sourceText, 300);

  if (!persisted) {
    return [
      {
        componentId: component.id,
        issueType: 'MPN_MISSING',
        issueCategory: 'IDENTITY',
        field: 'manufacturerPartNumber',
        title: 'Manufacturer part number missing',
        description: `No manufacturer part number is recorded, but "${extracted}" was identified in the component name or description.`,
        currentValue: { manufacturerPartNumber: null },
        suggestedValue: {
          manufacturerPartNumber: extracted,
          normalizedMpn: normalized,
          collidesWithExistingComponent,
        },
        confidence: 0.9,
        confidenceLevel: 'HIGH',
        evidence,
        source: 'analyzer:identity',
        intelligenceVersion,
        componentUpdatedAt: component.updatedAt,
        metadata: { rule: 'MPN_MISSING', analyzedText },
      },
    ];
  }

  const persistedNormalized = normalizeMpn(persisted);
  if (!persistedNormalized) return [];

  if (areEquivalentMpns(persistedNormalized, normalized)) return [];

  return [
    {
      componentId: component.id,
      issueType: 'MPN_CONFLICT',
      issueCategory: 'IDENTITY',
      field: 'manufacturerPartNumber',
      title: 'Manufacturer part number may be incorrect',
      description: `Recorded manufacturer part number is "${persisted}", but "${extracted}" was identified in the component name or description.`,
      currentValue: { manufacturerPartNumber: persisted },
      suggestedValue: {
        manufacturerPartNumber: extracted,
        normalizedMpn: normalized,
        collidesWithExistingComponent,
      },
      confidence: 0.9,
      confidenceLevel: 'HIGH',
      evidence: [
        ...evidence,
        {
          type: 'anomaly',
          description: `Recorded value "${persisted}" and identified value "${extracted}" differ after normalization`,
          weight: 0.9,
          source: 'analyzer:mpn_conflict',
        },
      ],
      source: 'analyzer:identity',
      intelligenceVersion,
      componentUpdatedAt: component.updatedAt,
      metadata: {
        rule: 'MPN_CONFLICT',
        analyzedText,
        persistedNormalizedMpn: persistedNormalized,
      },
    },
  ];
}

function buildManufacturerFindings(
  input: EvaluateComponentFindingsInput,
): PersistComponentFindingInput[] {
  const { component, suggestion, manufacturerById, intelligenceVersion } =
    input;
  const manufacturer = suggestion?.manufacturer;
  if (!manufacturer) return [];
  if (manufacturer.resolution === 'UNKNOWN') return [];
  if (
    !isHighConfidence(manufacturer.confidenceLevel, manufacturer.confidence)
  ) {
    return [];
  }

  const suggestedName = manufacturer.manufacturerName?.trim();
  if (!suggestedName) return [];

  const suggestedValue: Record<string, unknown> = {
    manufacturerId: manufacturer.manufacturerId ?? null,
    manufacturerName: suggestedName,
    manufacturerCode: manufacturer.manufacturerCode ?? null,
    resolution: manufacturer.resolution,
    matchType: manufacturer.matchType,
  };

  if (!component.manufacturerId) {
    return [
      {
        componentId: component.id,
        issueType: 'MANUFACTURER_UNRESOLVED',
        issueCategory: 'IDENTITY',
        field: 'manufacturer',
        title: 'Manufacturer not assigned',
        description: `No manufacturer is recorded for this component. Analysis resolved "${suggestedName}" (${manufacturer.matchType}).`,
        currentValue: { manufacturerId: null, manufacturerName: null },
        suggestedValue,
        confidence: manufacturer.confidence,
        confidenceLevel: manufacturer.confidenceLevel ?? 'HIGH',
        evidence: toEvidence(manufacturer.evidence),
        source: 'analyzer:manufacturer',
        intelligenceVersion,
        componentUpdatedAt: component.updatedAt,
        metadata: { rule: 'MANUFACTURER_UNRESOLVED' },
      },
    ];
  }

  const stored = manufacturerById.get(component.manufacturerId);
  // Dangling reference: repairing master data references is not this rule's job.
  if (!stored) return [];

  if (manufacturer.manufacturerId === stored.id) return [];

  const matchesStoredName =
    normalizeName(suggestedName) === normalizeName(stored.name) ||
    normalizeName(suggestedName) === normalizeName(stored.code) ||
    normalizeName(manufacturer.manufacturerCode) ===
      normalizeName(stored.name) ||
    normalizeName(manufacturer.manufacturerCode) === normalizeName(stored.code);
  if (matchesStoredName) return [];

  return [
    {
      componentId: component.id,
      issueType: 'MANUFACTURER_CONFLICT',
      issueCategory: 'IDENTITY',
      field: 'manufacturer',
      title: 'Manufacturer may be incorrect',
      description: `Recorded manufacturer is "${stored.name}", but analysis resolved "${suggestedName}" (${manufacturer.matchType}).`,
      currentValue: {
        manufacturerId: stored.id,
        manufacturerName: stored.name,
        manufacturerCode: stored.code,
      },
      suggestedValue,
      confidence: manufacturer.confidence,
      confidenceLevel: manufacturer.confidenceLevel ?? 'HIGH',
      evidence: toEvidence(manufacturer.evidence),
      source: 'analyzer:manufacturer',
      intelligenceVersion,
      componentUpdatedAt: component.updatedAt,
      metadata: { rule: 'MANUFACTURER_CONFLICT' },
    },
  ];
}

function buildCategoryFindings(
  input: EvaluateComponentFindingsInput,
): PersistComponentFindingInput[] {
  const { component, suggestion, categoryById, intelligenceVersion } = input;
  const category = suggestion?.category;
  if (!category) return [];
  if (!isHighConfidence(category.confidenceLevel, category.confidence)) {
    return [];
  }
  // Only existing categories are actionable. New-category candidates belong to
  // the creation assistant, not to a review queue.
  if (category.resolution !== 'EXISTING') return [];

  const suggestedId = category.categoryId ?? null;
  if (!suggestedId) return [];
  const suggested = categoryById.get(suggestedId);
  if (!suggested) return [];

  const categoryPath =
    category.categoryPath && category.categoryPath.length > 0
      ? category.categoryPath.join(' › ')
      : suggested.name;

  const suggestedValue: Record<string, unknown> = {
    categoryId: suggested.id,
    categoryName: suggested.name,
    categoryCode: suggested.code,
    categoryPath,
    resolution: category.resolution,
  };

  if (!component.categoryId) {
    return [
      {
        componentId: component.id,
        issueType: 'CATEGORY_UNRESOLVED',
        issueCategory: 'CLASSIFICATION',
        field: 'category',
        title: 'Category not assigned',
        description: `No category is recorded for this component. Analysis resolved "${categoryPath}".`,
        currentValue: { categoryId: null, categoryName: null },
        suggestedValue,
        confidence: category.confidence,
        confidenceLevel: category.confidenceLevel ?? 'HIGH',
        evidence: toEvidence(category.evidence),
        source: 'analyzer:category',
        intelligenceVersion,
        componentUpdatedAt: component.updatedAt,
        metadata: { rule: 'CATEGORY_UNRESOLVED' },
      },
    ];
  }

  const stored = categoryById.get(component.categoryId);
  if (!stored) return [];
  if (areCategoriesRelated(stored.id, suggested.id, categoryById)) return [];

  return [
    {
      componentId: component.id,
      issueType: 'CATEGORY_CONFLICT',
      issueCategory: 'CLASSIFICATION',
      field: 'category',
      title: 'Category may be incorrect',
      description: `Recorded category is "${stored.name}", but analysis resolved "${categoryPath}".`,
      currentValue: {
        categoryId: stored.id,
        categoryName: stored.name,
        categoryCode: stored.code,
      },
      suggestedValue,
      confidence: category.confidence,
      confidenceLevel: category.confidenceLevel ?? 'HIGH',
      evidence: toEvidence(category.evidence),
      source: 'analyzer:category',
      intelligenceVersion,
      componentUpdatedAt: component.updatedAt,
      metadata: { rule: 'CATEGORY_CONFLICT' },
    },
  ];
}

@Injectable()
export class ComponentReviewAnalyzer {
  private readonly logger = new Logger(ComponentReviewAnalyzer.name);

  constructor(
    private readonly mlService: MlService,
    private readonly reviewQueue: ComponentReviewQueueService,
    @Optional() private readonly dataPacksService?: DataPacksService,
  ) {}

  /**
   * Runs component analysis over the requested scope, persists findings, and
   * reconciles findings that are no longer detected.
   *
   * Bounded by `limit` because each analyzed component performs a full
   * intelligence lookup; full-catalog sweeps are executed as repeated bounded
   * audits rather than one unbounded request.
   */
  async runAudit(
    input: RunComponentAuditInput = {},
  ): Promise<ComponentAuditResult> {
    const startedAt = Date.now();
    const scope = input.scope ?? 'SELECTED';
    const limit = Math.min(
      Math.max(1, input.limit ?? DEFAULT_COMPONENT_AUDIT_LIMIT),
      MAX_COMPONENT_AUDIT_LIMIT,
    );
    const includeInactive = input.includeInactive ?? false;

    if (scope === 'SELECTED' && (input.componentIds ?? []).length === 0) {
      throw new BadRequestException(
        'Provide at least one component id, or use the ALL / RECENTLY_UPDATED scope.',
      );
    }

    const requestedIds = Array.from(
      new Set((input.componentIds ?? []).filter((id) => Boolean(id))),
    );
    const targets = await this.loadTargets({
      scope,
      componentIds: input.componentIds,
      sinceDays: input.sinceDays,
      limit,
      includeInactive,
    });

    const [{ categoryById, manufacturerById }, intelligence] =
      await Promise.all([
        this.loadReferenceData(),
        this.loadIntelligenceHints(),
      ]);
    const { packagePatterns, manufacturerHints } = intelligence;

    const mpnIndex = await this.loadMpnOwnerIndex({
      targets,
      manufacturerById,
      packagePatterns,
    });

    const scopeComponentIds = new Set(targets.map((target) => target.id));

    const {
      findings: duplicateCandidates,
      semantic: semanticStats,
      blocking: blockingStats,
    } = await this.detectDuplicateCandidates({
      targets,
      scopeComponentIds,
      includeInactive,
      categoryById,
      manufacturerById,
      manufacturerHints,
      packagePatterns,
    });
    const {
      findings: duplicateFindings,
      truncated: duplicateFindingsTruncated,
    } = capDuplicateFindings(duplicateCandidates);
    if (duplicateFindingsTruncated) {
      this.logger.warn(
        `Duplicate analysis produced ${duplicateCandidates.length} findings; capping this audit at ${MAX_DUPLICATE_FINDINGS_PER_AUDIT}. Re-run the audit to continue.`,
      );
    }
    if (semanticStats.truncated) {
      this.logger.warn(
        `Semantic duplicate analysis produced ${semanticStats.findingsProduced} findings; ${semanticStats.findingsTruncated} were dropped by the per-audit cap. Re-run the audit to continue.`,
      );
    }

    const findings: PersistComponentFindingInput[] = [...duplicateFindings];
    const duplicateFindingsCount = duplicateFindings.length;

    /**
     * Attributes another producer has already spoken about, per component.
     *
     * Documentation Intelligence quotes the datasheet page a value came from, so
     * its finding is the better-evidenced one for that attribute. Read once for
     * the batch and consulted per component, so the attribute producer fills the
     * gaps rather than competing with it.
     */
    const coveredAttributeIds =
      await this.loadCoveredAttributeFindings(scopeComponentIds);

    let failedCount = 0;
    let mlActiveCount = 0;
    let attributeFindingsCount = 0;
    let attributeFindingsTruncated = false;
    const incompleteComponentIds = new Set<string>();

    for (const component of targets) {
      const manufacturerPartNumber =
        component.manufacturerPartNumber?.trim() || undefined;
      const description = [component.name, component.description]
        .filter((part): part is string => Boolean(part && part.trim()))
        .join(' ')
        .trim();

      let suggestion: ComponentSuggestionResponseDto | null = null;
      try {
        suggestion = await this.mlService.suggest({
          query:
            manufacturerPartNumber || component.name.trim() || component.sku,
          partNumber: manufacturerPartNumber,
          description: description || undefined,
          // The component's own identity, so it is never offered as a duplicate
          // of itself, and its stored category, so attribute relevance is
          // conditioned on what the record actually is.
          componentId: component.id,
          categoryId: component.categoryId ?? undefined,
        });
        if (suggestion.isMlActive) mlActiveCount += 1;
      } catch (error) {
        // A failed lookup must not silently invalidate previously generated
        // ML-derived findings for this component.
        failedCount += 1;
        incompleteComponentIds.add(component.id);
        this.logger.warn(
          `Component analysis failed for ${component.sku}: ${String(error)}`,
        );
      }

      findings.push(
        ...evaluateComponentFindings({
          component,
          suggestion,
          categoryById,
          manufacturerById,
          mpnIndex,
          packagePatterns,
          intelligenceVersion: COMPONENT_REVIEW_INTELLIGENCE_VERSION,
        }),
      );

      // Attribute suggestions are only evaluated from a completed analysis: a
      // failed lookup would otherwise look like "no suggestions" and stale the
      // findings a previous run correctly produced.
      if (suggestion) {
        const built = buildAttributeSuggestionFindings({
          component: {
            id: component.id,
            sku: component.sku,
            name: component.name,
            updatedAt: component.updatedAt,
          },
          suggestions: suggestion.attributeSuggestions ?? [],
          coveredDefinitionIds:
            coveredAttributeIds.get(component.id) ?? new Set<string>(),
          intelligenceVersion: COMPONENT_REVIEW_INTELLIGENCE_VERSION,
        });
        findings.push(...built.findings);
        attributeFindingsCount += built.findings.length;
        attributeFindingsTruncated =
          attributeFindingsTruncated || built.truncated;
      }
    }

    if (attributeFindingsTruncated) {
      this.logger.warn(
        `Attribute suggestions exceeded ${MAX_ATTRIBUTE_FINDINGS_PER_COMPONENT} findings for at least one component; the least actionable were dropped. Re-running the audit is idempotent.`,
      );
    }

    const persisted =
      findings.length > 0
        ? await this.reviewQueue.persistFindings(findings)
        : { persistedCount: 0, findings: [] };

    const activeFingerprints = new Set(
      persisted.findings.map((finding) => finding.fingerprint),
    );
    const reconcilableComponentIds = targets
      .filter((target) => !incompleteComponentIds.has(target.id))
      .map((target) => target.id);

    const { staledCount } =
      reconcilableComponentIds.length > 0
        ? await this.reviewQueue.reconcileFindings({
            componentIds: reconcilableComponentIds,
            activeFingerprints,
            sources: [...COMPONENT_ANALYZER_SOURCES],
          })
        : { staledCount: 0 };

    const findingsByCategory: Record<string, number> = {};
    for (const finding of persisted.findings) {
      findingsByCategory[finding.issueCategory] =
        (findingsByCategory[finding.issueCategory] ?? 0) + 1;
    }

    const queue = await this.reviewQueue.listFindings({
      status: 'PENDING',
      page: 1,
      pageSize: 1,
    });

    const notFoundCount =
      scope === 'SELECTED' && requestedIds.length > 0
        ? await this.countMissingComponents(requestedIds, targets)
        : 0;

    const result: ComponentAuditResult = {
      scope,
      analyzedCount: targets.length,
      notFoundCount,
      failedCount,
      mlActiveCount,
      persistedCount: persisted.persistedCount,
      staledCount,
      duplicateFindingsCount,
      duplicateFindingsTruncated,
      semanticFindingsCount: semanticStats.findingsProduced,
      semanticCandidatesConsidered: semanticStats.candidatesConsidered,
      semanticCandidatesRejected: semanticStats.candidatesRejected,
      semanticCandidatesAccepted: semanticStats.candidatesAccepted,
      semanticCandidatesTruncated: semanticStats.truncated,
      semanticRejectionReasons: Object.fromEntries(
        Object.entries(semanticStats.rejectionReasons).filter(
          (entry): entry is [string, number] => typeof entry[1] === 'number',
        ),
      ),
      semanticBlocking: {
        tokensUsed: blockingStats.blockingTokensUsed,
        nonSelectiveTokens: blockingStats.nonSelectiveTokens,
        rowsRetrieved: blockingStats.rowsRetrieved,
        rowsTruncated: blockingStats.rowsTruncated,
        cappedComponents: blockingStats.cappedComponents,
        pairs: blockingStats.pairs,
      },
      findingsByCategory,
      attributeFindingsCount,
      attributeFindingsTruncated,
      pendingTotal: queue.summary.pending,
      batchLimitReached: targets.length === limit,
      durationMs: Math.round(Date.now() - startedAt),
      intelligenceVersion: COMPONENT_REVIEW_INTELLIGENCE_VERSION,
      issueTypes: COMPONENT_REVIEW_ISSUE_TYPES,
    };

    this.logger.log(
      `Component audit (${scope}) analyzed ${result.analyzedCount} component(s): ${result.persistedCount} finding(s) persisted, ${result.staledCount} marked stale.`,
    );

    return result;
  }

  /**
   * The attributes each component already has a PENDING attribute finding for
   * from ANOTHER producer.
   *
   * One query for the whole batch. Only PENDING rows count: a rejected or
   * dismissed finding means a reviewer has already decided about that attribute,
   * and the attribute producer is allowed to raise it again when the evidence
   * changes — that is how a dismissal stays revisable rather than permanent.
   *
   * This producer's own findings are excluded, and that exclusion is what makes
   * an audit idempotent. Counting them would make the producer defer to itself:
   * run 1 persists the finding, run 2 sees it as "covered" and skips it, and the
   * reconciliation that follows then stales the row it just skipped — so the
   * same condition would oscillate between pending and stale on every audit.
   */
  private async loadCoveredAttributeFindings(
    componentIds: ReadonlySet<string>,
  ): Promise<Map<string, Set<string>>> {
    if (componentIds.size === 0) return new Map();

    const rows = await db
      .select({
        componentId: componentIntelligenceFindings.componentId,
        metadata: componentIntelligenceFindings.metadata,
      })
      .from(componentIntelligenceFindings)
      .where(
        and(
          inArray(componentIntelligenceFindings.componentId, [...componentIds]),
          eq(componentIntelligenceFindings.status, 'PENDING'),
          eq(componentIntelligenceFindings.issueCategory, 'ATTRIBUTE_VALUE'),
          notInArray(componentIntelligenceFindings.source, [
            ATTRIBUTE_SUGGESTION_SOURCE,
          ]),
        ),
      );

    const covered = new Map<string, Set<string>>();
    for (const row of rows) {
      const definitionId = row.metadata?.attributeDefinitionId;
      if (typeof definitionId !== 'string' || definitionId.length === 0) {
        continue;
      }
      const list = covered.get(row.componentId) ?? new Set<string>();
      list.add(definitionId);
      covered.set(row.componentId, list);
    }
    return covered;
  }

  /**
   * Counts requested ids that do not exist. Ids that exist but were cut by the
   * batch limit are not reported as missing.
   */ private async countMissingComponents(
    requestedIds: string[],
    targets: AnalyzableComponent[],
  ): Promise<number> {
    const analyzedIds = new Set(targets.map((target) => target.id));
    const unresolvedIds = requestedIds.filter((id) => !analyzedIds.has(id));
    if (unresolvedIds.length === 0) return 0;

    const existing = await db
      .select({ id: components.id })
      .from(components)
      .where(inArray(components.id, unresolvedIds));

    return unresolvedIds.length - existing.length;
  }

  private async loadTargets(input: {
    scope: ComponentReviewAuditScope;
    componentIds?: string[];
    sinceDays?: number;
    limit: number;
    includeInactive: boolean;
  }): Promise<AnalyzableComponent[]> {
    const selection = componentColumns();

    if (input.scope === 'SELECTED') {
      const ids = Array.from(
        new Set((input.componentIds ?? []).filter((id) => Boolean(id))),
      );
      if (ids.length === 0) return [];
      // Explicitly selected components are analyzed even when inactive.
      return db
        .select(selection)
        .from(components)
        .where(inArray(components.id, ids))
        .orderBy(asc(components.sku))
        .limit(input.limit);
    }

    if (input.scope === 'RECENTLY_UPDATED') {
      const sinceDays = Math.max(
        1,
        input.sinceDays ?? DEFAULT_COMPONENT_AUDIT_RECENT_DAYS,
      );
      const since = new Date(Date.now() - sinceDays * 24 * 60 * 60 * 1000);
      const where = input.includeInactive
        ? gte(components.updatedAt, since)
        : and(gte(components.updatedAt, since), eq(components.isActive, true));
      return db
        .select(selection)
        .from(components)
        .where(where)
        .orderBy(desc(components.updatedAt))
        .limit(input.limit);
    }

    return db
      .select(selection)
      .from(components)
      .where(input.includeInactive ? undefined : eq(components.isActive, true))
      .orderBy(asc(components.sku))
      .limit(input.limit);
  }

  private async loadReferenceData(): Promise<{
    categoryById: Map<string, ComponentCategoryRef>;
    manufacturerById: Map<string, ComponentManufacturerRef>;
  }> {
    const [categoryRows, manufacturerRows] = await Promise.all([
      db
        .select({
          id: categories.id,
          code: categories.code,
          name: categories.name,
          parentId: categories.parentId,
        })
        .from(categories),
      db
        .select({
          id: manufacturers.id,
          code: manufacturers.code,
          name: manufacturers.name,
        })
        .from(manufacturers),
    ]);

    return {
      categoryById: new Map(categoryRows.map((row) => [row.id, row])),
      manufacturerById: new Map(manufacturerRows.map((row) => [row.id, row])),
    };
  }

  /**
   * Resolves the persisted MPN owners for the MPNs identified in this batch.
   *
   * This is an indexed point lookup on the normalized MPN (bounded by the audit
   * batch), replacing the full-catalog read used before Pass 5A. Only the MPNs
   * that the rules actually need are fetched, and every catalog row that shares
   * such an MPN is returned - including inactive rows, exactly as before.
   */
  private async loadMpnOwnerIndex(input: {
    targets: AnalyzableComponent[];
    manufacturerById: Map<string, ComponentManufacturerRef>;
    packagePatterns: string[];
  }): Promise<Map<string, CatalogMpnEntry[]>> {
    const normalizedMpns = new Set<string>();
    for (const target of input.targets) {
      const identity = extractComponentMpnIdentity(
        target,
        input.manufacturerById,
        input.packagePatterns,
      );
      if (identity) normalizedMpns.add(identity.normalized);
    }
    if (normalizedMpns.size === 0) return new Map();

    const rows = await this.selectCatalogRows(
      inArray(normalizedMpnSql(components.manufacturerPartNumber), [
        ...normalizedMpns,
      ]),
    );

    return buildMpnIndex(rows);
  }

  /**
   * Retrieves duplicate candidates and evaluates every rule.
   *
   * Candidate retrieval is grouped in the database by deterministic keys and is
   * deliberately independent of the audit scope, so a duplicate that lives
   * outside the analyzed batch (an old record, or a record far beyond any
   * arbitrary row window) is still discovered:
   *
   *  1. exact MPN groups      - `GROUP BY normalized mpn HAVING count(*) > 1`
   *  2. packaging variants    - rows whose MPN ends with an explicit packaging
   *                             suffix, plus every row whose normalized MPN is
   *                             one of their bases
   *  3. name identity groups  - `GROUP BY normalized name HAVING count(*) > 1`
   *                             restricted to manufacturer-assigned rows
   *  4. semantic blocking     - rows whose name contains an identity token of an
   *                             analyzed component (Pass 5B)
   *
   * Only rows that participate in a candidate group are transferred, so the
   * catalog size does not determine the cost. Structured attribute values are
   * then loaded for the components that actually take part in a candidate pair.
   */
  private async detectDuplicateCandidates(input: {
    targets: AnalyzableComponent[];
    scopeComponentIds: Set<string>;
    includeInactive: boolean;
    categoryById: Map<string, ComponentCategoryRef>;
    manufacturerById: Map<string, ComponentManufacturerRef>;
    manufacturerHints: ManufacturerHintTerm[];
    packagePatterns: string[];
  }): Promise<{
    findings: PersistComponentFindingInput[];
    semantic: SemanticDetectionStats;
    blocking: SemanticBlockingAuditStats;
  }> {
    const catalog = await this.loadDuplicateCandidateCatalog();

    const manufacturerIdentity = buildManufacturerIdentityIndex({
      manufacturers: input.manufacturerById.values(),
      hints: input.manufacturerHints,
    });
    const genericTerms = buildGenericNameTerms({
      categoryTerms: Array.from(input.categoryById.values()).flatMap(
        (category) => [category.name, category.code],
      ),
      packagePatterns: input.packagePatterns,
    });
    const vocabulary: SemanticTokenVocabulary = {
      genericTerms,
      packagePatterns: input.packagePatterns,
    };

    // --- Pass 5B: bounded blocking retrieval ---------------------------------
    const blocking = await this.loadSemanticBlockingRows({
      targets: input.targets,
      vocabulary,
    });

    const rowsById = new Map<string, CatalogMpnEntry>();
    for (const row of [...catalog, ...blocking.rows, ...input.targets]) {
      rowsById.set(row.id, row);
    }

    const { pairs, stats: pairStats } = buildSemanticCandidatePairs({
      rows: [...rowsById.values()],
      scopeComponentIds: input.scopeComponentIds,
      includeInactive: input.includeInactive,
      vocabulary,
    });

    // Structured attributes are loaded for the components that take part in a
    // deterministic name-identity group or in a semantic pair, so the query stays
    // bounded by candidate count rather than catalog size.
    const attributeComponentIds = new Set(
      collectNameIdentityCandidateIds(catalog, {
        manufacturerIdentity,
        genericTerms,
        packagePatterns: input.packagePatterns,
      }),
    );
    for (const pair of pairs) {
      attributeComponentIds.add(pair.member.id);
      attributeComponentIds.add(pair.canonical.id);
    }

    const identityAttributesByComponentId = await loadIdentityAttributeValues([
      ...attributeComponentIds,
    ]);

    const outcome = runDuplicateDetection({
      catalog,
      scopeComponentIds: input.scopeComponentIds,
      includeInactive: input.includeInactive,
      intelligenceVersion: COMPONENT_REVIEW_INTELLIGENCE_VERSION,
      manufacturerIdentity,
      categoryById: input.categoryById,
      identityAttributesByComponentId,
      genericTerms,
      packagePatterns: input.packagePatterns,
      semanticCandidatePairs: pairs,
    });

    return {
      findings: outcome.findings,
      semantic: outcome.semantic,
      blocking: {
        blockingTokensUsed: pairStats.blockingTokensUsed,
        nonSelectiveTokens: pairStats.nonSelectiveTokens,
        rowsRetrieved: blocking.rows.length,
        rowsTruncated: blocking.truncated,
        cappedComponents: pairStats.cappedComponents,
        pairs: pairStats.pairs,
      },
    };
  }

  /**
   * Retrieves rows that share an identity token with an analyzed component.
   *
   * This is the semantic blocking step: candidates are only ever drawn from rows
   * that already collide on a deterministic key, so the layer can never compare
   * every component with every other component.
   *
   * Cost characteristics (documented deliberately):
   *  - the token list is capped at {@link MAX_SEMANTIC_BLOCKING_KEYS}, prioritised
   *    by how many analyzed components carry the token,
   *  - the row transfer is capped at {@link MAX_SEMANTIC_CANDIDATE_ROWS} in
   *    deterministic order and truncation is reported to the caller,
   *  - `ILIKE '%token%'` is a bounded scan, the same order of cost as the name
   *    grouping the deterministic tier already performs.
   */
  private async loadSemanticBlockingRows(input: {
    targets: AnalyzableComponent[];
    vocabulary: SemanticTokenVocabulary;
  }): Promise<{ rows: CatalogMpnEntry[]; truncated: boolean }> {
    const tokenFrequency = new Map<string, number>();
    for (const target of input.targets) {
      for (const token of new Set(
        semanticBlockingTokens(target.name, input.vocabulary),
      )) {
        tokenFrequency.set(token, (tokenFrequency.get(token) ?? 0) + 1);
      }
    }
    if (tokenFrequency.size === 0) return { rows: [], truncated: false };

    const tokens = [...tokenFrequency.entries()]
      .sort(
        ([leftToken, leftCount], [rightToken, rightCount]) =>
          rightCount - leftCount || leftToken.localeCompare(rightToken),
      )
      .slice(0, MAX_SEMANTIC_BLOCKING_KEYS)
      .map(([token]) => token);

    const conditions = tokens.map(
      (token) => sql`${components.name} ilike ${`%${token}%`}`,
    );

    const rows = await this.selectCatalogRows(
      or(...conditions) as SqlCondition,
      MAX_SEMANTIC_CANDIDATE_ROWS,
    );

    return { rows, truncated: rows.length === MAX_SEMANTIC_CANDIDATE_ROWS };
  }

  /**
   * Bounded, database-side candidate retrieval for duplicate detection.
   *
   * Every query is a grouped/indexed lookup on a deterministic key; none of
   * them read the catalog wholesale.
   */
  private async loadDuplicateCandidateCatalog(): Promise<CatalogMpnEntry[]> {
    const normalizedMpn = normalizedMpnSql(components.manufacturerPartNumber);
    const normalizedName = normalizedNameSql(components.name);

    const [exactGroups, packagingRows] = await Promise.all([
      db
        .select({ key: normalizedMpn.as('key') })
        .from(components)
        .where(
          sql`${components.manufacturerPartNumber} is not null and ${normalizedMpn} <> ''`,
        )
        .groupBy(normalizedMpn)
        .having(sql`count(*) > 1`),
      this.selectCatalogRows(
        sql`${components.manufacturerPartNumber} is not null and ${normalizedMpn} ~ ${PACKAGING_SUFFIX_PATTERN}`,
      ),
    ]);

    // Bases of the packaging-suffix rows: any row whose normalized MPN equals
    // one of them is the canonical member of a packaging-variant group.
    const variantBases = new Set<string>();
    for (const row of packagingRows) {
      const normalized = normalizeMpn(row.manufacturerPartNumber);
      if (!normalized) continue;
      variantBases.add(stripPackagingSuffix(normalized));
    }

    const lookupKeys = new Set<string>([
      ...exactGroups.map((row) => row.key),
      ...variantBases,
    ]);

    const relatedRows =
      lookupKeys.size > 0
        ? await this.selectCatalogRows(inArray(normalizedMpn, [...lookupKeys]))
        : [];

    const nameGroupKeys = await db
      .select({ key: normalizedName.as('key') })
      .from(components)
      .where(sql`${components.manufacturerId} is not null`)
      .groupBy(normalizedName)
      .having(sql`count(*) > 1`);

    const nameCandidateRows =
      nameGroupKeys.length > 0
        ? await this.selectCatalogRows(
            and(
              sql`${components.manufacturerId} is not null`,
              inArray(
                normalizedName,
                nameGroupKeys.map((row) => row.key),
              ),
            ) as SqlCondition,
            MAX_NAME_CANDIDATE_ROWS,
          )
        : [];
    if (nameCandidateRows.length === MAX_NAME_CANDIDATE_ROWS) {
      this.logger.warn(
        `Name-identity candidate retrieval reached its ${MAX_NAME_CANDIDATE_ROWS}-row bound; re-run the audit to continue with a stable subset.`,
      );
    }

    const byId = new Map<string, CatalogMpnEntry>();
    for (const row of [
      ...relatedRows,
      ...packagingRows,
      ...nameCandidateRows,
    ]) {
      byId.set(row.id, row);
    }

    return [...byId.values()];
  }

  /** Selects the narrow catalog columns used by duplicate detection. */
  private async selectCatalogRows(
    where: SqlCondition,
    limit?: number,
  ): Promise<CatalogMpnEntry[]> {
    const query = db
      .select({
        id: components.id,
        sku: components.sku,
        name: components.name,
        manufacturerPartNumber: components.manufacturerPartNumber,
        manufacturerId: components.manufacturerId,
        categoryId: components.categoryId,
        isActive: components.isActive,
        createdAt: components.createdAt,
        updatedAt: components.updatedAt,
      })
      .from(components)
      .where(where)
      .orderBy(asc(components.createdAt), asc(components.id));

    const rows = limit ? await query.limit(limit) : await query;

    return rows.map((row) => ({
      ...row,
      manufacturerPartNumber: row.manufacturerPartNumber?.trim() || null,
    }));
  }

  private async loadIntelligenceHints(): Promise<{
    packagePatterns: string[];
    manufacturerHints: ManufacturerHintTerm[];
  }> {
    if (!this.dataPacksService) {
      return { packagePatterns: [], manufacturerHints: [] };
    }
    try {
      const hints = await this.dataPacksService.getActiveIntelligenceHints();
      return {
        packagePatterns: Array.from(
          new Set(hints.flatMap((hint) => hint.packagePatterns ?? [])),
        ),
        manufacturerHints: hints.flatMap(
          (hint) => hint.manufacturerHints ?? [],
        ),
      };
    } catch {
      return { packagePatterns: [], manufacturerHints: [] };
    }
  }
}

function componentColumns() {
  return {
    id: components.id,
    sku: components.sku,
    name: components.name,
    description: components.description,
    manufacturerPartNumber: components.manufacturerPartNumber,
    manufacturerId: components.manufacturerId,
    categoryId: components.categoryId,
    unit: components.unit,
    isActive: components.isActive,
    createdAt: components.createdAt,
    updatedAt: components.updatedAt,
  };
}
