import {
  BadRequestException,
  ConflictException,
  Injectable,
  Logger,
  NotFoundException,
} from '@nestjs/common';
import { db, type DbExecutor } from '@ananya/database';
import {
  aiSuggestionFeedback,
  componentIntelligenceFindings,
  components,
  type ComponentIntelligenceFinding,
} from '@ananya/database/schema';
import {
  and,
  asc,
  count,
  desc,
  eq,
  ilike,
  inArray,
  notInArray,
  or,
  sql,
} from '@ananya/database/query';
import {
  COMPONENT_REVIEW_STATUSES,
  type ComponentReviewDecision,
  type ComponentReviewIssueCategory,
  type ComponentReviewSortField,
  type ComponentReviewStatus,
  type ConfidenceLevel,
} from './component-review-queue.dtos';
import { ATTRIBUTE_VALUE_ISSUE_CATEGORY } from './document-attribute-value-review';
import {
  compareAttributeValues,
  readAbsoluteTolerance,
  readRelativeTolerance,
  toComparableValue,
} from './attribute-value-semantics';
import {
  loadUnitCatalog,
  readAttributeDefinitionState,
  readCurrentAttributeValue,
} from './current-attribute-value';

export interface ReviewerContext {
  id?: string;
  email?: string;
}

export interface PersistComponentFindingInput {
  componentId: string;
  relatedComponentId?: string | null;
  issueType: string;
  issueCategory: ComponentReviewIssueCategory;
  field?: string | null;
  title: string;
  description: string;
  currentValue?: Record<string, unknown> | null;
  suggestedValue?: Record<string, unknown> | null;
  confidence?: number | null;
  confidenceLevel?: ConfidenceLevel | null;
  evidence?: Array<Record<string, unknown>>;
  source: string;
  modelVersion?: string | null;
  intelligenceVersion?: string | null;
  componentUpdatedAt?: string | Date | null;
  metadata?: Record<string, unknown> | null;
}

export interface PersistFindingsResult {
  persistedCount: number;
  findings: ComponentReviewFindingDto[];
}

export interface ListComponentFindingsQuery {
  status?: string | string[];
  issueCategory?: ComponentReviewIssueCategory;
  issueType?: string;
  componentId?: string;
  confidenceLevel?: ConfidenceLevel;
  /** Attribute definition a finding targets (attribute-value suggestions). */
  attributeDefinitionId?: string;
  /** Document a finding was derived from (document-derived findings). */
  documentId?: string;
  /**
   * Restrict to findings a reviewer can act on right now (pending and
   * actionable), or to those that are informational only.
   */
  actionable?: boolean;
  search?: string;
  page?: number;
  pageSize?: number;
  sortBy?: ComponentReviewSortField;
  sortDirection?: 'asc' | 'desc';
}

export interface RecordFindingDecisionInput {
  decision: ComponentReviewDecision;
  decisionNotes?: string;
  expectedFingerprint?: string;
  finalValue?: unknown;
}

export interface MarkFindingsStaleInput {
  ids?: string[];
  componentId?: string;
  reason?: string;
  /**
   * Producers to leave untouched. Used when a change invalidates findings that
   * depend on one kind of state but not another: applying a component field ages
   * identity findings (which snapshot the component row) without invalidating
   * attribute-value suggestions, whose validity is defined by the attribute
   * value and the document revision instead.
   */
  excludeSources?: string[];
}

export interface ReconcileFindingsInput {
  /** Components that were re-analyzed in this run. */
  componentIds: string[];
  /** Fingerprints of findings that are still valid after re-analysis. */
  activeFingerprints: Set<string> | string[];
  /**
   * Producer tags owned by the caller. Only findings from these producers are
   * reconciled, so findings generated by other passes (or manually) are never
   * invalidated by an unrelated analysis run.
   */
  sources: string[];
  reason?: string;
}

export interface ComponentFindingComponentSummary {
  id: string;
  sku: string;
  name: string;
  manufacturerPartNumber: string | null;
  categoryId: string | null;
  manufacturerId: string | null;
  unit: string;
  isActive: boolean;
}

/**
 * One structured attribute recorded on both sides of a duplicate pair.
 *
 * Surfaced so the duplicate review detail can show a match/difference table
 * without re-deriving comparisons at read time. It is produced by the analyzer
 * (which already loaded the values) and stored on the finding metadata, so the
 * comparison always matches the evidence recorded with the finding.
 */
export interface DuplicateAttributeComparisonDto {
  code: string;
  label: string;
  current: string;
  related: string;
  result: 'MATCH' | 'DIFFERENT';
}

export interface ComponentReviewFindingDto {
  id: string;
  componentId: string;
  relatedComponentId: string | null;
  issueType: string;
  issueCategory: string;
  title: string;
  description: string;
  currentValue: Record<string, unknown> | null;
  suggestedValue: Record<string, unknown> | null;
  confidence: number | null;
  confidenceLevel: ConfidenceLevel | null;
  evidence: Array<Record<string, unknown>>;
  source: string;
  modelVersion: string | null;
  intelligenceVersion: string | null;
  fingerprint: string;
  status: ComponentReviewStatus;
  reviewerId: string | null;
  reviewerEmail: string | null;
  reviewedAt: string | null;
  decisionNotes: string | null;
  metadata: Record<string, unknown>;
  /**
   * Structured attribute comparison for duplicate findings. Empty for every
   * other finding type and for legacy duplicate rows persisted before the field
   * existed, so consumers must treat it as optional.
   */
  attributeComparison: DuplicateAttributeComparisonDto[];
  createdAt: string;
  updatedAt: string;
  component: ComponentFindingComponentSummary | null;
  relatedComponent: ComponentFindingComponentSummary | null;
}

export interface ComponentReviewQueueSummary {
  total: number;
  pending: number;
  accepted: number;
  rejected: number;
  dismissed: number;
  stale: number;
  byCategory: Record<string, number>;
}

export interface ComponentReviewQueuePage {
  summary: ComponentReviewQueueSummary;
  items: ComponentReviewFindingDto[];
  total: number;
  page: number;
  pageSize: number;
}

/**
 * Status transitions, decision→feedback mapping and canonical JSON
 * serialization are subject-neutral, so they live in the shared intelligence
 * findings module and are re-exported here.
 *
 * Why re-export rather than import at each call site: the analyzer, the
 * documentation intelligence pipeline and the specs all reach for these through
 * this module, and the rules must be the same rules the Attribute queue uses.
 * Re-exporting keeps every existing import path working while leaving exactly
 * one implementation.
 */
export {
  canDecide,
  decidableStatusesFor,
  mapDecisionToFeedbackAction,
} from './intelligence-findings/finding-lifecycle';
export { stableStringify } from './intelligence-findings/finding-fingerprint';

import { buildIntelligenceFingerprint } from './intelligence-findings/finding-fingerprint';
import {
  canDecide,
  decidableStatusesFor,
  mapDecisionToFeedbackAction,
} from './intelligence-findings/finding-lifecycle';

export interface FindingFingerprintInput {
  componentId: string;
  relatedComponentId?: string | null;
  issueType: string;
  field?: string | null;
  currentValue?: unknown;
  suggestedValue?: unknown;
  intelligenceVersion?: string | null;
}

/**
 * Stable identity for a finding condition. Identical analysis results map to
 * the same fingerprint (idempotent re-audits), while any material change to
 * the reviewed component, suggestion, or intelligence version creates a new
 * finding row instead of silently mutating an existing decision.
 *
 * The component subject is this module's contribution to the hash; the hashing
 * strategy itself is shared. The payload keys and values are unchanged, so
 * fingerprints persisted by earlier passes remain byte-identical.
 */
export function buildFindingFingerprint(
  input: FindingFingerprintInput,
): string {
  return buildIntelligenceFingerprint({
    componentId: input.componentId,
    relatedComponentId: input.relatedComponentId ?? null,
    issueType: input.issueType,
    field: input.field ?? null,
    currentValue: input.currentValue ?? null,
    suggestedValue: input.suggestedValue ?? null,
    intelligenceVersion: input.intelligenceVersion ?? null,
  });
}

@Injectable()
export class ComponentReviewQueueService {
  private readonly logger = new Logger(ComponentReviewQueueService.name);

  /**
   * Persists (or refreshes) findings from an analysis run.
   *
   * Idempotent by fingerprint: re-running analysis with unchanged inputs
   * updates the existing row instead of duplicating it. Reviewer decisions are
   * never overwritten by re-analysis - only STALE findings are returned to
   * PENDING when the same condition is detected again.
   */
  async persistFindings(
    inputs: PersistComponentFindingInput[],
  ): Promise<PersistFindingsResult> {
    if (inputs.length === 0) {
      return { persistedCount: 0, findings: [] };
    }

    const referencedComponentIds = Array.from(
      new Set(
        inputs
          .flatMap((input) => [input.componentId, input.relatedComponentId])
          .filter((id): id is string => Boolean(id)),
      ),
    );

    const knownComponents = await db
      .select({ id: components.id })
      .from(components)
      .where(inArray(components.id, referencedComponentIds));
    const knownIds = new Set(knownComponents.map((row) => row.id));
    const missingIds = referencedComponentIds.filter((id) => !knownIds.has(id));
    if (missingIds.length > 0) {
      throw new NotFoundException(
        `Component(s) not found: ${missingIds.join(', ')}`,
      );
    }

    const now = new Date();
    const rowsByFingerprint = new Map<
      string,
      typeof componentIntelligenceFindings.$inferInsert
    >();

    for (const input of inputs) {
      const fingerprint = buildFindingFingerprint({
        componentId: input.componentId,
        relatedComponentId: input.relatedComponentId ?? null,
        issueType: input.issueType,
        field: input.field ?? null,
        currentValue: input.currentValue ?? null,
        suggestedValue: input.suggestedValue ?? null,
        intelligenceVersion: input.intelligenceVersion ?? null,
      });

      const metadata: Record<string, unknown> = { ...(input.metadata ?? {}) };
      if (input.field) metadata.field = input.field;
      if (input.componentUpdatedAt) {
        metadata.componentUpdatedAt = new Date(
          input.componentUpdatedAt,
        ).toISOString();
      }

      rowsByFingerprint.set(fingerprint, {
        componentId: input.componentId,
        relatedComponentId: input.relatedComponentId ?? null,
        issueType: input.issueType,
        issueCategory: input.issueCategory,
        title: input.title,
        description: input.description,
        currentValue: input.currentValue ?? null,
        suggestedValue: input.suggestedValue ?? null,
        confidence:
          input.confidence === undefined || input.confidence === null
            ? null
            : String(input.confidence),
        confidenceLevel: input.confidenceLevel ?? null,
        evidence: input.evidence ?? [],
        source: input.source,
        modelVersion: input.modelVersion ?? null,
        intelligenceVersion: input.intelligenceVersion ?? null,
        fingerprint,
        metadata,
        updatedAt: now,
      });
    }

    // Postgres refuses ON CONFLICT DO UPDATE affecting the same row twice, so
    // identical findings within a single batch collapse to the last snapshot.
    const insertRows = Array.from(rowsByFingerprint.values());

    const persisted = await db
      .insert(componentIntelligenceFindings)
      .values(insertRows)
      .onConflictDoUpdate({
        target: componentIntelligenceFindings.fingerprint,
        set: {
          title: sql`excluded.title`,
          description: sql`excluded.description`,
          currentValue: sql`excluded.current_value`,
          suggestedValue: sql`excluded.suggested_value`,
          confidence: sql`excluded.confidence`,
          confidenceLevel: sql`excluded.confidence_level`,
          evidence: sql`excluded.evidence`,
          source: sql`excluded.source`,
          modelVersion: sql`excluded.model_version`,
          intelligenceVersion: sql`excluded.intelligence_version`,
          metadata: sql`coalesce(${componentIntelligenceFindings.metadata}, '{}'::jsonb) || excluded.metadata`,
          updatedAt: now,
          status: sql`case when ${componentIntelligenceFindings.status} = 'STALE' then 'PENDING' else ${componentIntelligenceFindings.status} end`,
        },
      })
      .returning();

    const componentSummaries = await this.loadComponentSummaries(
      persisted.flatMap((row) => [
        row.componentId,
        row.relatedComponentId ?? '',
      ]),
    );

    this.logger.log(
      `Persisted ${persisted.length} component intelligence finding(s).`,
    );

    return {
      persistedCount: persisted.length,
      findings: persisted.map((row) => toFindingDto(row, componentSummaries)),
    };
  }

  /**
   * Filtered, paginated queue read.
   *
   * `summary` counts ignore the status filter so queue tabs always show true
   * totals, while `total`/`items` honour every filter for pagination.
   */
  async listFindings(
    query: ListComponentFindingsQuery = {},
  ): Promise<ComponentReviewQueuePage> {
    const page = Math.max(1, query.page ?? 1);
    const pageSize = Math.min(100, Math.max(1, query.pageSize ?? 20));
    const statuses = this.normalizeStatuses(query.status);

    const baseConditions = await this.buildBaseConditions(query);

    const baseWhere = and(...baseConditions);
    const statusCondition =
      statuses.length > 0
        ? inArray(componentIntelligenceFindings.status, statuses)
        : undefined;
    const where = statusCondition
      ? and(...baseConditions, statusCondition)
      : baseWhere;

    const [statusRows, categoryRows, totalRows, rows] = await Promise.all([
      db
        .select({
          status: componentIntelligenceFindings.status,
          value: count(),
        })
        .from(componentIntelligenceFindings)
        .where(baseWhere)
        .groupBy(componentIntelligenceFindings.status),
      db
        .select({
          issueCategory: componentIntelligenceFindings.issueCategory,
          value: count(),
        })
        .from(componentIntelligenceFindings)
        .where(baseWhere)
        .groupBy(componentIntelligenceFindings.issueCategory),
      db
        .select({ value: count() })
        .from(componentIntelligenceFindings)
        .where(where),
      db
        .select()
        .from(componentIntelligenceFindings)
        .where(where)
        .orderBy(this.resolveOrderBy(query))
        .limit(pageSize)
        .offset((page - 1) * pageSize),
    ]);

    const summary: ComponentReviewQueueSummary = {
      total: 0,
      pending: 0,
      accepted: 0,
      rejected: 0,
      dismissed: 0,
      stale: 0,
      byCategory: {},
    };
    for (const row of statusRows) {
      const value = Number(row.value);
      summary.total += value;
      if (row.status === 'PENDING') summary.pending = value;
      if (row.status === 'ACCEPTED') summary.accepted = value;
      if (row.status === 'REJECTED') summary.rejected = value;
      if (row.status === 'DISMISSED') summary.dismissed = value;
      if (row.status === 'STALE') summary.stale = value;
    }
    for (const row of categoryRows) {
      summary.byCategory[row.issueCategory] = Number(row.value);
    }

    const componentSummaries = await this.loadComponentSummaries(
      rows.flatMap((row) => [row.componentId, row.relatedComponentId ?? '']),
    );

    return {
      summary,
      items: rows.map((row) => toFindingDto(row, componentSummaries)),
      total: Number(totalRows[0]?.value ?? 0),
      page,
      pageSize,
    };
  }

  /**
   * Reads one finding.
   *
   * `client` defaults to the global connection for ordinary HTTP callers. An
   * orchestration service that already holds a transaction passes its executor
   * so the read participates in that transaction — otherwise the caller would
   * observe committed state while the rest of its work runs against the
   * transaction's snapshot, and the two could disagree.
   */
  async getFinding(
    id: string,
    client: DbExecutor = db,
  ): Promise<ComponentReviewFindingDto> {
    const [row] = await client
      .select()
      .from(componentIntelligenceFindings)
      .where(eq(componentIntelligenceFindings.id, id))
      .limit(1);

    if (!row) {
      throw new NotFoundException(`Component review finding '${id}' not found`);
    }

    const componentSummaries = await this.loadComponentSummaries(
      [row.componentId, row.relatedComponentId ?? ''],
      client,
    );
    return toFindingDto(row, componentSummaries);
  }

  /**
   * Records a reviewer decision and appends the corresponding AI feedback
   * telemetry row atomically.
   *
   * This pass records the lifecycle decision only: it does NOT mutate the
   * component. Applying an accepted suggestion remains an explicit domain
   * operation owned by later passes.
   */
  async recordDecision(
    id: string,
    input: RecordFindingDecisionInput,
    user?: ReviewerContext,
  ): Promise<ComponentReviewFindingDto> {
    const [finding] = await db
      .select()
      .from(componentIntelligenceFindings)
      .where(eq(componentIntelligenceFindings.id, id))
      .limit(1);

    if (!finding) {
      throw new NotFoundException(`Component review finding '${id}' not found`);
    }

    const currentStatus = finding.status as ComponentReviewStatus;
    if (!canDecide(currentStatus, input.decision)) {
      throw new ConflictException(
        currentStatus === 'STALE'
          ? `Finding '${id}' is stale: ${this.describeStaleReason(finding)}. Re-run component analysis before accepting it.`
          : `Finding '${id}' is already ${currentStatus.toLowerCase()} and cannot be decided again.`,
      );
    }

    if (
      input.expectedFingerprint &&
      input.expectedFingerprint !== finding.fingerprint
    ) {
      throw new ConflictException(
        'This finding changed since it was loaded. Refresh the queue and try again.',
      );
    }

    const staleReason = await this.detectStaleness(finding);
    if (staleReason) {
      await this.markFindingsStale({ ids: [finding.id], reason: staleReason });
      throw new ConflictException(
        `Finding '${id}' is stale (${staleReason}). Re-run component analysis to refresh it.`,
      );
    }

    const reviewedAt = new Date();
    const hasFinalValue = input.finalValue !== undefined;
    const metadataPatch = JSON.stringify({
      decision: input.decision,
      decisionNotes: input.decisionNotes ?? null,
      finalValue: hasFinalValue ? input.finalValue : null,
    });

    const updated = await db.transaction(async (tx) => {
      const updatedRows = await tx
        .update(componentIntelligenceFindings)
        .set({
          status: input.decision,
          reviewerId: user?.id ?? null,
          reviewerEmail: user?.email ?? null,
          reviewedAt,
          decisionNotes: input.decisionNotes ?? null,
          updatedAt: reviewedAt,
          metadata: sql`coalesce(${componentIntelligenceFindings.metadata}, '{}'::jsonb) || ${metadataPatch}::jsonb`,
        })
        .where(
          and(
            eq(componentIntelligenceFindings.id, id),
            inArray(
              componentIntelligenceFindings.status,
              decidableStatusesFor(input.decision),
            ),
          ),
        )
        .returning();

      const row = updatedRows[0];
      if (!row) return null;

      await tx.insert(aiSuggestionFeedback).values({
        componentId: finding.componentId,
        suggestionType: finding.issueType,
        field: resolveFeedbackField(finding),
        predictedValue: finding.suggestedValue ?? null,
        confidence: finding.confidence,
        confidenceLevel: finding.confidenceLevel ?? 'MEDIUM',
        evidence: finding.evidence ?? [],
        modelVersion: finding.modelVersion ?? '1.0.0',
        userAction: mapDecisionToFeedbackAction(input.decision, hasFinalValue),
        finalValue: hasFinalValue
          ? input.finalValue
          : input.decision === 'ACCEPTED'
            ? (finding.suggestedValue ?? null)
            : null,
        reviewerId: user?.id ?? null,
        reviewerEmail: user?.email ?? null,
        metadata: {
          findingId: finding.id,
          issueCategory: finding.issueCategory,
          issueType: finding.issueType,
          decision: input.decision,
          decisionNotes: input.decisionNotes ?? null,
          intelligenceVersion: finding.intelligenceVersion ?? null,
        },
      });

      return row;
    });

    if (!updated) {
      throw new ConflictException(
        `Finding '${id}' was decided by another reviewer. Refresh the queue to see the current state.`,
      );
    }

    return this.getFinding(updated.id);
  }

  /**
   * Marks generated findings as STALE. Used when the component changes after a
   * finding was produced, and by future passes to invalidate findings for
   * components that were edited or re-imported.
   */
  async markFindingsStale(
    input: MarkFindingsStaleInput,
  ): Promise<{ staledCount: number }> {
    const ids = (input.ids ?? []).filter((id) => Boolean(id));
    if (ids.length === 0 && !input.componentId) {
      throw new BadRequestException(
        'Provide finding ids or a componentId to mark findings stale.',
      );
    }

    const excluded = (input.excludeSources ?? []).filter((source) =>
      Boolean(source),
    );
    const conditions = [
      ids.length > 0
        ? inArray(componentIntelligenceFindings.id, ids)
        : undefined,
      input.componentId
        ? eq(componentIntelligenceFindings.componentId, input.componentId)
        : undefined,
      excluded.length > 0
        ? notInArray(componentIntelligenceFindings.source, excluded)
        : undefined,
      eq(componentIntelligenceFindings.status, 'PENDING'),
    ].filter((condition): condition is NonNullable<typeof condition> =>
      Boolean(condition),
    );

    const patch = JSON.stringify({
      staleReason: input.reason ?? null,
      staledAt: new Date().toISOString(),
    });

    const rows = await db
      .update(componentIntelligenceFindings)
      .set({
        status: 'STALE',
        updatedAt: new Date(),
        metadata: sql`coalesce(${componentIntelligenceFindings.metadata}, '{}'::jsonb) || ${patch}::jsonb`,
      })
      .where(and(...conditions))
      .returning({ id: componentIntelligenceFindings.id });

    if (rows.length > 0) {
      this.logger.log(`Marked ${rows.length} finding(s) as STALE.`);
    }

    return { staledCount: rows.length };
  }

  /**
   * Marks PENDING findings produced by the given producers as STALE when they
   * were not re-detected by the latest analysis run.
   *
   * This keeps the queue truthful: an issue that no longer exists must not
   * remain reviewable, while terminal decisions (ACCEPTED / REJECTED /
   * DISMISSED) are preserved untouched so review history survives.
   */
  async reconcileFindings(
    input: ReconcileFindingsInput,
  ): Promise<{ staledCount: number }> {
    const componentIds = Array.from(
      new Set((input.componentIds ?? []).filter((id) => Boolean(id))),
    );
    const sources = Array.from(
      new Set((input.sources ?? []).filter((source) => Boolean(source))),
    );
    if (componentIds.length === 0 || sources.length === 0) {
      return { staledCount: 0 };
    }

    const active =
      input.activeFingerprints instanceof Set
        ? input.activeFingerprints
        : new Set(input.activeFingerprints);

    const pending = await db
      .select({
        id: componentIntelligenceFindings.id,
        fingerprint: componentIntelligenceFindings.fingerprint,
      })
      .from(componentIntelligenceFindings)
      .where(
        and(
          inArray(componentIntelligenceFindings.componentId, componentIds),
          eq(componentIntelligenceFindings.status, 'PENDING'),
          inArray(componentIntelligenceFindings.source, sources),
        ),
      );

    const staleIds = pending
      .filter((row) => !active.has(row.fingerprint))
      .map((row) => row.id);
    if (staleIds.length === 0) return { staledCount: 0 };

    let staledCount = 0;
    for (let index = 0; index < staleIds.length; index += 200) {
      const chunk = staleIds.slice(index, index + 200);
      const result = await this.markFindingsStale({
        ids: chunk,
        reason:
          input.reason ?? 'No longer detected by the latest component analysis',
      });
      staledCount += result.staledCount;
    }

    return { staledCount };
  }

  private async buildBaseConditions(query: ListComponentFindingsQuery) {
    const conditions = [
      query.issueCategory
        ? eq(componentIntelligenceFindings.issueCategory, query.issueCategory)
        : undefined,
      query.issueType
        ? eq(componentIntelligenceFindings.issueType, query.issueType)
        : undefined,
      query.componentId
        ? eq(componentIntelligenceFindings.componentId, query.componentId)
        : undefined,
      query.confidenceLevel
        ? eq(
            componentIntelligenceFindings.confidenceLevel,
            query.confidenceLevel,
          )
        : undefined,
      // Attribute and document relations live in the finding metadata, which is
      // where every producer records them. The jsonb access is bounded by the
      // component/status/issue-type conditions alongside it.
      query.attributeDefinitionId
        ? sql`${componentIntelligenceFindings.metadata} ->> 'attributeDefinitionId' = ${query.attributeDefinitionId}`
        : undefined,
      query.documentId
        ? sql`${componentIntelligenceFindings.metadata} -> 'document' ->> 'documentId' = ${query.documentId}`
        : undefined,
      query.actionable === undefined
        ? undefined
        : query.actionable
          ? sql`${componentIntelligenceFindings.metadata} ->> 'actionable' = 'true'`
          : sql`coalesce(${componentIntelligenceFindings.metadata} ->> 'actionable', 'true') <> 'true'`,
    ].filter((condition): condition is NonNullable<typeof condition> =>
      Boolean(condition),
    );

    const term = query.search?.trim();
    if (!term) return conditions;

    // Free-text search spans the finding text and the reviewed component's
    // identity fields (SKU / MPN / name), bounded to keep the lookup cheap.
    const pattern = `%${term}%`;
    const matchingComponents = await db
      .select({ id: components.id })
      .from(components)
      .where(
        or(
          ilike(components.sku, pattern),
          ilike(components.name, pattern),
          ilike(components.manufacturerPartNumber, pattern),
        ),
      )
      .limit(200);
    const matchingComponentIds = matchingComponents.map((row) => row.id);

    const searchCondition = or(
      ilike(componentIntelligenceFindings.title, pattern),
      ilike(componentIntelligenceFindings.description, pattern),
      matchingComponentIds.length > 0
        ? inArray(
            componentIntelligenceFindings.componentId,
            matchingComponentIds,
          )
        : undefined,
    );
    if (searchCondition) conditions.push(searchCondition);

    return conditions;
  }

  private resolveOrderBy(query: ListComponentFindingsQuery) {
    const column =
      query.sortBy === 'updatedAt'
        ? componentIntelligenceFindings.updatedAt
        : query.sortBy === 'confidence'
          ? componentIntelligenceFindings.confidence
          : componentIntelligenceFindings.createdAt;
    return query.sortDirection === 'asc' ? asc(column) : desc(column);
  }

  private normalizeStatuses(
    input?: string | string[],
  ): ComponentReviewStatus[] {
    if (!input) return [];
    const tokens = (Array.isArray(input) ? input : input.split(','))
      .map((token) => token.trim().toUpperCase())
      .filter((token) => token.length > 0);

    const unknown = tokens.filter(
      (token) =>
        !COMPONENT_REVIEW_STATUSES.includes(token as ComponentReviewStatus),
    );
    if (unknown.length > 0) {
      throw new BadRequestException(
        `Unknown component review status: ${unknown.join(', ')}`,
      );
    }

    return Array.from(new Set(tokens)) as ComponentReviewStatus[];
  }

  private async loadComponentSummaries(
    ids: string[],
    client: DbExecutor = db,
  ): Promise<Map<string, ComponentFindingComponentSummary>> {
    const uniqueIds = Array.from(new Set(ids.filter((id) => Boolean(id))));
    if (uniqueIds.length === 0) return new Map();

    const rows = await client
      .select({
        id: components.id,
        sku: components.sku,
        name: components.name,
        manufacturerPartNumber: components.manufacturerPartNumber,
        categoryId: components.categoryId,
        manufacturerId: components.manufacturerId,
        unit: components.unit,
        isActive: components.isActive,
      })
      .from(components)
      .where(inArray(components.id, uniqueIds));

    return new Map(rows.map((row) => [row.id, row]));
  }

  /**
   * Compares the state a finding was generated from with the current state.
   * Returns a human-readable reason when the finding is stale.
   *
   * Two staleness bases exist, because two kinds of finding depend on two kinds
   * of state:
   *
   *  - component-field findings (identity, classification) snapshot the
   *    component row's `updatedAt`;
   *  - attribute-value findings snapshot the *attribute value* the component
   *    recorded, which a component-row update does not change and which a manual
   *    attribute edit changes without touching the row.
   *
   * Checking the wrong one would either let a stale suggestion be applied over a
   * newer manual value, or invalidate a perfectly good suggestion whenever an
   * unrelated field changed.
   */
  private async detectStaleness(
    finding: ComponentIntelligenceFinding,
  ): Promise<string | null> {
    const attributeDefinitionId = readMetadataString(
      finding.metadata?.attributeDefinitionId,
    );
    if (
      finding.issueCategory === ATTRIBUTE_VALUE_ISSUE_CATEGORY &&
      attributeDefinitionId
    ) {
      return this.detectAttributeValueStaleness(finding, attributeDefinitionId);
    }

    const snapshot = finding.metadata?.componentUpdatedAt;
    if (typeof snapshot !== 'string' || snapshot.length === 0) return null;

    const [component] = await db
      .select({ updatedAt: components.updatedAt })
      .from(components)
      .where(eq(components.id, finding.componentId))
      .limit(1);

    // The component row is validated at persistence time; a missing row here
    // means it was deleted while the finding was pending.
    if (!component) return 'the component no longer exists';

    if (
      component.updatedAt.toISOString() !== new Date(snapshot).toISOString()
    ) {
      return 'the component changed after this finding was generated';
    }

    return null;
  }

  /**
   * Staleness for attribute-value suggestions: the recorded value must still be
   * the one the suggestion was generated against.
   *
   * Compared through the semantic layer, so an equivalent value re-expressed in
   * another unit (`1000 Ω` becoming `1 kΩ`) is recognised as the same recorded
   * value instead of invalidating a suggestion that is still correct.
   */
  private async detectAttributeValueStaleness(
    finding: ComponentIntelligenceFinding,
    attributeDefinitionId: string,
  ): Promise<string | null> {
    const recorded = readRecordedCurrentValue(finding.currentValue);
    const live = await readCurrentAttributeValue(
      finding.componentId,
      attributeDefinitionId,
    );

    // No value recorded at analysis time: the suggestion was "this attribute is
    // not set". It becomes stale as soon as anything sets it.
    if (recorded === null) {
      return live
        ? 'the component now records a value for this attribute'
        : null;
    }

    if (!live) {
      return 'the recorded value for this attribute was removed';
    }

    if (live.display === recorded) return null;

    const [definition, units] = await Promise.all([
      readAttributeDefinitionState(attributeDefinitionId),
      loadUnitCatalog(),
    ]);

    const comparison = compareAttributeValues({
      dataType: definition?.dataType ?? 'QUANTITY',
      unitCategory: definition?.unitCategory ?? null,
      units,
      first: toComparableValue({
        dataType: definition?.dataType ?? 'QUANTITY',
        display: recorded,
      }),
      second: toComparableValue({
        dataType: definition?.dataType ?? 'QUANTITY',
        display: live.display,
      }),
      relativeTolerance: readRelativeTolerance(definition?.validationRules),
      absoluteTolerance: readAbsoluteTolerance(definition?.validationRules),
    });

    if (comparison.equivalent) return null;

    return 'the recorded value for this attribute changed after this finding was generated';
  }

  private describeStaleReason(finding: ComponentIntelligenceFinding): string {
    const reason = finding.metadata?.staleReason;
    return typeof reason === 'string' && reason.length > 0
      ? reason
      : 'the component changed after this finding was generated';
  }
}

function resolveFeedbackField(finding: ComponentIntelligenceFinding): string {
  const field = finding.metadata?.field;
  if (typeof field === 'string' && field.length > 0) return field;
  return finding.issueType.toLowerCase();
}

/** Narrows a metadata value to a non-empty string. */
function readMetadataString(value: unknown): string | null {
  return typeof value === 'string' && value.length > 0 ? value : null;
}

/**
 * Reads the attribute value recorded on a finding when it was generated.
 *
 * Returns `null` both when the attribute had no value and when the payload is
 * unusable, which the caller treats identically: the suggestion claimed "not
 * set", so any value now present invalidates it.
 */
function readRecordedCurrentValue(
  currentValue: Record<string, unknown> | null,
): string | null {
  const value = currentValue?.value;
  return typeof value === 'string' && value.length > 0 ? value : null;
}

/**
 * Reads the duplicate attribute comparison stored on the finding metadata.
 *
 * Defensive by design: metadata is a jsonb payload, so anything that is not a
 * well-formed entry is dropped instead of being surfaced to the UI as a
 * half-valid row.
 */
function readAttributeComparison(
  metadata: Record<string, unknown> | null | undefined,
): DuplicateAttributeComparisonDto[] {
  const raw = metadata?.attributeComparison;
  if (!Array.isArray(raw)) return [];

  const entries: DuplicateAttributeComparisonDto[] = [];
  for (const item of raw) {
    if (!item || typeof item !== 'object') continue;
    const entry = item as Record<string, unknown>;
    const code = typeof entry.code === 'string' ? entry.code : '';
    const label = typeof entry.label === 'string' ? entry.label : '';
    const result = entry.result;
    if (!code || (result !== 'MATCH' && result !== 'DIFFERENT')) continue;
    entries.push({
      code,
      label: label || code,
      current: typeof entry.current === 'string' ? entry.current : '',
      related: typeof entry.related === 'string' ? entry.related : '',
      result,
    });
  }

  return entries;
}

function toFindingDto(
  row: ComponentIntelligenceFinding,
  componentSummaries: Map<string, ComponentFindingComponentSummary>,
): ComponentReviewFindingDto {
  return {
    id: row.id,
    componentId: row.componentId,
    relatedComponentId: row.relatedComponentId ?? null,
    issueType: row.issueType,
    issueCategory: row.issueCategory,
    title: row.title,
    description: row.description,
    currentValue: row.currentValue ?? null,
    suggestedValue: row.suggestedValue ?? null,
    confidence: row.confidence === null ? null : Number(row.confidence),
    confidenceLevel: (row.confidenceLevel as ConfidenceLevel | null) ?? null,
    evidence: row.evidence ?? [],
    source: row.source,
    modelVersion: row.modelVersion ?? null,
    intelligenceVersion: row.intelligenceVersion ?? null,
    fingerprint: row.fingerprint,
    status: row.status as ComponentReviewStatus,
    reviewerId: row.reviewerId ?? null,
    reviewerEmail: row.reviewerEmail ?? null,
    reviewedAt: row.reviewedAt ? row.reviewedAt.toISOString() : null,
    decisionNotes: row.decisionNotes ?? null,
    metadata: row.metadata ?? {},
    attributeComparison: readAttributeComparison(row.metadata),
    createdAt: row.createdAt.toISOString(),
    updatedAt: row.updatedAt.toISOString(),
    component: componentSummaries.get(row.componentId) ?? null,
    relatedComponent: row.relatedComponentId
      ? (componentSummaries.get(row.relatedComponentId) ?? null)
      : null,
  };
}
