'use client'

import * as React from 'react'
import type { ColumnDef } from '@tanstack/react-table'
import { Factory, Play } from 'lucide-react'
import { PageHeader } from '@/components/ui/page-header'
import { StatCard } from '@/components/ui/stat-card'
import { EntityDataTable } from '@/components/ui/entity-data-table'

interface PlannedProductionOrder {
  id: string
  plannedOrderNumber: string
  assemblySku: string
  assemblyName: string
  suggestedQuantity: number
  scheduledStartDate: string
}

const mockPlannedProd: PlannedProductionOrder[] = [
  {
    id: 'ppo-1',
    plannedOrderNumber: 'PWO-2026-001',
    assemblySku: 'ASY-MOTOR-5K',
    assemblyName: 'Precision Spindle Subassembly',
    suggestedQuantity: 15,
    scheduledStartDate: '2026-02-12',
  },
]

export default function MrpProductionPage() {
  const [orders] = React.useState<PlannedProductionOrder[]>(mockPlannedProd)

  const columns: ColumnDef<PlannedProductionOrder>[] = [
    {
      accessorKey: 'plannedOrderNumber',
      header: 'Planned Order No.',
      cell: ({ row }) => (
        <span className="font-mono text-xs font-bold text-primary">
          {row.original.plannedOrderNumber}
        </span>
      ),
    },
    {
      accessorKey: 'assemblySku',
      header: 'Assembly SKU',
      cell: ({ row }) => (
        <div>
          <p className="font-mono text-xs font-semibold text-foreground">{row.original.assemblySku}</p>
          <p className="text-[11px] text-muted-foreground">{row.original.assemblyName}</p>
        </div>
      ),
    },
    {
      accessorKey: 'suggestedQuantity',
      header: 'Suggested Batch Qty',
      cell: ({ row }) => <span className="font-mono text-xs text-foreground font-semibold">{row.original.suggestedQuantity} units</span>,
    },
    {
      accessorKey: 'scheduledStartDate',
      header: 'Scheduled Start',
      cell: ({ row }) => <span className="text-xs text-muted-foreground">{row.original.scheduledStartDate}</span>,
    },
  ]

  return (
    <div className="space-y-6">
      <PageHeader
        title="MRP Planned Production Orders"
        description="Review planned manufacturing orders generated by MRP gross demand logic."
      />

      <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
        <StatCard
          title="Planned Orders"
          value={orders.length}
          icon={<Factory className="w-4 h-4 text-primary" />}
        />
        <StatCard
          title="Actionable Orders"
          value="1 Ready to Release"
          icon={<Play className="w-4 h-4 text-emerald-500" />}
        />
        <StatCard
          title="Capacity Verified"
          value="100% Work Center Fit"
          icon={<Play className="w-4 h-4 text-blue-500" />}
        />
      </div>

      <EntityDataTable
        data={orders}
        columns={columns}
        searchPlaceholder="Search planned production orders..."
      />
    </div>
  )
}
