"use client";

import * as React from "react";
import type { ColumnDef } from "@tanstack/react-table";
import { Factory, Play, CheckCircle2 } from "lucide-react";
import { PageHeader } from "@/components/ui/page-header";
import { StatCard } from "@/components/ui/stat-card";
import { EntityDataTable } from "@/components/ui/entity-data-table";
import { mrpApi, type PlannedProductionOrderDto } from "@/lib/api/mrp-api";

export default function MrpProductionPage() {
  const [orders, setOrders] = React.useState<PlannedProductionOrderDto[]>([]);
  const [loading, setLoading] = React.useState(true);

  React.useEffect(() => {
    mrpApi
      .getProductionRecommendations()
      .then((data) => setOrders(data || []))
      .catch(() => setOrders([]))
      .finally(() => setLoading(false));
  }, []);

  const totalSuggestedQty = React.useMemo(
    () => orders.reduce((acc, o) => acc + (o.suggestedQuantity || 0), 0),
    [orders],
  );

  const columns: ColumnDef<PlannedProductionOrderDto>[] = [
    {
      accessorKey: "plannedOrderNumber",
      header: "Planned Order No.",
      cell: ({ row }) => (
        <span className="font-mono text-xs font-bold text-primary">
          {row.original.plannedOrderNumber || "-"}
        </span>
      ),
    },
    {
      accessorKey: "assemblySku",
      header: "Assembly SKU",
      cell: ({ row }) => (
        <div>
          <p className="font-mono text-xs font-semibold text-foreground">
            {row.original.assemblySku || "-"}
          </p>
          <p className="text-[11px] text-muted-foreground">
            {row.original.assemblyName || "-"}
          </p>
        </div>
      ),
    },
    {
      accessorKey: "suggestedQuantity",
      header: "Suggested Batch Qty",
      cell: ({ row }) => (
        <span className="font-mono text-xs text-foreground font-semibold">
          {row.original.suggestedQuantity || 0} units
        </span>
      ),
    },
    {
      accessorKey: "scheduledStartDate",
      header: "Scheduled Start",
      cell: ({ row }) => (
        <span className="text-xs text-muted-foreground">
          {row.original.scheduledStartDate || "Scheduled"}
        </span>
      ),
    },
  ];

  return (
    <div className="space-y-6">
      <PageHeader
        title="MRP Planned Production Orders"
        description="Review planned manufacturing orders generated by MRP gross demand logic."
      />

      <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
        <StatCard title="Planned Orders" value={orders.length} icon={Factory} />
        <StatCard
          title="Total Planned Output"
          value={`${totalSuggestedQty} Units`}
          icon={Play}
        />
        <StatCard
          title="Schedule Feasibility"
          value={orders.length > 0 ? "Validated" : "No Orders Pending"}
          icon={CheckCircle2}
        />
      </div>

      <EntityDataTable
        data={orders}
        columns={columns}
        searchPlaceholder="Search planned production orders..."
        loading={loading}
        emptyTitle="No Planned Production Orders"
        emptyMessage="No planned manufacturing orders currently required."
      />
    </div>
  );
}
