import { BadRequestException } from '@nestjs/common';

export interface ImportFieldDefinition {
  /** Canonical field name used by importer (e.g. 'code', 'parentCode', 'sku') */
  name: string;
  /** Human-readable label (e.g. 'Parent Category Code') */
  label: string;
  /** Data type: 'string' | 'number' | 'boolean' | 'date' | 'email' */
  type: 'string' | 'number' | 'boolean' | 'date' | 'email';
  /** Whether the field is mandatory */
  required: boolean;
  /** Relationship reference entity if this field references another model (e.g. 'Category', 'Manufacturer') */
  relationship?: {
    entity: string;
    referenceField: string;
  };
  /** Help description */
  description?: string;
  /** Header aliases accepted by header auto-matcher */
  aliases?: string[];
  /** Realistic sample value for template generation */
  sampleValue: string;
  /** Secondary realistic sample value (for multi-row relationship/hierarchy testing) */
  sampleValue2?: string;
}

export type ImportWriteMode = 'UPSERT' | 'CREATE_ONLY' | 'UPDATE_ONLY';

export interface ImportEntityDefinition {
  entityType: string;
  label: string;
  description: string;
  identityKeys: string[];
  writeMode: ImportWriteMode;
  fields: ImportFieldDefinition[];
}

export const IMPORT_ENTITY_REGISTRY: Record<string, ImportEntityDefinition> = {
  Category: {
    entityType: 'Category',
    label: 'Category',
    description:
      'Hierarchical classification tree for inventory components and catalog parts',
    identityKeys: ['code'],
    writeMode: 'UPSERT',
    fields: [
      {
        name: 'code',
        label: 'Category Code',
        type: 'string',
        required: true,
        description: 'Unique category identifier code',
        aliases: ['code', 'categorycode', 'categoryid', 'catcode'],
        sampleValue: 'ELEC',
        sampleValue2: 'CAP',
      },
      {
        name: 'name',
        label: 'Category Name',
        type: 'string',
        required: true,
        description: 'Human-readable category name',
        aliases: ['name', 'categoryname', 'title'],
        sampleValue: 'Electronics',
        sampleValue2: 'Capacitors',
      },
      {
        name: 'description',
        label: 'Description',
        type: 'string',
        required: false,
        description: 'Optional category description',
        aliases: ['description', 'desc', 'notes'],
        sampleValue: 'Electronic components and sub-assemblies',
        sampleValue2: 'Capacitive catalog parts and components',
      },
      {
        name: 'parentCode',
        label: 'Parent Category Code',
        type: 'string',
        required: false,
        relationship: { entity: 'Category', referenceField: 'code' },
        description:
          'Parent category code for hierarchical classification (blank for root categories)',
        aliases: [
          'parentcode',
          'parentcategorycode',
          'parentcategory',
          'parent',
          'parent_code',
        ],
        sampleValue: '',
        sampleValue2: 'ELEC',
      },
    ],
  },
  Component: {
    entityType: 'Component',
    label: 'Component',
    description: 'Master catalog item, part number, or inventory component',
    identityKeys: ['sku'],
    writeMode: 'UPSERT',
    fields: [
      {
        name: 'sku',
        label: 'SKU / Part Number',
        type: 'string',
        required: true,
        description: 'Unique stock keeping unit or part code',
        aliases: ['sku', 'partnumber', 'itemcode', 'componentcode'],
        sampleValue: 'RES-10K-001',
        sampleValue2: 'CAP-10UF-002',
      },
      {
        name: 'name',
        label: 'Component Name',
        type: 'string',
        required: true,
        description: 'Component name or title',
        aliases: ['name', 'title', 'componentname'],
        sampleValue: '10k Ohm Resistor 1/4W 5%',
        sampleValue2: '10uF 25V Ceramic Capacitor',
      },
      {
        name: 'unit',
        label: 'Unit of Measure',
        type: 'string',
        required: true,
        relationship: { entity: 'Unit', referenceField: 'name' },
        description: 'Base unit of measure (e.g. pcs, meters, kg)',
        aliases: ['unit', 'uom', 'baseunit'],
        sampleValue: 'pcs',
        sampleValue2: 'pcs',
      },
      {
        name: 'description',
        label: 'Description',
        type: 'string',
        required: false,
        description: 'Technical component specifications or notes',
        aliases: ['description', 'desc', 'specifications'],
        sampleValue: 'Through-hole carbon film resistor 1/4W 5% tolerance',
        sampleValue2: 'SMD 0805 X7R ceramic capacitor 25V',
      },
      {
        name: 'categoryCode',
        label: 'Category Code',
        type: 'string',
        required: false,
        relationship: { entity: 'Category', referenceField: 'code' },
        description: 'Associated category code',
        aliases: ['categorycode', 'categoryname', 'category', 'catcode'],
        sampleValue: 'ELEC',
        sampleValue2: 'CAP',
      },
      {
        name: 'manufacturerCode',
        label: 'Manufacturer Code',
        type: 'string',
        required: false,
        relationship: { entity: 'Manufacturer', referenceField: 'code' },
        description: 'Associated manufacturer code',
        aliases: [
          'manufacturercode',
          'manufacturername',
          'manufacturer',
          'mfgcode',
        ],
        sampleValue: 'YAGEO',
        sampleValue2: 'MURATA',
      },
    ],
  },
  Manufacturer: {
    entityType: 'Manufacturer',
    label: 'Manufacturer',
    description: 'Component or product manufacturer organization',
    identityKeys: ['code'],
    writeMode: 'UPSERT',
    fields: [
      {
        name: 'code',
        label: 'Manufacturer Code',
        type: 'string',
        required: true,
        description: 'Unique manufacturer code',
        aliases: [
          'code',
          'mfgcode',
          'manufacturercode',
          'manufacturer_code',
          'manufacturerid',
          'manufacturer_id',
        ],
        sampleValue: 'YAGEO',
        sampleValue2: 'MURATA',
      },
      {
        name: 'name',
        label: 'Manufacturer Name',
        type: 'string',
        required: true,
        description: 'Official manufacturer organization name',
        aliases: ['name', 'manufacturername', 'manufacturer_name', 'mfgname'],
        sampleValue: 'Yageo Corporation',
        sampleValue2: 'Murata Manufacturing Co., Ltd.',
      },
    ],
  },
  Supplier: {
    entityType: 'Supplier',
    label: 'Supplier',
    description: 'Vendor or supplier profile for procurement',
    identityKeys: ['code'],
    writeMode: 'UPSERT',
    fields: [
      {
        name: 'code',
        label: 'Supplier Code',
        type: 'string',
        required: true,
        description: 'Unique vendor supplier code',
        aliases: ['code', 'suppliercode', 'vendorcode'],
        sampleValue: 'SUP-001',
        sampleValue2: 'SUP-002',
      },
      {
        name: 'name',
        label: 'Supplier Name',
        type: 'string',
        required: true,
        description: 'Official vendor business name',
        aliases: ['name', 'suppliername', 'vendorname'],
        sampleValue: 'Acme Components Inc.',
        sampleValue2: 'Global Semiconductor Distro',
      },
      {
        name: 'paymentTerms',
        label: 'Payment Terms',
        type: 'string',
        required: false,
        description: 'Standard payment terms (e.g. NET30, NET60, COD)',
        aliases: ['paymentterms', 'terms'],
        sampleValue: 'NET30',
        sampleValue2: 'NET60',
      },
      {
        name: 'currency',
        label: 'Currency Code',
        type: 'string',
        required: false,
        description: 'Three-letter ISO currency code',
        aliases: ['currency', 'currencycode'],
        sampleValue: 'USD',
        sampleValue2: 'EUR',
      },
      {
        name: 'taxId',
        label: 'Tax Identification Number',
        type: 'string',
        required: false,
        description: 'Tax ID or VAT registration number',
        aliases: ['taxid', 'vatid', 'taxnumber'],
        sampleValue: 'TX-998877',
        sampleValue2: 'VAT-112233',
      },
    ],
  },
  Customer: {
    entityType: 'Customer',
    label: 'Customer',
    description: 'Customer account or client profile',
    identityKeys: ['code'],
    writeMode: 'UPSERT',
    fields: [
      {
        name: 'code',
        label: 'Customer Code',
        type: 'string',
        required: true,
        description: 'Unique customer account code',
        aliases: ['code', 'customercode', 'customernumber', 'clientcode'],
        sampleValue: 'CUST-001',
        sampleValue2: 'CUST-002',
      },
      {
        name: 'name',
        label: 'Customer Name',
        type: 'string',
        required: true,
        description: 'Customer company or contact name',
        aliases: ['name', 'customername', 'clientname'],
        sampleValue: 'Stark Industries',
        sampleValue2: 'Wayne Enterprises',
      },
      {
        name: 'email',
        label: 'Email Address',
        type: 'email',
        required: false,
        description: 'Primary contact email',
        aliases: ['email', 'contactemail'],
        sampleValue: 'procurement@stark.com',
        sampleValue2: 'orders@wayne.com',
      },
      {
        name: 'phone',
        label: 'Phone Number',
        type: 'string',
        required: false,
        description: 'Primary contact telephone number',
        aliases: ['phone', 'contactphone', 'telephone'],
        sampleValue: '+1-555-0199',
        sampleValue2: '+1-555-0288',
      },
      {
        name: 'currency',
        label: 'Currency',
        type: 'string',
        required: false,
        description: 'Default billing currency code',
        aliases: ['currency', 'billingcurrency'],
        sampleValue: 'USD',
        sampleValue2: 'USD',
      },
      {
        name: 'taxId',
        label: 'Tax ID',
        type: 'string',
        required: false,
        description: 'Customer tax registration number',
        aliases: ['taxid', 'vatid'],
        sampleValue: 'TAX-CUST-01',
        sampleValue2: 'TAX-CUST-02',
      },
    ],
  },
  Warehouse: {
    entityType: 'Warehouse',
    label: 'Warehouse',
    description: 'Physical storage facility or logistics warehouse location',
    identityKeys: ['code'],
    writeMode: 'UPSERT',
    fields: [
      {
        name: 'code',
        label: 'Warehouse Code',
        type: 'string',
        required: true,
        description: 'Unique warehouse identifier code',
        aliases: ['code', 'warehousecode', 'whcode'],
        sampleValue: 'WH-MAIN',
        sampleValue2: 'WH-EAST',
      },
      {
        name: 'name',
        label: 'Warehouse Name',
        type: 'string',
        required: true,
        description: 'Facility name',
        aliases: ['name', 'warehousename'],
        sampleValue: 'Main Central Warehouse',
        sampleValue2: 'East Coast Distribution Center',
      },
      {
        name: 'description',
        label: 'Description',
        type: 'string',
        required: false,
        description: 'Facility location description or address notes',
        aliases: ['description', 'desc', 'notes'],
        sampleValue: 'Primary logistics hub & SMT component storage',
        sampleValue2: 'Regional order fulfillment hub',
      },
    ],
  },
  WarehouseBin: {
    entityType: 'WarehouseBin',
    label: 'Warehouse Bin',
    description:
      'Specific shelf, rack, or storage bin location inside a warehouse',
    identityKeys: ['code'],
    writeMode: 'UPSERT',
    fields: [
      {
        name: 'code',
        label: 'Bin Code',
        type: 'string',
        required: true,
        description: 'Unique bin location code',
        aliases: ['code', 'bincode', 'locationcode'],
        sampleValue: 'BIN-A-01',
        sampleValue2: 'BIN-A-02',
      },
      {
        name: 'warehouseCode',
        label: 'Warehouse Code',
        type: 'string',
        required: true,
        relationship: { entity: 'Warehouse', referenceField: 'code' },
        description: 'Parent warehouse code',
        aliases: ['warehousecode', 'whcode', 'warehouse'],
        sampleValue: 'WH-MAIN',
        sampleValue2: 'WH-MAIN',
      },
      {
        name: 'capacity',
        label: 'Bin Capacity',
        type: 'number',
        required: false,
        description: 'Maximum item unit capacity',
        aliases: ['capacity', 'maxcapacity'],
        sampleValue: '5000',
        sampleValue2: '2500',
      },
      {
        name: 'purpose',
        label: 'Storage Purpose',
        type: 'string',
        required: false,
        description: 'Bin usage purpose (STORAGE, PICKING, STAGING, OVERFLOW)',
        aliases: ['purpose', 'binpurpose', 'type'],
        sampleValue: 'STORAGE',
        sampleValue2: 'PICKING',
      },
    ],
  },
  Location: {
    entityType: 'Location',
    label: 'Location',
    description: 'Hierarchical location tree or storage zone',
    identityKeys: ['code'],
    writeMode: 'UPSERT',
    fields: [
      {
        name: 'code',
        label: 'Location Code',
        type: 'string',
        required: true,
        description: 'Unique location code',
        aliases: ['code', 'locationcode', 'loccode'],
        sampleValue: 'LOC-Z1-01',
        sampleValue2: 'LOC-Z1-02',
      },
      {
        name: 'name',
        label: 'Location Name',
        type: 'string',
        required: true,
        description: 'Human-readable location title',
        aliases: ['name', 'locationname'],
        sampleValue: 'Zone 1 Shelf 01',
        sampleValue2: 'Zone 1 Shelf 02',
      },
      {
        name: 'kind',
        label: 'Location Kind',
        type: 'string',
        required: false,
        description: 'Kind of location (WAREHOUSE, ZONE, RACK, SHELF, BIN)',
        aliases: ['kind', 'locationkind', 'type'],
        sampleValue: 'BIN',
        sampleValue2: 'BIN',
      },
      {
        name: 'description',
        label: 'Description',
        type: 'string',
        required: false,
        description: 'Location notes or details',
        aliases: ['description', 'desc'],
        sampleValue: 'Top shelf bin 01 for reel storage',
        sampleValue2: 'Middle shelf bin 02 for bulk components',
      },
      {
        name: 'parentCode',
        label: 'Parent Location Code',
        type: 'string',
        required: false,
        relationship: { entity: 'Location', referenceField: 'code' },
        description: 'Parent location code for nested hierarchy',
        aliases: [
          'parentcode',
          'parentlocationcode',
          'parentlocation',
          'parent',
        ],
        sampleValue: '',
        sampleValue2: 'LOC-Z1-01',
      },
    ],
  },
  Unit: {
    entityType: 'Unit',
    label: 'Unit of Measure',
    description: 'Standard unit of measure for inventory cataloging',
    identityKeys: ['name'],
    writeMode: 'UPSERT',
    fields: [
      {
        name: 'name',
        label: 'Unit Name',
        type: 'string',
        required: true,
        description: 'Unit symbol or code (e.g. pcs, meters, kg, grams)',
        aliases: ['name', 'unit', 'unitname', 'symbol'],
        sampleValue: 'pcs',
        sampleValue2: 'meters',
      },
      {
        name: 'category',
        label: 'Unit Category',
        type: 'string',
        required: true,
        description:
          'Physical dimension category (Count, Length, Weight, Volume, Time)',
        aliases: ['category', 'unitcategory', 'dimension'],
        sampleValue: 'Count',
        sampleValue2: 'Length',
      },
      {
        name: 'conversionFactor',
        label: 'Conversion Factor',
        type: 'number',
        required: false,
        description:
          'Multiplier relative to base unit of measure (default 1.0000)',
        aliases: ['conversionfactor', 'factor', 'multiplier'],
        sampleValue: '1.0000',
        sampleValue2: '1.0000',
      },
      {
        name: 'precision',
        label: 'Decimal Precision',
        type: 'number',
        required: false,
        description: 'Number of decimal display places (0-4)',
        aliases: ['precision', 'decimals'],
        sampleValue: '0',
        sampleValue2: '2',
      },
    ],
  },
  User: {
    entityType: 'User',
    label: 'User Account',
    description: 'System user account profile',
    identityKeys: ['email'],
    writeMode: 'UPSERT',
    fields: [
      {
        name: 'email',
        label: 'Email Address',
        type: 'email',
        required: true,
        description: 'Corporate user email address',
        aliases: ['email', 'useremail', 'username'],
        sampleValue: 'alex.dev@48studios.com',
        sampleValue2: 'taylor.ops@48studios.com',
      },
      {
        name: 'firstName',
        label: 'First Name',
        type: 'string',
        required: true,
        description: 'Given name',
        aliases: ['firstname', 'first_name', 'fname'],
        sampleValue: 'Alex',
        sampleValue2: 'Taylor',
      },
      {
        name: 'lastName',
        label: 'Last Name',
        type: 'string',
        required: true,
        description: 'Family name',
        aliases: ['lastname', 'last_name', 'lname'],
        sampleValue: 'Vance',
        sampleValue2: 'Morgan',
      },
      {
        name: 'department',
        label: 'Department',
        type: 'string',
        required: false,
        description: 'User department or team',
        aliases: ['department', 'team', 'dept'],
        sampleValue: 'Engineering',
        sampleValue2: 'Operations',
      },
      {
        name: 'roleName',
        label: 'Role Name',
        type: 'string',
        required: false,
        relationship: { entity: 'Role', referenceField: 'name' },
        description: 'Assigned system security role name',
        aliases: ['rolename', 'role', 'securityrole'],
        sampleValue: 'Member',
        sampleValue2: 'Administrator',
      },
    ],
  },
  Role: {
    entityType: 'Role',
    label: 'Security Role',
    description: 'RBAC security role definition',
    identityKeys: ['name'],
    writeMode: 'UPSERT',
    fields: [
      {
        name: 'name',
        label: 'Role Name',
        type: 'string',
        required: true,
        description: 'Unique role title',
        aliases: ['name', 'rolename', 'title'],
        sampleValue: 'Quality Inspector',
        sampleValue2: 'Inventory Manager',
      },
      {
        name: 'description',
        label: 'Description',
        type: 'string',
        required: false,
        description: 'Role permissions summary',
        aliases: ['description', 'desc'],
        sampleValue: 'Inspects incoming components and production runs',
        sampleValue2:
          'Manages inventory transfers, stock adjustments, and audits',
      },
    ],
  },
  Permission: {
    entityType: 'Permission',
    label: 'System Permission',
    description: 'System access control permission',
    identityKeys: ['code'],
    writeMode: 'UPSERT',
    fields: [
      {
        name: 'code',
        label: 'Permission Code',
        type: 'string',
        required: true,
        description: 'Unique permission code key',
        aliases: ['code', 'permissioncode', 'key'],
        sampleValue: 'quality:inspect',
        sampleValue2: 'inventory:adjust',
      },
      {
        name: 'module',
        label: 'Module Name',
        type: 'string',
        required: true,
        description: 'System functional module',
        aliases: ['module', 'modulename'],
        sampleValue: 'Quality',
        sampleValue2: 'Inventory',
      },
      {
        name: 'description',
        label: 'Description',
        type: 'string',
        required: false,
        description: 'Permission capabilities text',
        aliases: ['description', 'desc'],
        sampleValue: 'Permission to record quality inspection results',
        sampleValue2: 'Permission to authorize inventory stock adjustments',
      },
    ],
  },
  Project: {
    entityType: 'Project',
    label: 'Project',
    description: 'R&D or engineering project master record',
    identityKeys: ['projectNumber'],
    writeMode: 'UPSERT',
    fields: [
      {
        name: 'projectNumber',
        label: 'Project Number',
        type: 'string',
        required: true,
        description: 'Unique project tracking number',
        aliases: ['projectnumber', 'code', 'projectcode'],
        sampleValue: 'PRJ-2026-001',
        sampleValue2: 'PRJ-2026-002',
      },
      {
        name: 'name',
        label: 'Project Name',
        type: 'string',
        required: true,
        description: 'Project title',
        aliases: ['name', 'projectname', 'title'],
        sampleValue: 'NextGen Flight Controller',
        sampleValue2: 'Modular Power Distribution Board',
      },
      {
        name: 'projectType',
        label: 'Project Type',
        type: 'string',
        required: false,
        description:
          'Type of project (INTERNAL_R_D, CUSTOMER_BUILD, PROTOTYPE)',
        aliases: ['projecttype', 'type'],
        sampleValue: 'INTERNAL_R_D',
        sampleValue2: 'CUSTOMER_BUILD',
      },
      {
        name: 'priority',
        label: 'Priority',
        type: 'string',
        required: false,
        description: 'Priority level (LOW, MEDIUM, HIGH, URGENT)',
        aliases: ['priority', 'prioritylevel'],
        sampleValue: 'HIGH',
        sampleValue2: 'MEDIUM',
      },
      {
        name: 'status',
        label: 'Project Status',
        type: 'string',
        required: false,
        description: 'Current status (PLANNING, ACTIVE, ON_HOLD, COMPLETED)',
        aliases: ['status', 'projectstatus'],
        sampleValue: 'ACTIVE',
        sampleValue2: 'PLANNING',
      },
      {
        name: 'owner',
        label: 'Owner Email',
        type: 'email',
        required: false,
        relationship: { entity: 'User', referenceField: 'email' },
        description: 'Project lead email address',
        aliases: ['owner', 'owneremail', 'lead'],
        sampleValue: 'alex.dev@48studios.com',
        sampleValue2: 'taylor.ops@48studios.com',
      },
      {
        name: 'projectManager',
        label: 'Project Manager',
        type: 'string',
        required: false,
        description: 'Manager assigned to project',
        aliases: ['projectmanager', 'manager'],
        sampleValue: 'Project Lead',
        sampleValue2: 'Engineering Manager',
      },
      {
        name: 'startDate',
        label: 'Start Date',
        type: 'date',
        required: false,
        description: 'Project start date (YYYY-MM-DD)',
        aliases: ['startdate'],
        sampleValue: '2026-01-01',
        sampleValue2: '2026-02-01',
      },
      {
        name: 'targetCompletionDate',
        label: 'Target Completion Date',
        type: 'date',
        required: false,
        description: 'Target end date (YYYY-MM-DD)',
        aliases: ['targetcompletiondate', 'targetdate', 'enddate'],
        sampleValue: '2026-12-31',
        sampleValue2: '2026-12-31',
      },
      {
        name: 'description',
        label: 'Description',
        type: 'string',
        required: false,
        description: 'Detailed project summary',
        aliases: ['description', 'desc'],
        sampleValue: 'Flight controller hardware design and firmware',
        sampleValue2: 'High efficiency power distribution board',
      },
    ],
  },
  Task: {
    entityType: 'Task',
    label: 'Project Task',
    description: 'Engineering task or work item inside a project',
    identityKeys: ['taskNumber'],
    writeMode: 'UPSERT',
    fields: [
      {
        name: 'taskNumber',
        label: 'Task Number',
        type: 'string',
        required: true,
        description: 'Unique task identifier code',
        aliases: ['tasknumber', 'code', 'taskcode'],
        sampleValue: 'TSK-001-01',
        sampleValue2: 'TSK-001-02',
      },
      {
        name: 'projectNumber',
        label: 'Project Number',
        type: 'string',
        required: true,
        relationship: { entity: 'Project', referenceField: 'projectNumber' },
        description: 'Associated project number',
        aliases: ['projectnumber', 'projectcode', 'project'],
        sampleValue: 'PRJ-2026-001',
        sampleValue2: 'PRJ-2026-001',
      },
      {
        name: 'title',
        label: 'Task Title',
        type: 'string',
        required: true,
        description: 'Task summary title',
        aliases: ['title', 'name', 'tasktitle'],
        sampleValue: 'Schematic Design & Component Selection',
        sampleValue2: 'PCB Layout & Signal Integrity Routing',
      },
      {
        name: 'estimatedHours',
        label: 'Estimated Hours',
        type: 'number',
        required: false,
        description: 'Estimated work hours',
        aliases: ['estimatedhours', 'hours', 'estimate'],
        sampleValue: '40',
        sampleValue2: '60',
      },
      {
        name: 'assignedUser',
        label: 'Assigned User Email',
        type: 'email',
        required: false,
        relationship: { entity: 'User', referenceField: 'email' },
        description: 'Assigned engineer email address',
        aliases: ['assigneduser', 'assignee', 'assignedto'],
        sampleValue: 'alex.dev@48studios.com',
        sampleValue2: 'taylor.ops@48studios.com',
      },
    ],
  },
  BOM: {
    entityType: 'BOM',
    label: 'Bill of Materials',
    description: 'Bill of materials assembly definition',
    identityKeys: ['bomNumber', 'componentSku'],
    writeMode: 'UPSERT',
    fields: [
      {
        name: 'bomNumber',
        label: 'BOM Number',
        type: 'string',
        required: true,
        description: 'Unique BOM assembly code',
        aliases: ['bomnumber', 'code', 'bomcode'],
        sampleValue: 'BOM-FC-V1',
        sampleValue2: 'BOM-FC-V1',
      },
      {
        name: 'name',
        label: 'Assembly Name',
        type: 'string',
        required: true,
        description: 'Assembly title',
        aliases: ['name', 'assemblyname', 'title'],
        sampleValue: 'Flight Controller Main Assembly',
        sampleValue2: 'Flight Controller Main Assembly',
      },
      {
        name: 'componentSku',
        label: 'Component SKU',
        type: 'string',
        required: true,
        relationship: { entity: 'Component', referenceField: 'sku' },
        description: 'Child component part number included in assembly',
        aliases: ['componentsku', 'sku', 'partnumber'],
        sampleValue: 'RES-10K-001',
        sampleValue2: 'CAP-10UF-002',
      },
      {
        name: 'quantity',
        label: 'Quantity per Assembly',
        type: 'number',
        required: true,
        description: 'Quantity required per assembly unit',
        aliases: ['quantity', 'qty', 'count'],
        sampleValue: '4',
        sampleValue2: '2',
      },
      {
        name: 'revision',
        label: 'Revision',
        type: 'string',
        required: false,
        description: 'BOM revision string (e.g. 1.0, A.1)',
        aliases: ['revision', 'rev'],
        sampleValue: '1.0',
        sampleValue2: '1.0',
      },
    ],
  },
  WorkOrder: {
    entityType: 'WorkOrder',
    label: 'Work Order',
    description: 'Production work order for manufacturing assemblies',
    identityKeys: ['orderNumber'],
    writeMode: 'UPSERT',
    fields: [
      {
        name: 'orderNumber',
        label: 'Work Order Number',
        type: 'string',
        required: true,
        description: 'Unique work order tracking number',
        aliases: ['ordernumber', 'code', 'workordernumber'],
        sampleValue: 'WO-2026-001',
        sampleValue2: 'WO-2026-002',
      },
      {
        name: 'bomNumber',
        label: 'BOM Number',
        type: 'string',
        required: true,
        relationship: { entity: 'BOM', referenceField: 'bomNumber' },
        description: 'Target BOM assembly number to manufacture',
        aliases: ['bomnumber', 'bomcode', 'bom'],
        sampleValue: 'BOM-FC-V1',
        sampleValue2: 'BOM-FC-V1',
      },
      {
        name: 'targetQuantity',
        label: 'Target Quantity',
        type: 'number',
        required: true,
        description: 'Number of assembly units to produce',
        aliases: ['targetquantity', 'quantity', 'qty'],
        sampleValue: '50',
        sampleValue2: '100',
      },
      {
        name: 'priority',
        label: 'Priority',
        type: 'string',
        required: false,
        description: 'Production priority (LOW, MEDIUM, HIGH, URGENT)',
        aliases: ['priority', 'prioritylevel'],
        sampleValue: 'HIGH',
        sampleValue2: 'MEDIUM',
      },
      {
        name: 'status',
        label: 'Status',
        type: 'string',
        required: false,
        description: 'Order status (DRAFT, RELEASED, IN_PROGRESS, COMPLETED)',
        aliases: ['status', 'orderstatus'],
        sampleValue: 'RELEASED',
        sampleValue2: 'DRAFT',
      },
    ],
  },
  PurchaseOrder: {
    entityType: 'PurchaseOrder',
    label: 'Purchase Order',
    description: 'Procurement purchase order line item',
    identityKeys: ['orderNumber', 'componentSku'],
    writeMode: 'UPSERT',
    fields: [
      {
        name: 'orderNumber',
        label: 'PO Number',
        type: 'string',
        required: true,
        description: 'Unique purchase order number',
        aliases: ['ordernumber', 'ponumber', 'code'],
        sampleValue: 'PO-2026-001',
        sampleValue2: 'PO-2026-001',
      },
      {
        name: 'supplierCode',
        label: 'Supplier Code',
        type: 'string',
        required: true,
        relationship: { entity: 'Supplier', referenceField: 'code' },
        description: 'Vendor supplier code',
        aliases: ['suppliercode', 'vendorcode', 'supplier'],
        sampleValue: 'SUP-001',
        sampleValue2: 'SUP-001',
      },
      {
        name: 'componentSku',
        label: 'Component SKU',
        type: 'string',
        required: true,
        relationship: { entity: 'Component', referenceField: 'sku' },
        description: 'Ordered component part SKU',
        aliases: ['componentsku', 'sku', 'partnumber'],
        sampleValue: 'RES-10K-001',
        sampleValue2: 'CAP-10UF-002',
      },
      {
        name: 'quantity',
        label: 'Quantity Ordered',
        type: 'number',
        required: true,
        description: 'Quantity ordered from vendor',
        aliases: ['quantity', 'qty'],
        sampleValue: '1000',
        sampleValue2: '500',
      },
      {
        name: 'unitPrice',
        label: 'Unit Purchase Price',
        type: 'number',
        required: false,
        description: 'Unit purchase price in supplier currency',
        aliases: ['unitprice', 'price', 'cost'],
        sampleValue: '0.05',
        sampleValue2: '0.12',
      },
    ],
  },
  OpeningInventory: {
    entityType: 'OpeningInventory',
    label: 'Opening Inventory Balance',
    description:
      'Initial stock balance upload for starting warehouse management',
    identityKeys: ['sku', 'locationCode'],
    writeMode: 'CREATE_ONLY',
    fields: [
      {
        name: 'sku',
        label: 'Component SKU',
        type: 'string',
        required: true,
        relationship: { entity: 'Component', referenceField: 'sku' },
        description: 'Component part SKU',
        aliases: ['sku', 'componentsku', 'partnumber'],
        sampleValue: 'RES-10K-001',
        sampleValue2: 'CAP-10UF-002',
      },
      {
        name: 'locationCode',
        label: 'Location / Bin Code',
        type: 'string',
        required: true,
        relationship: { entity: 'Location', referenceField: 'code' },
        description: 'Storage bin location code',
        aliases: ['locationcode', 'bincode', 'location'],
        sampleValue: 'LOC-Z1-01',
        sampleValue2: 'LOC-Z1-01',
      },
      {
        name: 'quantity',
        label: 'Initial Stock Quantity',
        type: 'number',
        required: true,
        description: 'Physical count quantity',
        aliases: ['quantity', 'qty', 'count'],
        sampleValue: '500',
        sampleValue2: '250',
      },
      {
        name: 'unitCost',
        label: 'Unit Cost Basis',
        type: 'number',
        required: false,
        description: 'Unit valuation cost',
        aliases: ['unitcost', 'cost', 'unitprice'],
        sampleValue: '0.04',
        sampleValue2: '0.10',
      },
    ],
  },
  StockAdjustment: {
    entityType: 'StockAdjustment',
    label: 'Stock Adjustment',
    description: 'Inventory audit balance adjustment',
    identityKeys: ['adjustmentNumber'],
    writeMode: 'CREATE_ONLY',
    fields: [
      {
        name: 'adjustmentNumber',
        label: 'Adjustment Number',
        type: 'string',
        required: true,
        description: 'Unique stock adjustment code',
        aliases: ['adjustmentnumber', 'code', 'adjnumber'],
        sampleValue: 'ADJ-2026-001',
        sampleValue2: 'ADJ-2026-002',
      },
      {
        name: 'sku',
        label: 'Component SKU',
        type: 'string',
        required: true,
        relationship: { entity: 'Component', referenceField: 'sku' },
        description: 'Adjusted component SKU',
        aliases: ['sku', 'componentsku'],
        sampleValue: 'RES-10K-001',
        sampleValue2: 'CAP-10UF-002',
      },
      {
        name: 'locationCode',
        label: 'Location Code',
        type: 'string',
        required: true,
        relationship: { entity: 'Location', referenceField: 'code' },
        description: 'Storage location code',
        aliases: ['locationcode', 'bincode', 'location'],
        sampleValue: 'LOC-Z1-01',
        sampleValue2: 'LOC-Z1-01',
      },
      {
        name: 'adjustedQuantity',
        label: 'Adjusted Quantity Change',
        type: 'number',
        required: true,
        description: 'Quantity delta (+/-)',
        aliases: ['adjustedquantity', 'quantity', 'delta'],
        sampleValue: '50',
        sampleValue2: '-5',
      },
      {
        name: 'reason',
        label: 'Adjustment Reason',
        type: 'string',
        required: false,
        description: 'Reason for inventory stock adjustment',
        aliases: ['reason', 'notes', 'justification'],
        sampleValue: 'Audit discrepancy reconciliation',
        sampleValue2: 'Damaged package during handling',
      },
    ],
  },
  Asset: {
    entityType: 'Asset',
    label: 'Fixed Asset',
    description: 'Capital fixed asset or machinery master record',
    identityKeys: ['assetNumber'],
    writeMode: 'UPSERT',
    fields: [
      {
        name: 'assetNumber',
        label: 'Asset Tag Number',
        type: 'string',
        required: true,
        description: 'Unique asset tag identifier',
        aliases: ['assetnumber', 'code', 'assettag'],
        sampleValue: 'AST-001',
        sampleValue2: 'AST-002',
      },
      {
        name: 'name',
        label: 'Asset Name',
        type: 'string',
        required: true,
        description: 'Asset description title',
        aliases: ['name', 'assetname', 'title'],
        sampleValue: 'SMT Pick and Place Machine',
        sampleValue2: 'Automated Optical Inspection Station',
      },
      {
        name: 'category',
        label: 'Asset Category',
        type: 'string',
        required: false,
        description: 'Asset classification (Machinery, Vehicles, IT Equipment)',
        aliases: ['category', 'assetcategory'],
        sampleValue: 'Machinery',
        sampleValue2: 'Test Equipment',
      },
      {
        name: 'purchaseValue',
        label: 'Purchase Value',
        type: 'number',
        required: false,
        description: 'Acquisition cost value',
        aliases: ['purchasevalue', 'cost', 'value'],
        sampleValue: '45000',
        sampleValue2: '28000',
      },
      {
        name: 'locationCode',
        label: 'Location Code',
        type: 'string',
        required: false,
        relationship: { entity: 'Warehouse', referenceField: 'code' },
        description: 'Asset facility location code',
        aliases: ['locationcode', 'warehousecode', 'location'],
        sampleValue: 'WH-MAIN',
        sampleValue2: 'WH-MAIN',
      },
    ],
  },
  Equipment: {
    entityType: 'Equipment',
    label: 'Equipment',
    description: 'Production equipment or tool unit',
    identityKeys: ['equipmentNumber'],
    writeMode: 'UPSERT',
    fields: [
      {
        name: 'equipmentNumber',
        label: 'Equipment Number',
        type: 'string',
        required: true,
        description: 'Unique equipment identifier code',
        aliases: ['equipmentnumber', 'code', 'eqpnumber'],
        sampleValue: 'EQP-001',
        sampleValue2: 'EQP-002',
      },
      {
        name: 'name',
        label: 'Equipment Name',
        type: 'string',
        required: true,
        description: 'Equipment name',
        aliases: ['name', 'equipmentname', 'title'],
        sampleValue: 'Reflow Oven Line 1',
        sampleValue2: 'Stencil Printer Station',
      },
      {
        name: 'model',
        label: 'Model Number',
        type: 'string',
        required: false,
        description: 'Manufacturer model name/number',
        aliases: ['model', 'modelnumber'],
        sampleValue: 'RF-800',
        sampleValue2: 'SP-300',
      },
      {
        name: 'serialNumber',
        label: 'Serial Number',
        type: 'string',
        required: false,
        description: 'Hardware serial number',
        aliases: ['serialnumber', 'sn', 'serial'],
        sampleValue: 'SN-887766',
        sampleValue2: 'SN-998811',
      },
      {
        name: 'status',
        label: 'Operational Status',
        type: 'string',
        required: false,
        description: 'Status (OPERATIONAL, MAINTENANCE, DECOMMISSIONED)',
        aliases: ['status', 'eqpstatus'],
        sampleValue: 'OPERATIONAL',
        sampleValue2: 'OPERATIONAL',
      },
    ],
  },
  MaintenanceSchedule: {
    entityType: 'MaintenanceSchedule',
    label: 'Maintenance Schedule',
    description: 'Preventive maintenance schedule routine',
    identityKeys: ['scheduleNumber'],
    writeMode: 'UPSERT',
    fields: [
      {
        name: 'scheduleNumber',
        label: 'Schedule Number',
        type: 'string',
        required: true,
        description: 'Unique maintenance schedule code',
        aliases: ['schedulenumber', 'code', 'mntcode'],
        sampleValue: 'MNT-001',
        sampleValue2: 'MNT-002',
      },
      {
        name: 'equipmentNumber',
        label: 'Equipment Number',
        type: 'string',
        required: true,
        relationship: {
          entity: 'Equipment',
          referenceField: 'equipmentNumber',
        },
        description: 'Target equipment number',
        aliases: ['equipmentnumber', 'eqpnumber', 'equipment'],
        sampleValue: 'EQP-001',
        sampleValue2: 'EQP-001',
      },
      {
        name: 'title',
        label: 'Maintenance Title',
        type: 'string',
        required: true,
        description: 'Routine maintenance title',
        aliases: ['title', 'name', 'maintenancetitle'],
        sampleValue: 'Monthly Air Filter Cleaning & Belt Tension Test',
        sampleValue2: 'Quarterly Heating Element Calibration',
      },
      {
        name: 'frequencyDays',
        label: 'Frequency (Days)',
        type: 'number',
        required: false,
        description: 'Recurrence frequency in days',
        aliases: ['frequencydays', 'frequency', 'days'],
        sampleValue: '30',
        sampleValue2: '90',
      },
      {
        name: 'nextDueDate',
        label: 'Next Due Date',
        type: 'date',
        required: false,
        description: 'Next scheduled maintenance due date (YYYY-MM-DD)',
        aliases: ['nextduedate', 'duedate', 'nextdate'],
        sampleValue: '2026-09-01',
        sampleValue2: '2026-11-01',
      },
    ],
  },
  ServiceRequest: {
    entityType: 'ServiceRequest',
    label: 'Service Request',
    description: 'Equipment repair or maintenance service ticket',
    identityKeys: ['requestNumber'],
    writeMode: 'UPSERT',
    fields: [
      {
        name: 'requestNumber',
        label: 'Request Number',
        type: 'string',
        required: true,
        description: 'Unique service request ticket number',
        aliases: ['requestnumber', 'code', 'ticketnumber'],
        sampleValue: 'SRV-001',
        sampleValue2: 'SRV-002',
      },
      {
        name: 'equipmentNumber',
        label: 'Equipment Number',
        type: 'string',
        required: true,
        relationship: {
          entity: 'Equipment',
          referenceField: 'equipmentNumber',
        },
        description: 'Target equipment number',
        aliases: ['equipmentnumber', 'eqpnumber', 'equipment'],
        sampleValue: 'EQP-001',
        sampleValue2: 'EQP-001',
      },
      {
        name: 'title',
        label: 'Issue Summary',
        type: 'string',
        required: true,
        description: 'Brief summary of issue or service requested',
        aliases: ['title', 'summary', 'issue'],
        sampleValue: 'Conveyor belt excessive noise & alignment drift',
        sampleValue2: 'Temperature sensor fluctuation alert',
      },
      {
        name: 'priority',
        label: 'Priority',
        type: 'string',
        required: false,
        description: 'Ticket priority (LOW, MEDIUM, HIGH, URGENT)',
        aliases: ['priority', 'prioritylevel'],
        sampleValue: 'MEDIUM',
        sampleValue2: 'HIGH',
      },
      {
        name: 'status',
        label: 'Status',
        type: 'string',
        required: false,
        description: 'Ticket status (OPEN, IN_PROGRESS, RESOLVED, CLOSED)',
        aliases: ['status', 'ticketstatus'],
        sampleValue: 'OPEN',
        sampleValue2: 'IN_PROGRESS',
      },
    ],
  },
  Warranty: {
    entityType: 'Warranty',
    label: 'Warranty Coverage',
    description: 'Component or vendor product warranty registration',
    identityKeys: ['warrantyNumber'],
    writeMode: 'UPSERT',
    fields: [
      {
        name: 'warrantyNumber',
        label: 'Warranty Certificate Number',
        type: 'string',
        required: true,
        description: 'Unique warranty agreement number',
        aliases: ['warrantynumber', 'code', 'certnumber'],
        sampleValue: 'WRN-001',
        sampleValue2: 'WRN-002',
      },
      {
        name: 'componentSku',
        label: 'Component SKU',
        type: 'string',
        required: true,
        relationship: { entity: 'Component', referenceField: 'sku' },
        description: 'Covered component SKU',
        aliases: ['componentsku', 'sku', 'partnumber'],
        sampleValue: 'RES-10K-001',
        sampleValue2: 'CAP-10UF-002',
      },
      {
        name: 'supplierCode',
        label: 'Supplier Code',
        type: 'string',
        required: true,
        relationship: { entity: 'Supplier', referenceField: 'code' },
        description: 'Warranting vendor supplier code',
        aliases: ['suppliercode', 'vendorcode', 'supplier'],
        sampleValue: 'SUP-001',
        sampleValue2: 'SUP-001',
      },
      {
        name: 'startDate',
        label: 'Start Date',
        type: 'date',
        required: false,
        description: 'Warranty start date (YYYY-MM-DD)',
        aliases: ['startdate', 'effectivefrom'],
        sampleValue: '2026-01-01',
        sampleValue2: '2026-01-01',
      },
      {
        name: 'endDate',
        label: 'End Date',
        type: 'date',
        required: false,
        description: 'Warranty expiration date (YYYY-MM-DD)',
        aliases: ['enddate', 'expireson'],
        sampleValue: '2027-01-01',
        sampleValue2: '2028-01-01',
      },
    ],
  },
  RMA: {
    entityType: 'RMA',
    label: 'Return Merchandise Authorization',
    description: 'Customer or vendor return merchandise authorization',
    identityKeys: ['rmaNumber'],
    writeMode: 'UPSERT',
    fields: [
      {
        name: 'rmaNumber',
        label: 'RMA Number',
        type: 'string',
        required: true,
        description: 'Unique return authorization number',
        aliases: ['rmanumber', 'code', 'returnnumber'],
        sampleValue: 'RMA-2026-001',
        sampleValue2: 'RMA-2026-002',
      },
      {
        name: 'customerCode',
        label: 'Customer Code',
        type: 'string',
        required: true,
        relationship: { entity: 'Customer', referenceField: 'code' },
        description: 'Customer account code',
        aliases: ['customercode', 'clientcode', 'customer'],
        sampleValue: 'CUST-001',
        sampleValue2: 'CUST-001',
      },
      {
        name: 'componentSku',
        label: 'Component SKU',
        type: 'string',
        required: true,
        relationship: { entity: 'Component', referenceField: 'sku' },
        description: 'Returned component SKU',
        aliases: ['componentsku', 'sku', 'partnumber'],
        sampleValue: 'RES-10K-001',
        sampleValue2: 'CAP-10UF-002',
      },
      {
        name: 'quantity',
        label: 'Returned Quantity',
        type: 'number',
        required: true,
        description: 'Quantity returned',
        aliases: ['quantity', 'qty', 'returnedqty'],
        sampleValue: '5',
        sampleValue2: '10',
      },
      {
        name: 'reason',
        label: 'Return Reason',
        type: 'string',
        required: false,
        description: 'Reason for return',
        aliases: ['reason', 'returnreason', 'notes'],
        sampleValue: 'Defective pin soldering during assembly test',
        sampleValue2: 'Wrong component value shipped by vendor',
      },
    ],
  },
};

/**
 * Returns canonical definition for given entityType.
 * Throws BadRequestException if entityType is invalid or generic (like "Entity").
 */
export function getImporterDefinition(
  entityType: string,
): ImportEntityDefinition {
  const normalized = (entityType || '').trim();
  if (!normalized) {
    throw new BadRequestException('Entity type must be specified.');
  }

  const entityAliases: Record<string, string> = {
    manufacturing: 'WorkOrder',
    productionorder: 'WorkOrder',
    productionorders: 'WorkOrder',
    workorder: 'WorkOrder',
    workorders: 'WorkOrder',
    bom: 'BOM',
    boms: 'BOM',
    billofmaterials: 'BOM',
    component: 'Component',
    components: 'Component',
    supplier: 'Supplier',
    suppliers: 'Supplier',
    manufacturer: 'Manufacturer',
    manufacturers: 'Manufacturer',
    category: 'Category',
    categories: 'Category',
    unit: 'Unit',
    units: 'Unit',
    location: 'Location',
    locations: 'Location',
    warehousebin: 'WarehouseBin',
    warehousebins: 'WarehouseBin',
    warehouse: 'Warehouse',
    warehouses: 'Warehouse',
    customer: 'Customer',
    customers: 'Customer',
    user: 'User',
    users: 'User',
    role: 'Role',
    roles: 'Role',
    permission: 'Permission',
    permissions: 'Permission',
    project: 'Project',
    projects: 'Project',
    task: 'Task',
    tasks: 'Task',
    purchaseorder: 'PurchaseOrder',
    purchaseorders: 'PurchaseOrder',
    openinginventory: 'OpeningInventory',
    stockadjustment: 'StockAdjustment',
    stockadjustments: 'StockAdjustment',
    asset: 'Asset',
    assets: 'Asset',
    equipment: 'Equipment',
    equipments: 'Equipment',
    maintenanceschedule: 'MaintenanceSchedule',
    servicerequest: 'ServiceRequest',
    servicerequests: 'ServiceRequest',
    warranty: 'Warranty',
    warranties: 'Warranty',
    rma: 'RMA',
    rmas: 'RMA',
  };

  const resolvedKey = entityAliases[normalized.toLowerCase()] || normalized;
  const matchedKey = Object.keys(IMPORT_ENTITY_REGISTRY).find(
    (k) => k.toLowerCase() === resolvedKey.toLowerCase(),
  );

  if (matchedKey && IMPORT_ENTITY_REGISTRY[matchedKey]) {
    return IMPORT_ENTITY_REGISTRY[matchedKey];
  }

  const supportedList = Object.keys(IMPORT_ENTITY_REGISTRY).join(', ');
  throw new BadRequestException(
    `No importer registered for entity type: "${entityType}". Supported entities are: ${supportedList}.`,
  );
}

/**
 * Returns true if entityType is registered or alias-resolvable.
 */
export function isEntitySupported(entityType: string): boolean {
  try {
    getImporterDefinition(entityType);
    return true;
  } catch {
    return false;
  }
}

/**
 * Returns JSON template representation with headers, sample row, and field metadata.
 */
export function getTemplate(entityType: string) {
  const def = getImporterDefinition(entityType);
  const headers = def.fields.map((f) => f.name);
  const sampleRow: Record<string, string> = {};
  const sampleRow2: Record<string, string> = {};

  def.fields.forEach((f) => {
    sampleRow[f.name] = f.sampleValue;
    sampleRow2[f.name] = f.sampleValue2 || f.sampleValue;
  });

  return {
    entityType: def.entityType,
    label: def.label,
    description: def.description,
    headers,
    sampleRow,
    sampleRow2,
    fields: def.fields,
  };
}

/**
 * Generates clean CSV string content representing the template with headers and realistic sample rows.
 */
export function generateTemplateCsv(entityType: string): string {
  const t = getTemplate(entityType);
  const headerLine = t.headers.join(',');

  const formatRow = (rowObj: Record<string, string>) =>
    t.headers
      .map((h) => {
        const val = rowObj[h] ?? '';
        if (val.includes(',') || val.includes('"') || val.includes('\n')) {
          return `"${val.replace(/"/g, '""')}"`;
        }
        return val;
      })
      .join(',');

  const row1 = formatRow(t.sampleRow);
  const row2 = formatRow(t.sampleRow2);

  return `${headerLine}\n${row1}\n${row2}`;
}

/**
 * Generates XLSX-compatible spreadsheet content representing the template.
 */
export function generateTemplateXlsx(entityType: string): string {
  return generateTemplateCsv(entityType);
}

/**
 * Returns system fields and header aliases for auto-matching in previewImport.
 */
export function getSystemFieldsWithAliases(
  entityType: string,
): { canonicalField: string; aliases: string[] }[] {
  const def = getImporterDefinition(entityType);
  return def.fields.map((f) => ({
    canonicalField: f.name,
    aliases: Array.from(
      new Set([
        f.name.toLowerCase(),
        f.label.toLowerCase().replace(/[^a-z0-9]/g, ''),
        ...(f.aliases || []).map((a) =>
          a.toLowerCase().replace(/[^a-z0-9]/g, ''),
        ),
      ]),
    ),
  }));
}
