/**
 * A unit row a Data Pack installs.
 *
 * Typed explicitly so the optional affine offset is part of the contract rather
 * than an extra property on one array element: the installer reads these rows
 * field by field, and a unit whose offset went unread would convert as if its
 * zero matched the base unit's.
 */
export interface DataPackUnit {
  name: string;
  category: string;
  isBaseUnit: boolean;
  /** Scale to the category's base unit, applied after `conversionOffset`. */
  conversionFactor: string;
  /**
   * Zero-point shift applied before the factor, in this unit's own scale
   * (`°F` is −32). Absent means 0: a purely multiplicative unit.
   */
  conversionOffset?: string | null;
  precision: string;
}

/**
 * The pack's units of measure.
 *
 * `conversionFactor` reaches 18 decimal places where a factor is a repeating
 * decimal (`°F` is 5/9 of a `°C` step), so that an exact conversion stays exact.
 */
const ELECTRONICS_SMD_UNITS: DataPackUnit[] = [
  // Resistance
  {
    name: 'ohm',
    category: 'Resistance',
    isBaseUnit: true,
    conversionFactor: '1.0000',
    precision: '2',
  },
  {
    name: 'kohm',
    category: 'Resistance',
    isBaseUnit: false,
    conversionFactor: '1000.0000',
    precision: '3',
  },
  {
    name: 'Mohm',
    category: 'Resistance',
    isBaseUnit: false,
    conversionFactor: '1000000.0000',
    precision: '4',
  },
  // Capacitance
  {
    name: 'uF',
    category: 'Capacitance',
    isBaseUnit: true,
    conversionFactor: '1.0000',
    precision: '3',
  },
  {
    name: 'nF',
    category: 'Capacitance',
    isBaseUnit: false,
    conversionFactor: '0.0010',
    precision: '4',
  },
  {
    name: 'pF',
    category: 'Capacitance',
    isBaseUnit: false,
    conversionFactor: '0.000001',
    precision: '6',
  },
  {
    name: 'F',
    category: 'Capacitance',
    isBaseUnit: false,
    conversionFactor: '1000000.0000',
    precision: '2',
  },
  // Voltage
  {
    name: 'V',
    category: 'Voltage',
    isBaseUnit: true,
    conversionFactor: '1.0000',
    precision: '2',
  },
  {
    name: 'mV',
    category: 'Voltage',
    isBaseUnit: false,
    conversionFactor: '0.0010',
    precision: '3',
  },
  {
    name: 'kV',
    category: 'Voltage',
    isBaseUnit: false,
    conversionFactor: '1000.0000',
    precision: '2',
  },
  // Power
  {
    name: 'W',
    category: 'Power',
    isBaseUnit: true,
    conversionFactor: '1.0000',
    precision: '3',
  },
  {
    name: 'mW',
    category: 'Power',
    isBaseUnit: false,
    conversionFactor: '0.0010',
    precision: '4',
  },
  {
    name: 'kW',
    category: 'Power',
    isBaseUnit: false,
    conversionFactor: '1000.0000',
    precision: '2',
  },
  // Current
  {
    name: 'A',
    category: 'Current',
    isBaseUnit: true,
    conversionFactor: '1.0000',
    precision: '3',
  },
  {
    name: 'mA',
    category: 'Current',
    isBaseUnit: false,
    conversionFactor: '0.0010',
    precision: '3',
  },
  {
    name: 'uA',
    category: 'Current',
    isBaseUnit: false,
    conversionFactor: '0.000001',
    precision: '6',
  },
  // Inductance
  {
    name: 'uH',
    category: 'Inductance',
    isBaseUnit: true,
    conversionFactor: '1.0000',
    precision: '3',
  },
  {
    name: 'mH',
    category: 'Inductance',
    isBaseUnit: false,
    conversionFactor: '1000.0000',
    precision: '3',
  },
  {
    name: 'H',
    category: 'Inductance',
    isBaseUnit: false,
    conversionFactor: '1000000.0000',
    precision: '3',
  },
  // Percentage
  {
    name: '%',
    category: 'Percentage',
    isBaseUnit: true,
    conversionFactor: '1.0000',
    precision: '2',
  },
  // Temperature
  {
    name: '°C',
    category: 'Temperature',
    isBaseUnit: true,
    conversionFactor: '1.0000',
    precision: '1',
  },
  // `°F` is affine, not multiplicative: its zero is offset from `°C`'s by 32
  // degrees, and the conversion is `(value − 32) × 5/9`. The offset is stored
  // in the unit's own scale (−32) because that number is exact, while the
  // equivalent base-scale offset (−17.77…) would have to be truncated. The
  // factor carries 18 decimal places so that 5/9 is stored exactly enough for
  // `50 °F` to convert to exactly `10 °C` and compare equal to it.
  {
    name: '°F',
    category: 'Temperature',
    isBaseUnit: false,
    conversionFactor: '0.555555555555555556',
    conversionOffset: '-32.000000000000000000',
    precision: '1',
  },
];

export const ELECTRONICS_SMD_PACK = {
  id: 'electronics-smd',
  name: 'Electronics & SMD Dynamic Attributes Pack',
  category: 'Core Lookup' as const,
  description:
    'Standard dynamic attributes for electronics components (Resistance, Capacitance, Inductance, Package footprints, Tolerances, Power/Voltage ratings, Dielectrics) and physical units.',
  entityType: 'AttributeDefinition',
  recordCount: 45,

  units: ELECTRONICS_SMD_UNITS,

  attributeDefinitions: [
    {
      code: 'package',
      name: 'Package / Case',
      description: 'Industry-standard mechanical component footprint / outline',
      dataType: 'SELECT',
      isFilterable: true,
      sortOrder: 1,
      options: [
        { code: '0201', label: '0201 (0603 Metric)', sortOrder: 1 },
        { code: '0402', label: '0402 (1005 Metric)', sortOrder: 2 },
        { code: '0603', label: '0603 (1608 Metric)', sortOrder: 3 },
        { code: '0805', label: '0805 (2012 Metric)', sortOrder: 4 },
        { code: '1206', label: '1206 (3216 Metric)', sortOrder: 5 },
        { code: '1210', label: '1210 (3225 Metric)', sortOrder: 6 },
        { code: '2010', label: '2010 (5025 Metric)', sortOrder: 7 },
        { code: '2512', label: '2512 (6432 Metric)', sortOrder: 8 },
        { code: 'SOD-123', label: 'SOD-123', sortOrder: 9 },
        { code: 'SOD-323', label: 'SOD-323', sortOrder: 10 },
        { code: 'SOT-23', label: 'SOT-23', sortOrder: 11 },
        { code: 'SOT-223', label: 'SOT-223', sortOrder: 12 },
        { code: 'TO-220', label: 'TO-220 (Through Hole)', sortOrder: 13 },
        { code: 'TO-247', label: 'TO-247', sortOrder: 14 },
        { code: 'DIP-8', label: 'DIP-8 (Through Hole)', sortOrder: 15 },
        { code: 'DIP-14', label: 'DIP-14 (Through Hole)', sortOrder: 16 },
        { code: 'DIP-16', label: 'DIP-16 (Through Hole)', sortOrder: 17 },
        { code: 'SOIC-8', label: 'SOIC-8 (150 mil)', sortOrder: 18 },
        { code: 'SOIC-14', label: 'SOIC-14', sortOrder: 19 },
        { code: 'TSSOP-16', label: 'TSSOP-16', sortOrder: 20 },
        { code: 'QFN-32', label: 'QFN-32 (5x5mm)', sortOrder: 21 },
        { code: 'LQFP-48', label: 'LQFP-48 (7x7mm)', sortOrder: 22 },
        { code: 'LQFP-64', label: 'LQFP-64 (10x10mm)', sortOrder: 23 },
        { code: 'BGA', label: 'Ball Grid Array (BGA)', sortOrder: 24 },
        { code: 'Radial', label: 'Radial Can (Through Hole)', sortOrder: 25 },
        { code: 'Axial', label: 'Axial Lead (Through Hole)', sortOrder: 26 },
      ],
    },
    {
      code: 'mounting_type',
      name: 'Mounting Type',
      description: 'Physical mounting technology (SMD/SMT vs Through Hole)',
      dataType: 'SELECT',
      isFilterable: true,
      sortOrder: 2,
      options: [
        { code: 'SMD', label: 'Surface Mount (SMD/SMT)', sortOrder: 1 },
        { code: 'Through Hole', label: 'Through Hole (THT)', sortOrder: 2 },
        { code: 'Panel Mount', label: 'Panel Mount', sortOrder: 3 },
      ],
    },
    {
      code: 'resistance',
      name: 'Resistance',
      description: 'Nominal electrical resistance',
      dataType: 'QUANTITY',
      unitCategory: 'Resistance',
      defaultUnit: 'ohm',
      isFilterable: true,
      sortOrder: 3,
    },
    {
      code: 'tolerance',
      name: 'Tolerance',
      description: 'Component manufacturing tolerance percentage',
      dataType: 'QUANTITY',
      unitCategory: 'Percentage',
      defaultUnit: '%',
      isFilterable: true,
      sortOrder: 4,
    },
    {
      code: 'power_rating',
      name: 'Power Rating',
      description: 'Maximum continuous power dissipation',
      dataType: 'QUANTITY',
      unitCategory: 'Power',
      defaultUnit: 'W',
      isFilterable: true,
      sortOrder: 5,
    },
    {
      code: 'capacitance',
      name: 'Capacitance',
      description: 'Nominal electrical capacitance',
      dataType: 'QUANTITY',
      unitCategory: 'Capacitance',
      defaultUnit: 'uF',
      isFilterable: true,
      sortOrder: 6,
    },
    {
      code: 'voltage_rating',
      name: 'Voltage Rating',
      description: 'Maximum operating DC/AC working voltage',
      dataType: 'QUANTITY',
      unitCategory: 'Voltage',
      defaultUnit: 'V',
      isFilterable: true,
      sortOrder: 7,
    },
    {
      code: 'dielectric',
      name: 'Dielectric Material',
      description: 'Capacitor dielectric formulation or technology',
      dataType: 'SELECT',
      isFilterable: true,
      sortOrder: 8,
      options: [
        { code: 'C0G/NP0', label: 'C0G / NP0 (Ultra-Stable)', sortOrder: 1 },
        { code: 'X5R', label: 'X5R (Semi-Stable)', sortOrder: 2 },
        { code: 'X7R', label: 'X7R (Stable)', sortOrder: 3 },
        { code: 'Y5V', label: 'Y5V (High Dielectric)', sortOrder: 4 },
        {
          code: 'Aluminum Electrolytic',
          label: 'Aluminum Electrolytic',
          sortOrder: 5,
        },
        { code: 'Tantalum', label: 'Tantalum', sortOrder: 6 },
        { code: 'Film', label: 'Film / Polypropylene', sortOrder: 7 },
      ],
    },
    {
      code: 'forward_voltage',
      name: 'Forward Voltage (Vf)',
      description: 'Diode / LED forward conducting voltage drop',
      dataType: 'QUANTITY',
      unitCategory: 'Voltage',
      defaultUnit: 'V',
      isFilterable: true,
      sortOrder: 9,
    },
    {
      code: 'forward_current',
      name: 'Forward Current (If)',
      description: 'Maximum continuous forward current',
      dataType: 'QUANTITY',
      unitCategory: 'Current',
      defaultUnit: 'mA',
      isFilterable: true,
      sortOrder: 10,
    },
    {
      code: 'pin_count',
      name: 'Pin / Conductor Count',
      description: 'Number of pins, contacts, or internal conductors',
      dataType: 'INTEGER',
      isFilterable: true,
      sortOrder: 11,
    },
    {
      code: 'pitch',
      name: 'Contact Pitch',
      description: 'Spacing between adjacent pin or contact centers',
      dataType: 'QUANTITY',
      unitCategory: 'Length',
      defaultUnit: 'mm',
      isFilterable: true,
      sortOrder: 12,
    },
    {
      code: 'cable_type',
      name: 'Cable / Wire Type',
      description: 'Cable construction or wire style',
      dataType: 'SELECT',
      isFilterable: true,
      sortOrder: 13,
      options: [
        { code: 'Ribbon Cable', label: 'Flat Ribbon Cable', sortOrder: 1 },
        { code: 'Coaxial', label: 'Coaxial Cable', sortOrder: 2 },
        { code: 'Twisted Pair', label: 'Twisted Pair (STP/UTP)', sortOrder: 3 },
        {
          code: 'FFC/FPC',
          label: 'Flexible Flat Cable (FFC/FPC)',
          sortOrder: 4,
        },
        {
          code: 'Hookup Wire',
          label: 'Single-Conductor Hookup Wire',
          sortOrder: 5,
        },
      ],
    },
    {
      code: 'connector_type',
      name: 'Connector Interface',
      description: 'Connector mechanical termination style',
      dataType: 'SELECT',
      isFilterable: true,
      sortOrder: 14,
      options: [
        { code: 'USB-C', label: 'USB Type-C', sortOrder: 1 },
        { code: 'USB-A', label: 'USB Type-A', sortOrder: 2 },
        { code: 'JST-XH', label: 'JST-XH (2.50mm)', sortOrder: 3 },
        { code: 'JST-PH', label: 'JST-PH (2.00mm)', sortOrder: 4 },
        { code: 'Pin Header', label: 'Pin Header 2.54mm (0.1")', sortOrder: 5 },
        { code: 'Terminal Block', label: 'Screw Terminal Block', sortOrder: 6 },
      ],
    },
    {
      code: 'length',
      name: 'Length',
      description: 'Physical cable, wire, or component length',
      dataType: 'QUANTITY',
      unitCategory: 'Length',
      defaultUnit: 'mm',
      isFilterable: true,
      sortOrder: 15,
    },
    {
      code: 'mfr_part_number',
      name: 'Manufacturer Part Number (MPN)',
      description: 'Official OEM manufacturer part number code',
      dataType: 'TEXT',
      isFilterable: true,
      sortOrder: 16,
    },
    {
      code: 'operating_temp_min',
      name: 'Operating Temp Min',
      description: 'Minimum specified operating temperature',
      dataType: 'NUMBER',
      unitCategory: 'Temperature',
      defaultUnit: '°C',
      isFilterable: true,
      sortOrder: 17,
    },
    {
      code: 'operating_temp_max',
      name: 'Operating Temp Max',
      description: 'Maximum specified operating temperature',
      dataType: 'NUMBER',
      unitCategory: 'Temperature',
      defaultUnit: '°C',
      isFilterable: true,
      sortOrder: 18,
    },
  ],

  intelligence: [
    {
      categoryName: 'Capacitors',
      categoryCode: 'CAP',
      aliases: [
        'capacitor',
        'cap',
        'mlcc',
        'ceramic capacitor',
        'electrolytic capacitor',
        'tantalum capacitor',
      ],
      keywords: [
        'capacitance',
        'dielectric',
        'x7r',
        'x5r',
        'c0g',
        'np0',
        'mlcc',
        'tantalum',
        'electrolytic',
        'esr',
      ],
      mpnPatterns: [
        '^GRM\\d{2}',
        '^GJM\\d{2}',
        '^C\\d{4}C',
        '^CC\\d{4}',
        '^T491',
        '^T495',
        '^CS\\d{4}',
        '^CL\\d{2}',
        '^EMK\\d{2}',
      ],
      expectedAttributes: [
        'capacitance',
        'voltage',
        'tolerance',
        'dielectric',
        'package',
        'mounting_type',
      ],
      attributeAliases: {
        capacitance: ['cap', 'capacity', 'val'],
        voltage: ['volt', 'rated_voltage', 'vdc'],
        dielectric: ['material', 'temp_coeff'],
      },
      packagePatterns: [
        '0201',
        '0402',
        '0603',
        '0805',
        '1206',
        '1210',
        '1812',
        '2220',
        'radial',
        'smd',
      ],
      electricalUnitHints: {
        capacitance: ['pf', 'nf', 'uf', 'mf', 'f'],
        voltage: ['v', 'kv', 'mv'],
      },
      manufacturerHints: [
        {
          name: 'Murata',
          code: 'MURATA',
          prefixPatterns: ['^GRM\\d{2}', '^GJM\\d{2}'],
          aliases: ['murata'],
        },
        {
          name: 'KEMET',
          code: 'KEMET',
          prefixPatterns: ['^C\\d{4}C', '^T491', '^T495'],
          aliases: ['kemet'],
        },
        {
          name: 'Yageo',
          code: 'YAGEO',
          prefixPatterns: ['^CC\\d{4}'],
          aliases: ['yageo'],
        },
        {
          name: 'Samwha',
          code: 'SAMWHA',
          prefixPatterns: ['^CS\\d{4}'],
          aliases: ['samwha'],
        },
      ],
      classificationExamples: [
        {
          text: '10uF 25V X7R 0805 ceramic capacitor',
          category: 'Electronic Components',
          subcategory: 'Capacitors',
        },
        {
          text: 'GRM21BR61A226ME51L 22uF 10V Murata',
          category: 'Electronic Components',
          subcategory: 'Capacitors',
        },
      ],
    },
    {
      categoryName: 'Resistors',
      categoryCode: 'RES',
      aliases: [
        'resistor',
        'res',
        'smd resistor',
        'chip resistor',
        'thick film resistor',
        'thin film resistor',
        'potentiometer',
      ],
      keywords: [
        'resistance',
        'tolerance',
        'power',
        'thick film',
        'thin film',
        'metal film',
        'carbon film',
        'shunt',
        'ohm',
      ],
      mpnPatterns: [
        '^RC\\d{4}',
        '^RT\\d{4}',
        '^CRCW\\d{4}',
        '^WSL\\d{4}',
        '^\\d{4}W\\d',
        '^ERJ',
        '^MFR',
      ],
      expectedAttributes: [
        'resistance',
        'tolerance',
        'power',
        'package',
        'mounting_type',
      ],
      attributeAliases: {
        resistance: ['res', 'value', 'ohm'],
        tolerance: ['tol'],
        power: ['wattage', 'pwr'],
      },
      packagePatterns: [
        '0201',
        '0402',
        '0603',
        '0805',
        '1206',
        '1210',
        '2010',
        '2512',
        'axial',
      ],
      electricalUnitHints: {
        resistance: ['ohm', 'kohm', 'mohm', 'r', 'k', 'm'],
      },
      manufacturerHints: [
        {
          name: 'Yageo',
          code: 'YAGEO',
          prefixPatterns: ['^RC\\d{4}', '^RT\\d{4}'],
          aliases: ['yageo', 'phycomp'],
        },
        {
          name: 'Vishay',
          code: 'VISHAY',
          prefixPatterns: ['^CRCW\\d{4}', '^WSL\\d{4}'],
          aliases: ['vishay', 'dale'],
        },
        {
          name: 'Uniohm',
          code: 'UNIOHM',
          prefixPatterns: ['^\\d{4}W\\d'],
          aliases: ['uniohm', 'royalohm'],
        },
      ],
      classificationExamples: [
        {
          text: '10k ohm 1% 0805 SMD resistor Yageo',
          category: 'Electronic Components',
          subcategory: 'Resistors',
        },
        {
          text: 'RC0805FR-0710KL 10k resistor',
          category: 'Electronic Components',
          subcategory: 'Resistors',
        },
      ],
    },
    {
      categoryName: 'Inductors',
      categoryCode: 'IND',
      aliases: [
        'inductor',
        'choke',
        'coil',
        'ferrite bead',
        'power inductor',
        'smd inductor',
      ],
      keywords: [
        'inductance',
        'dc resistance',
        'dcr',
        'saturation current',
        'isat',
        'shielded',
        'unshielded',
        'ferrite',
      ],
      mpnPatterns: [
        '^SWPA\\d{4}',
        '^BLM\\d{2}',
        '^LQH\\d{2}',
        '^CD\\d{2}',
        '^IHLP',
        '^NR\\d{4}',
      ],
      expectedAttributes: ['inductance', 'current', 'package', 'mounting_type'],
      attributeAliases: {
        inductance: ['ind', 'val'],
        current: ['isat', 'irms', 'rated_current'],
      },
      packagePatterns: [
        '0402',
        '0603',
        '0805',
        '1206',
        '4020',
        '5040',
        '6045',
        'smd',
      ],
      electricalUnitHints: {
        inductance: ['nh', 'uh', 'mh', 'h'],
        current: ['a', 'ma'],
      },
      manufacturerHints: [
        {
          name: 'Sunlord',
          code: 'SUNLORD',
          prefixPatterns: ['^SWPA\\d{4}'],
          aliases: ['sunlord'],
        },
        {
          name: 'Murata',
          code: 'MURATA',
          prefixPatterns: ['^BLM\\d{2}', '^LQH\\d{2}'],
          aliases: ['murata'],
        },
      ],
      classificationExamples: [
        {
          text: '10uH shielded power inductor 2A',
          category: 'Electronic Components',
          subcategory: 'Inductors',
        },
        {
          text: 'SWPA4020S100MT 10uH SMD Sunlord',
          category: 'Electronic Components',
          subcategory: 'Inductors',
        },
      ],
    },
    {
      categoryName: 'Diodes',
      categoryCode: 'DIO',
      aliases: ['diode', 'schottky', 'rectifier', 'zener', 'tvs', 'esd diode'],
      keywords: [
        'forward voltage',
        'reverse voltage',
        'breakdown',
        'schottky',
        'zener',
        'rectifier',
        'fast recovery',
      ],
      mpnPatterns: [
        '^1N\\d{4}',
        '^MBR\\d{4}',
        '^SS\\d{2}',
        '^BAT\\d{2}',
        '^BAS\\d{2}',
        '^BAV\\d{2}',
      ],
      expectedAttributes: ['voltage', 'current', 'package', 'mounting_type'],
      packagePatterns: [
        'SOD-123',
        'SOD-323',
        'SOD-523',
        'SMA',
        'SMB',
        'SMC',
        'SOT-23',
        'DO-41',
      ],
      manufacturerHints: [
        {
          name: 'Slkor',
          code: 'SLKOR',
          prefixPatterns: ['^SL\\d{4}'],
          aliases: ['slkor'],
        },
        {
          name: 'Tech Public',
          code: 'TECH-PUBLIC',
          prefixPatterns: ['^1N\\d{4}HW', '^SS\\d{2}'],
          aliases: ['tech public'],
        },
        {
          name: 'JSMSEMI',
          code: 'JSMSEMI',
          prefixPatterns: ['^MBR\\d{4}'],
          aliases: ['jsmsemi'],
        },
      ],
    },
    {
      categoryName: 'Transistors',
      categoryCode: 'TRAN',
      aliases: [
        'transistor',
        'mosfet',
        'bjt',
        'igbt',
        'fet',
        'n-channel',
        'p-channel',
      ],
      keywords: [
        'drain source',
        'gate threshold',
        'rds(on)',
        'collector emitter',
        'hfe',
        'saturation',
        'n-channel',
        'p-channel',
      ],
      mpnPatterns: [
        '^BSS\\d{3}',
        '^2N\\d{4}',
        '^SI\\d{4}',
        '^AO\\d{4}',
        '^IRF\\d{3}',
        '^MMBT',
      ],
      expectedAttributes: ['voltage', 'current', 'package', 'mounting_type'],
      packagePatterns: [
        'SOT-23',
        'SOT-223',
        'TO-220',
        'TO-252',
        'DPAK',
        'DFN',
        'QFN',
      ],
      manufacturerHints: [
        {
          name: 'Slkor',
          code: 'SLKOR',
          prefixPatterns: ['^BSS\\d{3}'],
          aliases: ['slkor'],
        },
        {
          name: 'Vishay',
          code: 'VISHAY',
          prefixPatterns: ['^SI\\d{4}'],
          aliases: ['vishay', 'siliconix'],
        },
      ],
    },
    {
      categoryName: 'ICs & Semiconductors',
      categoryCode: 'IC',
      aliases: [
        'ic',
        'microcontroller',
        'mcu',
        'opamp',
        'amplifier',
        'linear regulator',
        'ldo',
        'buck regulator',
      ],
      keywords: [
        'cortex',
        'flash',
        'ram',
        'adc',
        'dac',
        'gpio',
        'operational amplifier',
        'voltage regulator',
      ],
      mpnPatterns: [
        '^STM32',
        '^ESP32',
        '^NE5532',
        '^LM\\d{3,4}',
        '^AMS1117',
        '^MP\\d{4}',
        '^TPS\\d{4}',
      ],
      expectedAttributes: ['package', 'voltage', 'current', 'mounting_type'],
      packagePatterns: ['SOIC-8', 'DIP-8', 'TSSOP', 'QFP', 'QFN', 'BGA'],
      manufacturerHints: [
        {
          name: 'STMicroelectronics',
          code: 'STMICRO',
          prefixPatterns: ['^STM32'],
          aliases: ['stmicro', 'st'],
        },
        {
          name: 'Texas Instruments',
          code: 'TEXAS-INSTRUMENTS',
          prefixPatterns: ['^NE5532', '^LM\\d{3,4}'],
          aliases: ['ti', 'texas instruments'],
        },
      ],
    },
  ],
};
