export const ELECTRONICS_SMD_PACK = {
  id: 'electronics-smd',
  name: 'Electronics & SMD Dynamic Attributes Pack',
  category: 'Core Lookup' as const,
  description:
    'Standard dynamic attributes for electronics components (Resistance, Capacitance, Inductance, Package footprints, Tolerances, Power/Voltage ratings, Dielectrics) and physical units.',
  entityType: 'AttributeDefinition',
  recordCount: 45,

  units: [
    // Resistance
    {
      name: 'ohm',
      category: 'Resistance',
      isBaseUnit: true,
      conversionFactor: '1.0000',
      precision: '2',
    },
    {
      name: 'kohm',
      category: 'Resistance',
      isBaseUnit: false,
      conversionFactor: '1000.0000',
      precision: '3',
    },
    {
      name: 'Mohm',
      category: 'Resistance',
      isBaseUnit: false,
      conversionFactor: '1000000.0000',
      precision: '4',
    },
    // Capacitance
    {
      name: 'uF',
      category: 'Capacitance',
      isBaseUnit: true,
      conversionFactor: '1.0000',
      precision: '3',
    },
    {
      name: 'nF',
      category: 'Capacitance',
      isBaseUnit: false,
      conversionFactor: '0.0010',
      precision: '4',
    },
    {
      name: 'pF',
      category: 'Capacitance',
      isBaseUnit: false,
      conversionFactor: '0.000001',
      precision: '6',
    },
    {
      name: 'F',
      category: 'Capacitance',
      isBaseUnit: false,
      conversionFactor: '1000000.0000',
      precision: '2',
    },
    // Voltage
    {
      name: 'V',
      category: 'Voltage',
      isBaseUnit: true,
      conversionFactor: '1.0000',
      precision: '2',
    },
    {
      name: 'mV',
      category: 'Voltage',
      isBaseUnit: false,
      conversionFactor: '0.0010',
      precision: '3',
    },
    {
      name: 'kV',
      category: 'Voltage',
      isBaseUnit: false,
      conversionFactor: '1000.0000',
      precision: '2',
    },
    // Power
    {
      name: 'W',
      category: 'Power',
      isBaseUnit: true,
      conversionFactor: '1.0000',
      precision: '3',
    },
    {
      name: 'mW',
      category: 'Power',
      isBaseUnit: false,
      conversionFactor: '0.0010',
      precision: '4',
    },
    {
      name: 'kW',
      category: 'Power',
      isBaseUnit: false,
      conversionFactor: '1000.0000',
      precision: '2',
    },
    // Current
    {
      name: 'A',
      category: 'Current',
      isBaseUnit: true,
      conversionFactor: '1.0000',
      precision: '3',
    },
    {
      name: 'mA',
      category: 'Current',
      isBaseUnit: false,
      conversionFactor: '0.0010',
      precision: '3',
    },
    {
      name: 'uA',
      category: 'Current',
      isBaseUnit: false,
      conversionFactor: '0.000001',
      precision: '6',
    },
    // Inductance
    {
      name: 'uH',
      category: 'Inductance',
      isBaseUnit: true,
      conversionFactor: '1.0000',
      precision: '3',
    },
    {
      name: 'mH',
      category: 'Inductance',
      isBaseUnit: false,
      conversionFactor: '1000.0000',
      precision: '3',
    },
    {
      name: 'H',
      category: 'Inductance',
      isBaseUnit: false,
      conversionFactor: '1000000.0000',
      precision: '3',
    },
    // Percentage
    {
      name: '%',
      category: 'Percentage',
      isBaseUnit: true,
      conversionFactor: '1.0000',
      precision: '2',
    },
    // Temperature
    {
      name: '°C',
      category: 'Temperature',
      isBaseUnit: true,
      conversionFactor: '1.0000',
      precision: '1',
    },
  ],

  attributeDefinitions: [
    {
      code: 'package',
      name: 'Package / Case',
      description: 'Industry-standard mechanical component footprint / outline',
      dataType: 'SELECT',
      isFilterable: true,
      sortOrder: 1,
      options: [
        { code: '0201', label: '0201 (0603 Metric)', sortOrder: 1 },
        { code: '0402', label: '0402 (1005 Metric)', sortOrder: 2 },
        { code: '0603', label: '0603 (1608 Metric)', sortOrder: 3 },
        { code: '0805', label: '0805 (2012 Metric)', sortOrder: 4 },
        { code: '1206', label: '1206 (3216 Metric)', sortOrder: 5 },
        { code: '1210', label: '1210 (3225 Metric)', sortOrder: 6 },
        { code: '2010', label: '2010 (5025 Metric)', sortOrder: 7 },
        { code: '2512', label: '2512 (6432 Metric)', sortOrder: 8 },
        { code: 'SOD-123', label: 'SOD-123', sortOrder: 9 },
        { code: 'SOD-323', label: 'SOD-323', sortOrder: 10 },
        { code: 'SOT-23', label: 'SOT-23', sortOrder: 11 },
        { code: 'SOT-223', label: 'SOT-223', sortOrder: 12 },
        { code: 'TO-220', label: 'TO-220 (Through Hole)', sortOrder: 13 },
        { code: 'TO-247', label: 'TO-247', sortOrder: 14 },
        { code: 'DIP-8', label: 'DIP-8 (Through Hole)', sortOrder: 15 },
        { code: 'DIP-14', label: 'DIP-14 (Through Hole)', sortOrder: 16 },
        { code: 'DIP-16', label: 'DIP-16 (Through Hole)', sortOrder: 17 },
        { code: 'SOIC-8', label: 'SOIC-8 (150 mil)', sortOrder: 18 },
        { code: 'SOIC-14', label: 'SOIC-14', sortOrder: 19 },
        { code: 'TSSOP-16', label: 'TSSOP-16', sortOrder: 20 },
        { code: 'QFN-32', label: 'QFN-32 (5x5mm)', sortOrder: 21 },
        { code: 'LQFP-48', label: 'LQFP-48 (7x7mm)', sortOrder: 22 },
        { code: 'LQFP-64', label: 'LQFP-64 (10x10mm)', sortOrder: 23 },
        { code: 'BGA', label: 'Ball Grid Array (BGA)', sortOrder: 24 },
        { code: 'Radial', label: 'Radial Can (Through Hole)', sortOrder: 25 },
        { code: 'Axial', label: 'Axial Lead (Through Hole)', sortOrder: 26 },
      ],
    },
    {
      code: 'mounting_type',
      name: 'Mounting Type',
      description: 'Physical mounting technology (SMD/SMT vs Through Hole)',
      dataType: 'SELECT',
      isFilterable: true,
      sortOrder: 2,
      options: [
        { code: 'SMD', label: 'Surface Mount (SMD/SMT)', sortOrder: 1 },
        { code: 'Through Hole', label: 'Through Hole (THT)', sortOrder: 2 },
        { code: 'Panel Mount', label: 'Panel Mount', sortOrder: 3 },
      ],
    },
    {
      code: 'resistance',
      name: 'Resistance',
      description: 'Nominal electrical resistance',
      dataType: 'QUANTITY',
      unitCategory: 'Resistance',
      defaultUnit: 'ohm',
      isFilterable: true,
      sortOrder: 3,
    },
    {
      code: 'tolerance',
      name: 'Tolerance',
      description: 'Component manufacturing tolerance percentage',
      dataType: 'QUANTITY',
      unitCategory: 'Percentage',
      defaultUnit: '%',
      isFilterable: true,
      sortOrder: 4,
    },
    {
      code: 'power_rating',
      name: 'Power Rating',
      description: 'Maximum continuous power dissipation',
      dataType: 'QUANTITY',
      unitCategory: 'Power',
      defaultUnit: 'W',
      isFilterable: true,
      sortOrder: 5,
    },
    {
      code: 'capacitance',
      name: 'Capacitance',
      description: 'Nominal electrical capacitance',
      dataType: 'QUANTITY',
      unitCategory: 'Capacitance',
      defaultUnit: 'uF',
      isFilterable: true,
      sortOrder: 6,
    },
    {
      code: 'voltage_rating',
      name: 'Voltage Rating',
      description: 'Maximum operating DC/AC working voltage',
      dataType: 'QUANTITY',
      unitCategory: 'Voltage',
      defaultUnit: 'V',
      isFilterable: true,
      sortOrder: 7,
    },
    {
      code: 'dielectric',
      name: 'Dielectric Material',
      description: 'Capacitor dielectric formulation or technology',
      dataType: 'SELECT',
      isFilterable: true,
      sortOrder: 8,
      options: [
        { code: 'C0G/NP0', label: 'C0G / NP0 (Ultra-Stable)', sortOrder: 1 },
        { code: 'X5R', label: 'X5R (Semi-Stable)', sortOrder: 2 },
        { code: 'X7R', label: 'X7R (Stable)', sortOrder: 3 },
        { code: 'Y5V', label: 'Y5V (High Dielectric)', sortOrder: 4 },
        {
          code: 'Aluminum Electrolytic',
          label: 'Aluminum Electrolytic',
          sortOrder: 5,
        },
        { code: 'Tantalum', label: 'Tantalum', sortOrder: 6 },
        { code: 'Film', label: 'Film / Polypropylene', sortOrder: 7 },
      ],
    },
    {
      code: 'forward_voltage',
      name: 'Forward Voltage (Vf)',
      description: 'Diode / LED forward conducting voltage drop',
      dataType: 'QUANTITY',
      unitCategory: 'Voltage',
      defaultUnit: 'V',
      isFilterable: true,
      sortOrder: 9,
    },
    {
      code: 'forward_current',
      name: 'Forward Current (If)',
      description: 'Maximum continuous forward current',
      dataType: 'QUANTITY',
      unitCategory: 'Current',
      defaultUnit: 'mA',
      isFilterable: true,
      sortOrder: 10,
    },
    {
      code: 'pin_count',
      name: 'Pin / Conductor Count',
      description: 'Number of pins, contacts, or internal conductors',
      dataType: 'INTEGER',
      isFilterable: true,
      sortOrder: 11,
    },
    {
      code: 'pitch',
      name: 'Contact Pitch',
      description: 'Spacing between adjacent pin or contact centers',
      dataType: 'QUANTITY',
      unitCategory: 'Length',
      defaultUnit: 'mm',
      isFilterable: true,
      sortOrder: 12,
    },
    {
      code: 'cable_type',
      name: 'Cable / Wire Type',
      description: 'Cable construction or wire style',
      dataType: 'SELECT',
      isFilterable: true,
      sortOrder: 13,
      options: [
        { code: 'Ribbon Cable', label: 'Flat Ribbon Cable', sortOrder: 1 },
        { code: 'Coaxial', label: 'Coaxial Cable', sortOrder: 2 },
        { code: 'Twisted Pair', label: 'Twisted Pair (STP/UTP)', sortOrder: 3 },
        {
          code: 'FFC/FPC',
          label: 'Flexible Flat Cable (FFC/FPC)',
          sortOrder: 4,
        },
        {
          code: 'Hookup Wire',
          label: 'Single-Conductor Hookup Wire',
          sortOrder: 5,
        },
      ],
    },
    {
      code: 'connector_type',
      name: 'Connector Interface',
      description: 'Connector mechanical termination style',
      dataType: 'SELECT',
      isFilterable: true,
      sortOrder: 14,
      options: [
        { code: 'USB-C', label: 'USB Type-C', sortOrder: 1 },
        { code: 'USB-A', label: 'USB Type-A', sortOrder: 2 },
        { code: 'JST-XH', label: 'JST-XH (2.50mm)', sortOrder: 3 },
        { code: 'JST-PH', label: 'JST-PH (2.00mm)', sortOrder: 4 },
        { code: 'Pin Header', label: 'Pin Header 2.54mm (0.1")', sortOrder: 5 },
        { code: 'Terminal Block', label: 'Screw Terminal Block', sortOrder: 6 },
      ],
    },
    {
      code: 'length',
      name: 'Length',
      description: 'Physical cable, wire, or component length',
      dataType: 'QUANTITY',
      unitCategory: 'Length',
      defaultUnit: 'mm',
      isFilterable: true,
      sortOrder: 15,
    },
    {
      code: 'mfr_part_number',
      name: 'Manufacturer Part Number (MPN)',
      description: 'Official OEM manufacturer part number code',
      dataType: 'TEXT',
      isFilterable: true,
      sortOrder: 16,
    },
    {
      code: 'operating_temp_min',
      name: 'Operating Temp Min',
      description: 'Minimum specified operating temperature',
      dataType: 'NUMBER',
      unitCategory: 'Temperature',
      defaultUnit: '°C',
      isFilterable: true,
      sortOrder: 17,
    },
    {
      code: 'operating_temp_max',
      name: 'Operating Temp Max',
      description: 'Maximum specified operating temperature',
      dataType: 'NUMBER',
      unitCategory: 'Temperature',
      defaultUnit: '°C',
      isFilterable: true,
      sortOrder: 18,
    },
  ],
};
