export const SPATIAL_MODEL_REPOSITORY = 'SPATIAL_MODEL_REPOSITORY';
export const SPATIAL_ANCHOR_REPOSITORY = 'SPATIAL_ANCHOR_REPOSITORY';
export const SPATIAL_NODE_REPOSITORY = 'SPATIAL_NODE_REPOSITORY';
export const SPATIAL_LAYOUT_REPOSITORY = 'SPATIAL_LAYOUT_REPOSITORY';
